### ISSUE TITLE
Swap logo with tenant

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#1]
Active logo swapping to the tenant application being used. If it's on the shop. subdomain, the default CompLinks logo should be inserted.

**Comment by cgladue** [comment]
how would you like this data delivered to you ... in the form of a classname that is configured in the DB and that classname gets applied to style the page ?

**Comment by ChrisASearles** [comment]
Seems like the easiest way would be to upload the logo in the tenant detail on the back end and just pass the image URL down to the Layout page (moving it to a partial might work best). Will leave the implementation details up to whatever you prefer or think is best.

We changed the way this was working to drive all the layout changes from the database, simplify the theming process, and eliminate the need to deploy a new stylesheet whenever a new casino signed up.

We can lump this in with #6 to bundle the model changes in a single update.

**Comment by cgladue** [comment]
how will you handle the other style changes colors fonts etc etc ?  should come up with a better overall method instead of just passing the image url since more will change then just the image

**Comment by ChrisASearles** [comment]
@cgladue Just want to verify this comment was before we worked out the logic to change the theme and you're good with this, correct?

**Comment by cgladue** [comment]
yes i should be, i dont know which views you would need it tho, where
should i pass it to you ?  or do you need it in all views

**Comment by ChrisASearles** [comment]
I'd create the logo as a partial view with it's own controller action. @Dwells7583 can we bundle this partial together with the whole nav menu?

**Comment by robgpeak** [comment]
For easy reference, here is the link to the default CompLinks logo for the shop subdomain https://drive.google.com/file/d/0B1Ggj9_E3xjJaFlvc1MzRU1rMTg/view?usp=sharing

**Comment by ChrisASearles** [comment]
@cgladue This should be working but it looks like I'm not getting the correct logo sent down.

**Comment by cgladue** [comment]
@ChrisASearles What do you mean ?  you get the logo int he Partner object and its working on doverdowns and shop subdomains
