### ISSUE TITLE
Getting the pages to load faster

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#100]
It's not the images that are slowing the page loads, it's something else.  I have no idea what but we need to find out what it is and fix it.

https://developers.google.com/speed/pagespeed/insights/?url=Shop.complinks.co&tab=desktop

This is one thing I found, but there are probably better tools out there to help pin point the bottleneck.

**Comment by cgladue** [comment]
the server is only running on 1GB of ram and very small CPU so it may be resources on the server slowing this down too for now.

**Comment by robgpeak** [comment]
My spider senses say that it is more likely a script or coding that is causing it, and a way to test it would be to load a page from the same place that does NOT use any scripts, but is very rich in graphic content (big image files, etc.) and compare the load times.  Do you have something that you can use to test it?

How much would be it be to upgrade to something better and faster on AWS?

**Comment by cgladue** [comment]
@robgpeak 

https://aws.amazon.com/ec2/pricing/on-demand/

Currently the web server is a "t2.micro" instance with 1 GB ram and 1 core costing about 1.2 cents per hour (or $8.93 a month)  you can go anywhere from there to x1.32xlarge  with 1952GB Ram and 128 cores at 13.338 an hour ($9,923 a month)

**Comment by robgpeak** [comment]
Let's first test the script theory.
