### ISSUE TITLE
The site not showing properly in Safari

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#102]
I am not sure why there is a major compatibility issue with the site and Safari, but that needs to be fixed.

**Comment by ChrisASearles** [comment]
Just pushed up some fixes across the board that should solve (I believe) all of the flexbox layout issues we've been seeing. My iPhone emulator is showing some issues but I can't test live to see if it's just a problem with the emulator until these get up live.

**Comment by cgladue** [comment]
@ChrisASearles @robgpeak just published the changes
