### ISSUE TITLE
Time stamp on the server needs to be adjusted to EST

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#103]
@cgladue I just signed up for a new test user account (dd_test@peakmarketing.com) under the doverdowns subdomain at 7:50PM EST, but when I look at the record in the User view of the back end, The time stamp in the Created column reads 11:50PM

**Comment by cgladue** [comment]
Database server was still set to UTC, changed timezone to **America/New_York**

**Comment by robgpeak** [comment]
And that was seemingly only the new user registration database because the shopping trip recorder the correct time...  Strange.
