### ISSUE TITLE
Limiting the number of text links that display by default

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#105]
@cgladue trying to think of a way to limit the number of text links that display in the deals and promotions section of the advertiser index page.  Some advertisers have hundreds... https://shop.complinks.co/AdminDashboard/Advertisers/Links/5587
https://shop.complinks.co/admindashboard/advertisers/links/6789

I was thinking, maybe we only show (mark the Active column "True" by default) deals and promotions that are past the Start on date, and the Expires date is within 90 days.

I know this might not be the ideal solution, but I would rather have store with 5 or 10 deal and promotions that are expiring soon, instead of 100s that expire in 2018.  Of course the other ones that expire in 2020 would still be in our advertiser links db and visible on the back end, but be marked false, and if some of them are compelling, we can manually mark them as true.

**Comment by robgpeak** [comment]
@cgladue Did you have any thoughts on this?

**Comment by cgladue** [comment]
i was thinking perhaps that whenever a user starts a trip using a link we increment a counter on that link, and we sort the links displayed by the popularity of the link, so the most used links would be at the top and the least used at the bottom.  id hate to not show a link that might entice someone to click it and buy something ....

**Comment by robgpeak** [comment]
That is a great idea. I love it.  But again, I think 200 links is just WAY too many to even start with.  

I may have mentioned this in another issue, but what if we could have the same functionality of selecting multiple records like we do in the activity stream and then mark them all true or false, for Active, or true or false for Featured, etc.  In essence, it batch processing records...  Hey look what I found;) https://screencast.com/t/XvzQJHPEJTP

**Comment by cgladue** [comment]
i believe you have the functionality you asked for in this screencast now...

**Comment by robgpeak** [comment]
Yep
