### ISSUE TITLE
removing the header images from the store index pages

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#106]
This might be a phase 2 or 3 thing where we could take the time to put header images on each of the internal store index pages, but for now we should take the same approach that was in the mock up https://app.moqups.com/robg/QSDVx2F07W/edit/page/ab309be6f where it reads, Shop <Name of Store>

**Comment by ChrisASearles** [comment]
The intention here was that we were going to pull the category header image from one of the categories the store was a member of. We thought it would be a good look for the store page. Right now the auto header was just a placeholder until the right data could be loaded. If you'd prefer no image that's fine, just wanted to explain the intent before you nix the design.

**Comment by robgpeak** [comment]
I appreciate the insight, and actually I Initially I thought the same thing.  But then there are a lot of companies that are in multiple categories, and it might seem confusing... Let's back burner it until we have time to put in more images.  Other fish to fry.  Additionally, (this will be a separate item for Phase 2 or 3), but we are going to have to think about sub-categories.  What we have hear now are primarily "Parent" categories, and we are going to need "Child" categories.
