### ISSUE TITLE
An approved advertiser not showing up in our back end

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#111]
@cgladue The advertiser Saks Fifth Avenue is not showing up in our db?

It was loaded from the original .json file, here is the record:

"advertiserId" : 13816,
"advertiserName" : "Saks Fifth Avenue",
"advertiserDescription" : "Saks.com offers a personalized, online shopping experience, providing an expansive assortment of the finest designer collections, accessories, cosmetics and home furnishings."
"advertiserCommissionAllFrom" : ,
"advertiserCommissionAllTo" : 0.03,
"advertiserCommissionSelectedFrom" : ,
"advertiserCommissionSelectedTo" : ,
"advertiserLogo" : "logos\lg_13816.jpg",

You can see in the activity stream that it has new links for this advertiser, but noting about it being a new advertiser...?  we received notification from the advertiser on 5/16/17 at 5:44pm via email that they accepted us in their program.

**Comment by cgladue** [comment]
As chris requested all new advertisers show up as INACTIVE.

so you have to click the INACTIVE filter or use this link and search for saks and its there...
https://shop.complinks.co/admindashboard/advertisers?filter=inactive

**Comment by cgladue** [comment]
that was requested in issue #28

**Comment by robgpeak** [comment]
Ah, gotcha.  No worries.

I found the record in the inactive filtered list, but it is still showing as notjoined.

**Comment by cgladue** [comment]
yea because of the issue with the Linkshare API that is returning both approved and declined advertisers when it should only be approved, i had to comment out the line of code that changed them to joined .. but if you activate them it wont matter if they are joined or not its just informational, as long as the advertiser has links and is active they will appear on the site.

**Comment by robgpeak** [comment]
@morganpeak This means in addition to using Activity Stream to see New Advertisers, we will have to continue to look at the emails in groove for New Advertiser notifications.

**Comment by cgladue** [comment]
just untill i get notification that they have fixed the API then i will add it back.

**Comment by ChrisASearles** [comment]
@cgladue is this issue closed?

**Comment by robgpeak** [comment]
@cgladue We just noticed about 100 "New Advertisers" in the Activity Stream, and I know "joined and notjoined" are for internal informational purposes, and @morganpeak  can mark the ones that she verifies from the linkshare site have actually approved us as "Active" "True", but in the manual procedure that Morgan goes through for her routine in managing the advertiser relationships, it would be helpful if she was able to manually mark them as joined or notjoined on the https://shop.complinks.co/admindashboard/advertisers/edit/7076 pages (as an example), which would then carry through so when she does a refresh on the list view https://shop.complinks.co/admindashboard/advertisers those advertisers would show up in their corresponding filters... 

Something like this at the bottom right of the image:

<img width="1073" alt="screen shot 2017-06-12 at 1 36 23 pm" src="https://user-images.githubusercontent.com/28393235/27046917-3cc0b1f4-4f74-11e7-929e-a2211570ecd9.png">

**Comment by cgladue** [comment]
@robgpeak @morganpeak This has been added.

**Comment by robgpeak** [comment]
Thanks
