### ISSUE TITLE
Name to display when user is authenticated

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#116]
If a user is logged in, we should display the just the user's First name, not first and last. If the "First Name" field in that users record is **blank or empty**, we should display the prefix of their email address. For example robg@peakmarekting.com would display "ROBG - 2,000 POINTS"

**Comment by ChrisASearles** [comment]
committed.

**Comment by cgladue** [comment]
published

**Comment by robgpeak** [comment]
I am not sure if this is the right thread for this issue, but when I look at the site on my default internet browser on my phone, I don't see anything in the header except the logo...  So not only is the name not showing up, but not even the search magnifying glass, or the hamburger menu.
![screenshot_2017-05-22-22-05-10](https://cloud.githubusercontent.com/assets/28393235/26335601/0cac9684-3f3b-11e7-859b-da22a104e022.png)

**Comment by ChrisASearles** [comment]
@robgpeak can you close that browser session out, open up a new one and verify you're still seeing what you posted here?

**Comment by robgpeak** [comment]
This is what shows up when I log in...
![screenshot_2017-05-23-11-41-21](https://cloud.githubusercontent.com/assets/28393235/26363013/bdd8f944-3fad-11e7-9c13-aa62efee7b8a.png)
