### ISSUE TITLE
Links of Store Boxes on home page are broken

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#117]
@cgladue @ChrisASearles The links from the store boxes on the home page to individual store index pages are broken.  The are currently going to https://doverdowns.complinks.co/~/stores/index/6241 and the "~" is bringing back a 404.

**Comment by ChrisASearles** [comment]
@cgladue I fixed the link to use the start trip link but I'm getting a 404 on these

**Comment by cgladue** [comment]
@ChrisASearles i went into Views/Home/Index.cshtml and swapped the links to use startTripLink 

some may not work correctly because there is no main link defined, so it will error out, but if it starts with /trip/start then it will work ok once rob sets the main advertiser link.

**Comment by ChrisASearles** [comment]
@robgpeak How do you want to handle the situation @cgladue is describing?

I see your options as:

1. Default to the link with the longest expiration date if a default hasn't been specified
2. Filter out advertisers that don't have a default link defined and don't display them
3. Hide the button if a default link doesn't exist.

**Comment by robgpeak** [comment]
Number 1 is OK, but number 2 and 3 are no good.  We will ALWAYS put in a default link manually.

**Comment by robgpeak** [comment]
So we will always show a button

**Comment by robgpeak** [comment]
Sorry for the short answer yesterday, I was on the road.  Let me elaborate a bit.

1. If a default link has not be manually selected by Morgan or someone else in the back end, then YES use the link with the longest expiration date as the default link.

2. By doing number 1, we will NOT have any advertisers with no default link, so I think that makes 2 moot.

3. As mentioned above, we must always have a default 'main advertising' link.  So I know right now, it is programmed to NOT show a link (Shop Now Button) if there is no main advertiser link in the back end, and that's fine.  I just means we will have to manually select a default link from the back end.

**Comment by ChrisASearles** [comment]
@cgladue any update on this?

**Comment by robgpeak** [comment]
Seeet
