### ISSUE TITLE
Layout for Deal & Promotions Containers on Store Index pages

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#123]
It was easier to show you with a screencast of what I was looking for... https://screencast.com/t/fk9hwFVvQN  Please let me know if you have any questions.

**Comment by ChrisASearles** [comment]
That layout presents a challenge on mobile. @Dwells7583 can you try to accommodate a bit of what Rob's looking for in something that works in a responsive layout?

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
Looks good, but please refer to all the comments I made on #199
