### ISSUE TITLE
All links taking a user off our site must start a shopping trip, and be launched in a new browser tab

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#124]

**Comment by ChrisASearles** [comment]
@cgladue I've noticed a few different links that are passed with each of these records, can we change the models that are being passed to include just the link that should be used on the frontend to avoid any confusion now and in the future about which link to use?

@Dwells7583 we need to go through the site and ensure we open anything that links out in a new tab.

**Comment by ChrisASearles** [comment]
@Dwells7583 hold off on your part of this until further notice, I'm going to solve a couple of these with display templates.

**Comment by cgladue** [comment]
Already added to the view model.  The property is startTripLink.

**Comment by cgladue** [comment]
use Advertiser.startTripLink property

**Comment by ChrisASearles** [comment]
This should be primarily resolved everywhere but the store detail page and will change a bit with the new display templates so I'm going to close this out. From here out if there is a link found that's not behaving appropriately, please provide steps to reproduce with device and browser information so we can narrow down particular issues.
