### ISSUE TITLE
Main nav at mobile size

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#128]
The display on the nav at mobile needs to be cleaned up. Search should be right aligned next to the person icon, the logo needs to be constrained, the menu button is getting cut off, etc.

**Comment by robgpeak** [comment]
As a follow up on this, if you look at http://www.357am.com/CL/client/index.html in your mobile device, and then click the hamburger menu and click featured, and you can see when the header does when someone is logged in.  At least it's different from ebates;). I think it looks nice.

**Comment by cgladue** [comment]
@robgpeak pending your review
