### ISSUE TITLE
Paged stores on category page

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#129]

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
published

**Comment by robgpeak** [comment]
While I can see the paged stores at the bottom of the page, that was not really what I was looking for.  The idea was to have the pages just for the Store Boxes section, so it would show only 8 or 12 boxes, (3 or 4 rows), and then someone could page through the rest.

I would actually rather have the "All <Category_Name> Stores" section be a complete scrollable list from A-Z without the pagination feature.  I know it would make the page very long, but that's OK

As for the original idea of the pagination of the Store Boxes, let's nix that, and instead, we will just use the order of the stores in their individual category listed order.  For example, the order listed in https://shop.complinks.co/admindashboard/advertisers/setAdvertiserDisplayOrder/10 should appear in the Featured Automotive Stores section (i.e. https://shop.complinks.co/category/index/10).

This is what I tried to describe in #25 I will try to articulate it a little better in #25 now...

**Comment by ChrisASearles** [comment]
Made the change but can't test it b/c of #151

**Comment by ChrisASearles** [comment]
Paging removed, waiting on a resolution to #25 for the sort.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
I just cleared my cookies and browsing history, and I am still seeing the area for the page numbers at the bottom of the Deals and Promotions section...  I would like to remove the colored bar and the numbers all together.
<img width="858" alt="screen shot 2017-05-31 at 5 22 25 pm" src="https://cloud.githubusercontent.com/assets/28393235/26654754/f7aaea46-4625-11e7-9941-461b0adf6926.png">

**Comment by ChrisASearles** [comment]
@robgpeak this issue is related to the Category page, you're looking at the Store detail page.

**Comment by robgpeak** [comment]
Gotcha

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
@robgpeak Published
