### ISSUE TITLE
User info and point total on side nav needs to load real data

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#13]

**Comment by cgladue** [comment]
i will make the data available in the viewmodel, but you need to change the way the side nav is for non authenticated session before this will work

**Comment by cgladue** [comment]
i have added the User object to the HomeIndex view model.  The data is now available but long names or large point balances is causing the display to wrap.

**Comment by ChrisASearles** [comment]
This data needs to be available to the Layout page, we need to tie this to #41 to load data via a partial.

**Comment by cgladue** [comment]
So two seperate partials one for the User Info and one for Categories/Featured Advertisers then, correct ?

**Comment by ChrisASearles** [comment]
I updated this and this should only load production data now based on user login status.
