### ISSUE TITLE
First option in nav menu is always active

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#130]
If you click on either of the nav menu options "Shop Categories" or "Featured Stores" the first menu item in each of them is already "highlighted" as if someone's cursor is hovering over it.  None should be "highlighted" until the cursor has hovered over that menu item.

![uploads/d82bfe14-f48e-4229-a7a5-00f4596c4792/Screen Shot 2017-05-24 at 8.50.57 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd82bfe14-f48e-4229-a7a5-00f4596c4792%2FScreen+Shot+2017-05-24+at+8.50.57+AM.png)

**Comment by ChrisASearles** [comment]
This actually just got magnified a bit by the fix I just pushed to reorder the columns for you, unfortunately I'm not sure what the solution is going to be yet as I believe it's a bug in Angular Material. I'm going to reach out to that team to see what's going on there.

**Comment by ChrisASearles** [comment]
This is a bug in the Angular Material framework so to get around it for now I disabled the active hover entirely, the ripple effect is still active.

**Comment by cgladue** [comment]
@robgpeak Published
