### ISSUE TITLE
Change second 'Join Now' button to 'How It Works' button when user is Authenticated

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#131]
In the section below, please use the same functionality that you use in the Hero Image section that changes the 'Join Now' button into a 'How It Works' link, that will go to the How It Works page.

![uploads/7f869579-bc11-4278-bf24-dbad5a9a6d78/Screen Shot 2017-05-24 at 9.36.29 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7f869579-bc11-4278-bf24-dbad5a9a6d78%2FScreen+Shot+2017-05-24+at+9.36.29+AM.png)

**Comment by ChrisASearles** [comment]
Would you rather we just hide this section for logged-in users?

**Comment by robgpeak** [comment]
No, I still like the section, and I would like to leave it there and have people that are logged in click the link that says "Learn More" (I know earlier on I said the link should read "How It Works", but it should read Learn More, and go to a mock up of this page https://app.moqups.com/robg/QSDVx2F07W/edit/page/acd4932ab

**Comment by Dwells7583** [comment]
@robgpeak and i spoke on friday about this. It will be learn more regardless of authenticated or not.

**Comment by cgladue** [comment]
What do I need to do for this?  It's just a link change right.  The image isn't changing

**Comment by ChrisASearles** [comment]
@cgladue nothing, just assigning to you to publish and re-assign

**Comment by ChrisASearles** [comment]
(I'm pretty sure it already has been published, just keeping the process consistent)

**Comment by cgladue** [comment]
@robgpeak pending your review
