### ISSUE TITLE
Functionality of Featured Stores containers to the right of hero image on home page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#132]
I wanted to ensure the Featured Stores containers (image below), have the same functionality as the Featured Stores containers at the bottom of the home page, whereby a user clicking anywhere in the overall container EXCEPT the Show Now button, will take the user to the particular store index page, but if the user clicks the Shop Now button would start a shopping trip in a new browser tab.

This should be the same functionality in the Store Boxes.

![uploads/b3794d08-e7a4-406f-8104-b23948c39aa4/Screen Shot 2017-05-24 at 9.41.04 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb3794d08-e7a4-406f-8104-b23948c39aa4%2FScreen+Shot+2017-05-24+at+9.41.04+AM.png)

**Comment by ChrisASearles** [comment]
I believe the next time @cgladue pushes a new version up this should be taken care of.

**Comment by cgladue** [comment]
i just pushed it, but there are a lot of errors if you look in the Console, and the site dosnt look right to me, is something not included int he project correctly ?

**Comment by cgladue** [comment]
published

**Comment by robgpeak** [comment]
For the purpose of this specific issue of having the link from the overall box lead to the store, and the Shop Now button to actually start a trip, it is almost complete.  The Shop Now buttons do NOT currently start a shopping trip in a new tab, and the URL that it is gong to does not exist.  I think this was assigned to me pre-maturely.

**Comment by ChrisASearles** [comment]
@robgpeak It actually does but there are no default links defined for those advertisers and #117 is not yet complete. I'm going to close this issue as complete and will request an update on the status of #117

**Comment by robgpeak** [comment]
I just clicked on the Macy's Shop Now button, but the link is broken and does not work, yet there is a default link for Macy's. Additionally, it should pop open in a new tab but it does not.

**Comment by ChrisASearles** [comment]
New tab is fixed

**Comment by cgladue** [comment]
done
