### ISSUE TITLE
Change Hue Usage

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#133]
Allowing users to specify hue shades via partner config won't work based on testing. Consistency can't be guaranteed in colors, we need to move to allowing users to config the primary and accent palette's, and we're going to specify the hues that will be used.

@Dwells7583 you need to go through the project and replace all 'hue-1' 'hue-2' references with specific hue values.

@cgladue You can remove everything from the Style info class and the JSON that's being stored for styles in the DB but the primary name and the accent name.

**Comment by cgladue** [comment]
ok, so CL Staff wont be storing Style info in the DB for each partner then ?  will you go back t the individual css file per partner ?

**Comment by Dwells7583** [comment]
I completed my side of this. I assigned it to @cgladue

**Comment by ChrisASearles** [comment]
@cgladue no changes other than we're just not using the hue values anymore. I actually modified your code a bit because we needed a theme color name for both the primary and the accent which we're still using. You h honestly don't have to change anything but we'd just have to keep providing those values that font get used. Your call either way.

**Comment by ChrisASearles** [comment]
@Dwells7583 you missed a bunch in the Layout page that Chad had mocked up with the values from the partner theme. There also seems to be a color declaration somewhere that's missing a closing ' after the value. It's a primary-900 but I'm not sure if it's coming from one of the aforementioned styles in the DB or if it's  one of the ones you just changed.

**Comment by ChrisASearles** [comment]
@Dwells7583 You also changed the bg on the sign up button to the accent color, was that intentional?

**Comment by Dwells7583** [comment]
@ChrisASearles  I wanted it to stand out a big more, but now that I think about it, it may not look well with other colors. I changed it back to the primary color.  I fixed the ones I missed as well.
