### ISSUE TITLE
Change hierarchy of elements on smaller screen sizes

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#136]
When a user is on a store index page on a small screen (like mobile) the order of appearance of the elements should be, (1) the main logo, points/$ and shop now button container, (2) the name of the store header and description container, (3) Conditions header and container, (4) Deals & Promotions header and containers, (5) Shop Similar Stores header and containers.

**Comment by Dwells7583** [comment]
this has been updated

**Comment by cgladue** [comment]
@robgpeak pending your review

**Comment by robgpeak** [comment]
BadaBing BadaBoom.  Nice.
