### ISSUE TITLE
The links to the store index pages in the "All <Category_Name> Stores" sections in all the categories are broken

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#137]
The links are going to ../store/index/...  and store needs to have an "s" and must be ../stores/index/..  This is the second time with the same error.

**Comment by ChrisASearles** [comment]
Updated and I believe I fixed all of these throughout the display templates but I can't test this page pending #151.

**Comment by ChrisASearles** [comment]
Should be good to go.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
Cool
