### ISSUE TITLE
Confirm Email Page Issues

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#140]
/Account/ConfirmEmail has issues (link color vs bg color - very noticeable on DoverDowns version, no link breaks between sections, etc.). This doesn't need to be anything fancy but those minor issues should get sorted out quickly.

**Comment by Dwells7583** [comment]
updated.

**Comment by cgladue** [comment]
@robgpeak pending your review

**Comment by robgpeak** [comment]
I am not really sure what I am supposed to be looking for, but I suppose it is acceptable.  I think it would look nicer if all of the login screens and the email confirmation screens, were smaller "Overlays" to the home screen, with a 50% opacity filter over the main home page screen.  It would look sort of like the mock up...  https://app.moqups.com/robg/QSDVx2F07W/edit/page/a93e4a7ba

Maybe this is a back burner thing, as there are more pressing issues we need in place.
