### ISSUE TITLE
Unable to upload "Current Authenticated Hero Img"

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#142]
@cgladue In the Edit Advertiser, I am unable to upload a Current Authenticated Hero Img  I was on https://shop.complinks.co/admindashboard/partners/edit/10 and I tried to upload the image https://drive.google.com/file/d/0B1Ggj9_E3xjJT0xENmlaX1VHZUE/view?usp=sharing  It tells me that is saves, but nothing shows up.

**Comment by cgladue** [comment]
it did save the file, i will look at why it isnt showing on the front end...

https://s3.us-east-2.amazonaws.com/complinks/partners/10-hero_shop_authenticated.jpg

[image: Inline image 1]



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=chadgladue@gmail.com&idSignature=22>



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I don't even see it in the back end?

**Comment by cgladue** [comment]
@robgpeak pending your review

**Comment by robgpeak** [comment]
Working now!  Thanks.
