### ISSUE TITLE
Adding a line in the right hand side user menu

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#144]
Looks like we need a line between "Shopping Trips" and "Redemptions" on the logged in user menu on the right hand side of the screen.

![uploads/ddec6a5b-f9ca-4a05-8d8a-e9b83a93600b/Screen Shot 2017-05-31 at 1.01.40 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fddec6a5b-f9ca-4a05-8d8a-e9b83a93600b%2FScreen+Shot+2017-05-31+at+1.01.40+PM.png)

**Comment by ChrisASearles** [comment]
Commiitted.

**Comment by cgladue** [comment]
@robgpeak Published
