### ISSUE TITLE
Adjustment to "All <Category_Name> Stores" section containers.

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#145]
The individual "All <Category_Name> Stores"containers behave differently in different screen sizes, and I would like them to be consistent.

At full desktop screen res. they do NOT contain the advertiser logo image, but at the smaller screen res. it does.  Based on the ultimate objective for the "All <Category_Name> Stores"section described in #129, let's just use the text of the store name at all screen sizes, and leave it sorted alphabetically.

Additionally, at the smaller screen sizes, the "Shop Now" button changes to a shopping cart, and that is confusing.  Please leave it as a "Shop Now" button, consistent with all the other Shop Now buttons on the site.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
This issue is behaving a little strangely, and I actually started another issue as a result of it #199 with a screenshot.

As a follow up on this issue, the shopping cart icon is showing up on the Deal and Promotions sections of all the store index pages on the smaller screen, and they too should have the Shop Now button as well.  They DO currently show up full screen width, so that's good.

I suspect there may be some sizing issues with the amount of horizontal real estate given the description of the deal/promotion and the "Shop Now" button, but I have faith you'll make it work and look good.  The shopping cart icon is definitely not an option.  Maybe the Shop Now button can go on the row below the deal/promo description, where the expiration dates are, but right justified, while the expiration date is left justified.  Just be cognizant of the buffer space (padding), of the button so it looks consistent with the spacing in relations to all the other Shop Now buttons and their corresponding containers.

**Comment by Dwells7583** [comment]
updated.

**Comment by cgladue** [comment]
@robgpeak published
