### ISSUE TITLE
Change Complinks logo in footer

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#146]
Please change the logo.png in the footer of ALL subdomains to this image https://drive.google.com/file/d/0B1Ggj9_E3xjJc29KNFpPaXpkUHM/view?usp=sharing

**Comment by Dwells7583** [comment]
Do you have a better quality image. even the .eps, I can then use the svg file and it will scale with perfect pixel resolution. @robgpeak I added it for now, but maybe you can send me the original art file

**Comment by robgpeak** [comment]
Here is the original original big clean version, but I don't know how to change it so everything is white.  Can you do that?  Then add the "Powered by"  See if you can work with that, but in the mean time, I will ask the guy that created it to get me the raw original files.

![logo_white](https://cloud.githubusercontent.com/assets/28393235/26677490/3f16482a-469a-11e7-900c-f55115e670bf.png)

The logo is actually attached above, but you can't see it cause it's white.  Here it is on google.  https://drive.google.com/file/d/0B1Ggj9_E3xjJUkt6VGJkcGxnVjg/view?usp=sharing

**Comment by Dwells7583** [comment]
. I did update the logo for now though, will update again when I get the art file.

**Comment by robgpeak** [comment]
It's not showing up on my view yet, but I am assuming it's because it hasn't been pushed live to the main server yet.
