### ISSUE TITLE
Main link on store index page not launching in new tab

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#147]
If you visit any store's index page and click on the main Shop Now button at the top of the page in the container that has the logo, it starts a trip, but does not do it in a new tab.  The Deals and Promotions shop now links do open in a new tab, so that's good.

Examples:
https://shop.complinks.co/stores/index/5339
https://doverdowns.complinks.co/stores/index/5464

**Comment by robgpeak** [comment]
@ChrisASearles I would like to start some testing of the site this week with Dover Downs customers, and this issue is an important one to be working properly, so please move it up the priority list.

**Comment by ChrisASearles** [comment]
Commited.
