### ISSUE TITLE
Adding <Partner_Name> to How it Works section

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#149]
As we are building an extension of the casino partner's existing rewards program, I want to reference that brand name of the casino's rewards program throughout our site in various places.

First and foremost will be on the Home page in the call out section that links to (through the "Learn More" button) to the How it works page.

The copy on this text overlay on the image below, we want to change the copy from "Your favorite casino just made it..." to, "<Partner_Name> just made it..."

![uploads/903e61c9-dfba-41e1-a498-2b6663e6e7eb/Screen Shot 2017-05-24 at 9.36.29 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F903e61c9-dfba-41e1-a498-2b6663e6e7eb%2FScreen+Shot+2017-05-24+at+9.36.29+AM.png)

The Partner Name is coming from the "Name" column on the page below, which is of course editable

![uploads/afde71c1-2808-4476-8fdb-d3b4a797eb49/Screen Shot 2017-05-31 at 2.25.32 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fafde71c1-2808-4476-8fdb-d3b4a797eb49%2FScreen+Shot+2017-05-31+at+2.25.32+PM.png)

For example, in the case of the subdomain for doverdowns, the copy would read: "Capital Club® just made it..."  On the shop subdomain it would read, "CompLinks just made it..."

On the How it works page itself, we will change the following copy to include the <Partner_Name>.

Section 1.
As a <Partner_Name> member, you already earn points for playing casino games, but what if you could earn points even when you're not in the casino?

{the rest of the current copy remains as it is in section 1}

[As an internal note to us, the partner name we put in that editable field in our database which we will be pulling from to populate <Partner_Name> WILL be the brand that customer's are familiar with as their rewards program.  So for example in the case of Foxwoods, we currently only have "Foxwoods" in there as the Partner Name, but eventually it will become the proper name of the Foxwoods Rewards program.  So if the name is Foxwoods Rewards, it would be "As a Foxwoods Rewards member, you already earn points..." and that will be perfect.]

Section 2.
<Partner_Name> just made it easier than ever for you to earn more comps, faster!

{the rest of the current copy remains as it is in section 2}

Section 3.
No changes needed.

**Comment by robgpeak** [comment]
I'm not sure what this was marked as Review and assigned to me?  I did a cache clear, and shirt refresh, but it does not look like anything was changed?

**Comment by cgladue** [comment]
i have not published any of chris' or derk's changes yet, will do in a little bit

**Comment by robgpeak** [comment]
Oh, OK.  I saw them in my review screen, and I was just cleaning house;)

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
Nice!

**Comment by robgpeak** [comment]
I am not sure who would do this, but this functionality should be in place even for unauthenticated users.  Currently if I am NOT logged in, it reads, "Your favorite casino..." instead of "Capital Club®" (or whatever the casino partner name is), and it should.

**Comment by robgpeak** [comment]
@ChrisASearles I'm pretty sure this is an easy fix, and it would be nice to have done for my demos

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
@ChrisASearles Should this last comment I just made on this thread have been a new issue?

**Comment by Dwells7583** [comment]
I will take care of it as part of this one. @robgpeak

**Comment by Dwells7583** [comment]
This is complete.
