### ISSUE TITLE
Increase password required length to 8 characters and remove all other requirements

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#15]
Adding two more required characters is significantly more secure than requiring rules that will force users into using more common passwords and don't significantly increase the time required to brute force a password. I'd love for the length to be 10 characters but I think 8 is a reasonable compromise given the purpose of this website and the lack of ability for someone to do just about anything malicious should they gain access to a user's account.

**Comment by cgladue** [comment]
the requirements were the default requirements as a starting point.  I disagree we dont need to require at the very minimum upper case and/or numbers as well...  it can be increased to 8 characters, but require numbers and/or punctuation as well.

**Comment by cgladue** [comment]
removed all restrictions but length.
