### ISSUE TITLE
Things look a little screwy on ipad in chrome

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#152]
Here is a view from my ipad (using chrome on the ipad, latest version 58.0.3029.113)

![uploads/bf4389ab-ad46-45ae-9824-dd2f1111d438/IMG_0037.PNG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbf4389ab-ad46-45ae-9824-dd2f1111d438%2FIMG_0037.PNG)

and here are the specs of the ipad...

![uploads/aecea6f3-94b2-4f69-9f2b-3cacad526702/IMG_0038.PNG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Faecea6f3-94b2-4f69-9f2b-3cacad526702%2FIMG_0038.PNG)

**Comment by ChrisASearles** [comment]
@robgpeak Pretty sure this will get sorted out with the other flexbox browser bugs we're trying to work around for Safari but can you just provide the iOS and iPad version (2, 3, air, air 2, etc.)?

**Comment by robgpeak** [comment]
I have two different ipads.  I have the old one, iPad 2 with the iOS 9.3.5  And my wife has a newer one, the iPad Air with iOS 10.3.1.  Oddly enough, it looks the same on both ipads in safari and chrome 58.0.3029.113.

As for Safari on my laptop, I just saw I am using version 8.0.5, so that is too old to really tell anything, so I won't even look at the site in that browser...

**Comment by ChrisASearles** [comment]
Related to the same problem reported in #102
