### ISSUE TITLE
Pull Ads into Display Templates

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#153]
This is done, can't test pending #151

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
I'm not sure what I am supposed to be looking at/for on this one.  Having said that, if it has something to do with the image ads for certain advertisers, I think we need to include a line of text under the ad that mentioned the advertiser's name, and the "x points/$".  And in the even that there are multiple image ads on the same page, we should put in a horizontal line as a separator.

Mock up below...
<img width="483" alt="screen shot 2017-05-31 at 5 47 43 pm" src="https://cloud.githubusercontent.com/assets/28393235/26655564/52fa5adc-4629-11e7-858b-090378d1849b.png">
