### ISSUE TITLE
left and right hand margins needed on T&C, Privacy and FAQ pages

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#154]
The T&C, Privacy policy and FAQ paged need to have more spacing from the left and right margins on the page.  It looks like it is set to 0 at the moment.  It should be the same buffer that all the other pages with text content have like the how it works page...

**Comment by robgpeak** [comment]
This is another one that is in "review" but I did not see a change on the pages https://doverdowns.complinks.co/terms-and-conditions and https://doverdowns.complinks.co/privacy-policy

**Comment by cgladue** [comment]
@robgpeak published
