### ISSUE TITLE
Naming convention for rewards points

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#156]
@cgladue I might need a refresher course on how to name the rewards for each casino partner.

Meaning, on the front end in the "Rewards Description" on this page...

![uploads/cbde118b-6e7e-4f33-a96f-2b6d5cf5d3cd/Screen Shot 2017-05-31 at 6.10.11 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcbde118b-6e7e-4f33-a96f-2b6d5cf5d3cd%2FScreen+Shot+2017-05-31+at+6.10.11+PM.png)

...it reads "40 CompLinks Rewards Points" and I am guessing this is because I logged in and set this account up through shop.complinks.co and the name of the partner is CompLinks, so the reward set for that partner is "{0} Rewards Points" and "{0}" is pulling the Partner Name from the db.  So if I was to do this same thing through doverdowns.complinks.co it would show up with "40 Capital Club® Rewards Points"...?  If so, that would be great.

**Comment by cgladue** [comment]
You are correct {0} is a placeholder for the partner name field and for any redemptions on Dover downs subdomain will show Dover downs program name.   This way this one reward can be used on all partners with different names.

**Comment by robgpeak** [comment]
Excellent
