### ISSUE TITLE
Individual store header images not working

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#157]
@cgladue just for shits and giggles, I wanted to upload a header image for macys (https://shop.complinks.co/AdminDashboard/Advertisers/Edit/6789) and it says it saved successfully, but nothing shows up in the front or back end...

This is the file I uploaded... https://drive.google.com/file/d/0B1Ggj9_E3xjJMWs0RDU4MGJpb28/view?usp=sharing

**Comment by robgpeak** [comment]
Just tried another one to be sure it was not an isolated case with Macys.  https://shop.complinks.co/AdminDashboard/Advertisers/Edit/6712 and image https://drive.google.com/file/d/0B1Ggj9_E3xjJTU1xbHZ4MmNFVzQ/view?usp=sharing

**Comment by cgladue** [comment]
@robgpeak try it now, i fixed the bug

**Comment by robgpeak** [comment]
cool

**Comment by ChrisASearles** [comment]
Guys, this is why we have a process in place. This was not a bug. Issue #106 specifically asked for the removal of this image. This never got assigned to anyone, placed in a milestone, or triaged at all, and yet it's back in already?

**Comment by robgpeak** [comment]
Keep in mind Chad like to code in order to relax, so I was just helping him chill out :)
