### ISSUE TITLE
Approved advertiser not showing as joined

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#158]
@cgladue I think this happened when LS had that API snafu.  Saks Fifth Avenue but is showing approved on http://cli.linksynergy.com/cli/publisher/programs/advertisers.php?cat=1&advertiserSearchBox=Saks%20Fifth%20Avenue&exactMatch=0 but https://shop.complinks.co/admindashboard/advertisers/edit/6786  has it as not joined.  We need to change that.

**Comment by cgladue** [comment]
while the joined or notjoined has no other meaning then to let you know whos int he program and whos not i will change it, but it would still work as long as there were links loaded for that advertiser, but i have changed saks to joined in the meantime waiting from LS
