### ISSUE TITLE
Adding points manually

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#159]
@cgladue we need a way in the back end that will allow CL staff to add points to a users account manually for certain adjustments. i.e. goodwill credit, etc.

**Comment by robgpeak** [comment]
As a follow up to this, and how it might sort of relate to #112, when a CL rep manually adds points to a user's account, normally it will NOT show as "earned" to the end user, but it will show up in the total balance, and be redeemable immediately. However, if the points were actually earned and credited manually, they should be able to be tagged as earned.

**Comment by cgladue** [comment]
Go to Users page, and view transaction history, at the top is an option to add transaction 

![image](https://user-images.githubusercontent.com/7914133/26924843-6a597806-4c15-11e7-9426-00f75256e862.png)

**Comment by robgpeak** [comment]
Looks great.  Please change the names of the "Types" to **Points Adjustment, Points Earned, and Points Redeemed** including the "s" on the word Points.

**Comment by cgladue** [comment]
@robgpeak All Set

**Comment by robgpeak** [comment]
OK, looks great.  Just realized, we will need to be able to remove someone earned points as well.  If someone returns a product, charges back, etc.  And of course, there should always be a master record somewhere keeping track of all these transaction adjustments and who is making them (which CL user).

So I will leave it open in this issue and change the name to Adding and "subtracting" points manually.
