### ISSUE TITLE
missing links for joined advertiser

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#160]
@cgladue looks like we are missing links for a joined advertiser Groupon https://shop.complinks.co/admindashboard/advertisers/edit/6945  Maybe another LS issue.

**Comment by cgladue** [comment]
if they are in LS then it is the same issue they have still not resolved
it, and do not have any updates when i keep asking...



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=chadgladue@gmail.com&idSignature=22>



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Can you please forward me the email thread you've had with LS support, and I will follow up with a phone call to them

**Comment by robgpeak** [comment]
Just called them and they are still working on it.  In the mean time, is there a way to override the API and add the advertiser manually?  Meaning, they are showing up as Joined, and Active, but none of the data in the description and conditions sections on the store index page are being displayed?

**Comment by cgladue** [comment]
links were added, sometimes the links arent available immediatly so then it takes 24 hours before i update the advertiser (and links/ads) again so the next time around the links pulled and are there now.
