### ISSUE TITLE
Constraining the image size of advertiser logo on store index page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#161]
Am I looking at this wrong?

It seems like, if the natural image size is 40px high, when it appears on the store index page, it adjusts the height to 56px.  Or maybe that is just the container the image is in...

Anyway, there are some advertiser logos that are bigger than 40px high, but look great in the store boxes, but when you get to the store index page, they appear their normal size, and are NOT constrained to the 56px height restriction.

Two examples that you can see on the home page are Godaddy and Macys.  They look great in the store boxes, and/or the feature boxes, but then click into the store index pages, and reduce the size of your browser a bit and you'll see what I mean.

See the screenshots below.  Does this mean the only fix is the make sure the advertiser logos are all 40px high max?

![uploads/5df69eef-cbba-4937-8fef-61b630e35868/Screen Shot 2017-06-01 at 1.09.49 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F5df69eef-cbba-4937-8fef-61b630e35868%2FScreen+Shot+2017-06-01+at+1.09.49+PM.png)

![uploads/1d0df9e3-4889-4555-a12e-29bc96afa32d/Screen Shot 2017-06-01 at 1.21.03 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1d0df9e3-4889-4555-a12e-29bc96afa32d%2FScreen+Shot+2017-06-01+at+1.21.03+PM.png)

**Comment by robgpeak** [comment]
As a follow up, I was just able to find a smaller godaddy logo, and I replaced it, so now the natural size is 40px h.

**Comment by robgpeak** [comment]
This is a low priority item, but I am going to reopen it and add a bit of clarification to the fix, so it is a better fix.  In addition to restricting the height to no more than 60, we should also restrict the width to a maximum of no more than 150px wide.

If it is a quick fix, then by all means, put it in place, otherwise, it can wait.

**Comment by cgladue** [comment]
@robgpeak Published
