### ISSUE TITLE
The big How it works background image blew up, but only on https://doverdowns.complinks.co/

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#162]
For some reason the image that is the background of the section that links to the how it works page, expanded, and is blowing up the page all of a sudden.  visit https://doverdowns.complinks.co/ to see it.  But is is not happening on shop...  And actually, it is only on the desktop screen resolution, becasue it looks fine on the phone...

**Comment by cgladue** [comment]
i think it looks ok on my pc, 

can you try holding down the SHIFT key and pressing F5 ?

**Comment by robgpeak** [comment]
Shit, I guess I should have mentioned it is ONLY happening in firefox.  I'm using v. 53.0.2 (64-bit) on my laptop and 50.1.0 on my desktop, same result.

https://screencast.com/t/n4AMJ4iG7o

**Comment by ChrisASearles** [comment]
Checked on Firefox 53 on Sierra and Win 10 and I'm not seeing any issues. Try clearing cache.

**Comment by robgpeak** [comment]
If you look at the screencast I did, you can see I cleared the cache, and am using an incognito window (private in Firefox), and it is still happening.  https://screencast.com/t/n4AMJ4iG7o

Maybe it's because of the mac.  But again, it was working fine yesterday, just not today.  AND, it's on both of my machines in firefox...  very strange.

**Comment by ChrisASearles** [comment]
I ran it in FF53 on Mac Sierra without a problem. What OS version are you running on?

**Comment by ChrisASearles** [comment]
Sorry Rob, read through this a little too fast and thought you were talking about the hero image. I can confirm I'm seeing the same thing on FF on the Mac.

**Comment by robgpeak** [comment]
no worries, at least I am not losing my mind.
