### ISSUE TITLE
Replacing dummy info in You May Also Like section store boxes

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#164]
I saw something mentioned in #107 that there was dummy information in the store boxes that show up in the You May Also Like section, and I was wonder when that might be resolved so it is real information with stores that are in similar categories to the stores in the search results?

**Comment by ChrisASearles** [comment]
Is this in reference to the search results page?

**Comment by robgpeak** [comment]
Yes

**Comment by ChrisASearles** [comment]
Loading real data as of a few days ago. I'm not sure how they're being chosen, @cgladue ?

**Comment by robgpeak** [comment]
I think we are talking about two different things.  I was not asking how they are being chosen in this issue, and was/am saying, the store boxes that show up in the "You May Also Like" section AFTER you do any search, the results that show up are not real. 

I referenced #107, specifically the comment that Derek made (image of it below)...
<img width="858" alt="screen shot 2017-06-01 at 10 49 39 pm" src="https://cloud.githubusercontent.com/assets/28393235/26708907/c93ad8c2-471c-11e7-9ad5-8cdd998014d0.png">


 So to test this yourself, please do a search, and then click on some of the store boxes that show up in the You May Also Like section. and you'll see what I mean.  They are NOT going to real store index pages.  In fact, it looks like all the store boxes that show up in the You May Also Like section after a search, all have the same "x points/$" as the first store box in the search results...  

So the search results are fine, but the results that show up in the You May Also Like section have dummy data...

**Comment by ChrisASearles** [comment]
It's not dummy data, it's possible I missed something on the points text that was hard-coded but all the store links are going to different ID's so it's coming from somewhere on the back-end, just might be the wrong data. Will look into it.

**Comment by cgladue** [comment]
"You May Also Like" is displaying Similar Stores, which are stores within the same category as the results of the search.

**Comment by cgladue** [comment]
and they are going to real pages, but i must of pulled inactive ones there so i will add the criteria for active = true to that query which will fix the broken pages.

**Comment by robgpeak** [comment]
@cgladue also note that "...it looks like all the store boxes that show up in the You May Also Like section after a search, all have the same "x points/$" as the first store box in the search results..."

**Comment by ChrisASearles** [comment]
@cgladue what's the status on this, seems like you already fixed it, no?

**Comment by cgladue** [comment]
@ChrisASearles yes this is not dummy data and it is filtering inactive stores now.

**Comment by cgladue** [comment]
@robgpeak thumbs up ?

**Comment by robgpeak** [comment]
Yes, looks like it is working well now.
