### ISSUE TITLE
Force 10 digits for a phone number in Account/MyProfile

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#170]
If a user attempts to put in a phone number that is not a full 10 digits, and clicks update info, it responds with "Profile Has Been Updated" and reverts the phone number back to 555-555-5555. I would suppose it should return a yellow error saying this phone number field must be 10 digits. Similar to what happens when the email address is not entered in the proper format

On a side note, nice job with the (__) ___-_____ formatting when someone starts typing.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/26955626-f2831d5c-4c85-11e7-9e4a-50be0c92c347.png)

it limits the input to 10 characters now but it lets people enter non-numeric values.

**Comment by robgpeak** [comment]
I must have missed something.  Why does it not automatically format to (___) ___-_____ anymore?  And why would we allow non-numeric values?  Only Audrey Hepburn still uses KL5-6312 as a phone number any more...

**Comment by cgladue** [comment]
it dosnt format witht eh ( because chris said i cant use jQuery, which is what i used to do the formatting.

and some us arent old enough to even know who audrey hepburne is rob ;)

**Comment by robgpeak** [comment]
Well with whatever it is that you're using, you can't force it to only allow numbers?  Seem archaic.

And I call bullshit on anyone not knowing who Audrey Hepburn is...  At least not anyone reading this thread... lol

**Comment by cgladue** [comment]
haha... im sure chris and derek could, i have never used Angular (what they are using instead of jQuery) so its out of my hands ... 

i know who she is but thats about it, i dont know what they reference was to, and i dont even really know what shes famous for so, yea...

**Comment by robgpeak** [comment]
The reference was just supposed to mean, you know how in old movies that would always quote a phone number as KL5...  The Honeymooners too.  Unless you're too young for that :)

**Comment by cgladue** [comment]
lol my life pretty much starts with i love lucy, get smart, and dick van dike.

**Comment by Dwells7583** [comment]
The phone will accept only numbers, sorry Audrey. The formatting will be done also, but I pushed up the fix to the numbers only for now.

**Comment by robgpeak** [comment]
LOL

**Comment by robgpeak** [comment]
I just did a cache clear, and was able to enter letters into the phone field...

<img width="624" alt="screen shot 2017-06-09 at 8 40 25 am" src="https://user-images.githubusercontent.com/28393235/26975826-6cc2c00e-4cef-11e7-9751-d4b3dfb4aa08.png">

**Comment by Dwells7583** [comment]
It hasn't been published yet.

**Comment by robgpeak** [comment]
Oh, OK.  Off to the gym then.  back in a bit.

**Comment by cgladue** [comment]
enjoy the gun show...

**Comment by ChrisASearles** [comment]
This has been "materialized" and "angularized" and should be good.

**Comment by ChrisASearles** [comment]
Spoke too soon.

**Comment by ChrisASearles** [comment]
Ok, was missing ticks, should be all good.

**Comment by ChrisASearles** [comment]
Damnit ...

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
If there are less than 10 digits entered into the field, and someone clicks "Update Info", there is a green check mark saying the profile has been updated, but the phone number field still remains empty.  There should be an error message saying there must be 10 digits.

**Comment by ChrisASearles** [comment]
Committed. This field will now disable the save button and show an error message if there's something in it that's invalid, otherwise it re-enables with valid content or if it remains empty.
