### ISSUE TITLE
Adding Physical Address fields to " Account Information" section in Account/MyProfile

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#172]
I would like to add the following fields under First and Last names fields

Address
City, State (in a dropdown) Zip

As for the layout of it, I would tighten it up a bit, meaning make a little less space between the rows of fields.   Maybe 1/2 the amount of space there is now.

**Comment by Dwells7583** [comment]
@cgladue can you add these to the account controller?

**Comment by cgladue** [comment]
@Dwells7583 tonight sure, its not just the controller the DB needs the fields as well as does all of the DAL, you dont need to be blocked just use dummy data for now

**Comment by Dwells7583** [comment]
@cgladue when will this be updated?

**Comment by cgladue** [comment]
@Dwells7583 done, and added to the view as well, you can tidy it up

**Comment by cgladue** [comment]
@robgpeak i added both address1 and address2 fields, do you want a place to put Apartment Suite etc info or only Street address ?

**Comment by Dwells7583** [comment]
@cgladue I only see it added to the view. Are all your files included in your latest commit?

**Comment by cgladue** [comment]
@Dwells7583 yes, it was added to the ApplicationUser Class as well as the Database and is updating correctly.

**Comment by robgpeak** [comment]
Here is what I am seeing, and it is fine.  Next issue:)
<img width="895" alt="screen shot 2017-06-07 at 4 08 39 pm" src="https://user-images.githubusercontent.com/28393235/26898976-b3d62ada-4b9b-11e7-9a85-3573187581c9.png">

**Comment by cgladue** [comment]
@robgpeak @Dwells7583 Derek will need to make the State dropdown contain all states and also if any one of the address fields are filled in then all should be mandatory, if none are filled in the optional.

**Comment by robgpeak** [comment]
Agreed.

**Comment by cgladue** [comment]
@robgpeak and you are ok with all address information being contained within only one line of text correct ?

**Comment by Dwells7583** [comment]
@cgladue I am def not getting something on my end. The only thing that was added in that commit was the updated view.

**Comment by cgladue** [comment]
dont know what to say, it shows nothing on my working folder to commit.  

see if yours looks the same
![image](https://user-images.githubusercontent.com/7914133/26900660-ef46e01e-4ba0-11e7-9949-92d8b6f5d038.png)

**Comment by cgladue** [comment]
@Dwells7583 i am re-comitting the files again see if it works now.

**Comment by Dwells7583** [comment]
Ok, I got all the files now. thanks.

**Comment by Dwells7583** [comment]
@cgladue  OK. The Phone number is not formatted like it was, a few commits ago. Did this change for some reason? It is also not displaying anymore. Also, was the script removed to force the formatted phone number on purpose?

**Comment by cgladue** [comment]
**maskedinput.js** was removed because it uses jQuery and Chris said jQuery absolutely cannot be loaded at the same time as angular, so you'll just have to do it in angular i guess.  as for the phone not displaying ill look, when i added the additional fields i may have changed the property name give me a few minutes

**Comment by Dwells7583** [comment]
OK, that is what I thought. Just confirming. thanks.

**Comment by Dwells7583** [comment]
Ok the name was changed to phonenumber from mobile. Its working now. As far as the dropdown for state and the formatting of the phone number, we will circle back to those as there are more pressing items to be addressed first.

**Comment by cgladue** [comment]
@Dwells7583 i will be adding timezone as a dropdown as well so that will need to be adjusted to look pretty on my next commit

**Comment by cgladue** [comment]
@Dwells7583 timezone is not going in for go live, it will be done later, so ignore my previous comment.

**Comment by robgpeak** [comment]
This looks OK, except for the lack of a dropdown for the state field.  Having said that, we are going to need to (for now), hide all these fields from the end user's view.

We got feedback from Dover Downs, and they are weary of their user's information being outside of their own personal database.  To that end, I am going to start a new thread to make the data that we ask for from end users to be less, and make it more like the social casinos do.  @cgladue I would like to have a verbal conversation on this with you and Frank.  I will send that request via email.
