### ISSUE TITLE
Adding Advertiser Name and "x points/$" under display ads.

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#174]
@ChrisASearles This (below) was in #153, but I've since closed that one and will start this new one.

I think we need to include a line of text under the ad that mentioned the advertiser's name, and the "x points/$" under the display ads. And in the event that there are multiple image ads on the same page, we should put in a horizontal line as a separator.

![uploads/f604ee1a-3c0c-4512-932c-5a97cba2d02a/Screen Shot 2017-05-31 at 5.47.43 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff604ee1a-3c0c-4512-932c-5a97cba2d02a%2FScreen+Shot+2017-05-31+at+5.47.43+PM.png)

**Comment by robgpeak** [comment]
@Dwells7583 I would like to see about getting the Advertiser Name and points a little closer to the ad image, and lined up with it on the same left hand border of the image.  Like I mocked up in my original.

This is what it looks like on my screen now...  Too far away, and too far left in comparison to the image.
<img width="400" alt="screen shot 2017-06-06 at 5 22 27 pm" src="https://user-images.githubusercontent.com/28393235/26852698-223f976e-4add-11e7-9f4b-40258bf6d79a.png">

**Comment by robgpeak** [comment]
Also, @Dwells7583 the horizontal line as a separator is seemingly only appearing below the ads then there are two of them, but the line is not separating, it is really only under the bottom image...  It should be a separator of the images with an equidistant buffer between the bottom of the "Advertisers name and points" and the top of the next image...  I would reduce the current buffer you have between them now by half.

Here is a screen shot of what I am seeing now.
<img width="394" alt="screen shot 2017-06-06 at 5 30 48 pm" src="https://user-images.githubusercontent.com/28393235/26853066-88b6b86e-4ade-11e7-83be-5eda6c7add37.png">

**Comment by cgladue** [comment]
@robgpeak Published
