### ISSUE TITLE
Locking in points already earned

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#177]
Once we issue points to an end user for completing a transaction, we need to LOCK that point amount for that transaction.  Meaning, as it stands currently, if I as an end user have earned 28 points for a shopping trip/purchase and subsequently the partner's "share rate" (which is the portion of the commission we receive from the advertisers that we convert to points for the end user) changes, that should ONLY be on a going forward basis.

So as an example.  Today being June 5, and on my robg account in shop.complinks.co, I had earned 28 points for a transaction back on June 1st.  But if I was to go into the partner page now https://shop.complinks.co/admindashboard/partners and change the share rate, it would augment my current 28 points to whatever the new share rate was set at, and that should NOT be the case.

Once points are earned at a specific share rate, those points should not change retroactively, only going forward.

**Comment by cgladue** [comment]
@robgpeak that isnt true.

currently it will only create the balance record for the user when the comission is recieved through the API.  CJ and LS tell us the total sale and the total comission earned (in $) the program then looks up the current partner share rate and awards that percentage to the user for the purchase.  there is no other process that goes back and updates the record once its written as of right now .. so this should already behave as you are expecting.

**Comment by cgladue** [comment]
i did change the share rate to 90% just to make sure i was correct and my point balance still says 7.5 which is what it said before i changed it when it was 50%

**Comment by cgladue** [comment]
however, i think we do need to decide how soon after a comission is recieved and points are awarded do the points stay in a "pending" state.  Meaning they cannot be used untill they mature.  Like ebates does they only pay you out every quarter, so there is a peroid of time that your purchases are frozen and cannot be used.  Some of the advertisers report a "lockdate" and some do not, i guess you should think of a default # of days to lock the comission if none is reported just in case theres a return or fradulent activity etc, after that # of days then the balance transaction would be changed from pending to active and the points would be available for use.

**Comment by robgpeak** [comment]
One issue at a time:)  I will address the "pending points" state in another issue thread. 

As for the points locking issue, as you changed "shop" to 90%, my points issued for the CVS transaction on June 1st, which was 28, is now 50.4.  This is the only transaction in my account.

They pay us 4%, and we paid out 2% (share rate .5).  So the commission we received from CVS was $0.56, and 90% would be the new 50.4 points.

Please try to clear your cache and log in through an incognito window, and you should see what I'm seeing.


![uploads/6d2839ad-a48e-44fe-bb9f-7f7d4fb3c825/Screen Shot 2017-06-05 at 1.18.31 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F6d2839ad-a48e-44fe-bb9f-7f7d4fb3c825%2FScreen+Shot+2017-06-05+at+1.18.31+PM.png)

**Comment by cgladue** [comment]
shit, it is happening, had to log out and back in ... ok let me fix this.

**Comment by cgladue** [comment]
@robgpeak this has been corrected  once a comission has been recorded it will not go back and update the record again.
