### ISSUE TITLE
Adjustments needed on Rewards page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#178]
@cgladue on the page https://doverdowns.complinks.co/myrewards, we need to have the copy read the following:

You currently have 23000 Rewards Everywhere points available.

1000 Rewards Everywhere Points = 40 {Partner_Name} Points

Minimum transfer is 1,000 Rewards Everywhere Points

Choose Reward

NaN {Partner_Name} Points will be credited to your account.

undefined Rewards Everywhere Points will be deducted from your balance.

---

**Note the following edits to the above copy**

Currently "NaN" is not calculating the value even if you select a reward amount.  Neither is "undefined"   Also, BEFORE a reward is selected I think it should be 0.

As for the {Partner_Name}, it seems like at the moment, they are hard coded in there and not using the actual partner name variable.

And you'll notice that the proper terminology for the points in our system are "Rewards Everywhere" Points.  Points does not really have to be capitalized, but if we are going to capitalize it in on instance, then it should always be capitalized.

Obviously the 23000 and the 40 in the example above are coming from the db, where the 40 is calculated by the Redemption Rate of the give partner, and the 1000 Rewards Everywhere Points is always 1000.

Lastly, I removed the word "Rewards" after the {Partner_Name} on purpose, because a lot of programs names already use that term in their official brand, (Total Rewards, Mlife Rewards, Foxwoods Rewards, etc.) so we would not want to be redundant.  And then for those that don't, like Capital Club@, they just call them Capital Club® Points.

That's why you'll see in https://shop.complinks.co/admindashboard/rewards I added "{0} Points" as a reward, and that will be one for Dover Downs.

**Comment by ChrisASearles** [comment]
I believe all of these are being tracked in #55. @robgpeak can you review and close this issue if that's the case?
