### ISSUE TITLE
Remove username from Register page?

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#18]
Not sure there's a need or use for a username field. Anybody have any reason why we'd have one?

**Comment by cgladue** [comment]
because username is not equal to email address.  they are two seperate things.

**Comment by robgpeak** [comment]
I agree, I don't think we need to pigeon hole someone into picking a user name, especially if we are going to refer to them by their first name when they are logged in.  And then when we get to the stage where we have leaderboards for high point earners, we can list them by their first name, and a small icon of their profile image that they can upload.  (Again, phase 3 or later...)

**Comment by cgladue** [comment]
using email address as username is a bad practice, it makes the site less secure.

**Comment by robgpeak** [comment]
If we are really worried about security, we will implement 2 factor authorization, but for this particular application and its intended use, email and pw are fine.

Look at it this way, if I was looking to hack someone's account in Foxwoods play for fun casino, and I had my own account and was able to see all the user names of other players on a leaderboard, I have 50% of the info I need to hack into their account.  At least from that perspective the email is hidden from those types of nefarious trolls.

**Comment by cgladue** [comment]
you cannot use email as the username rob, as your design the user is allowed to have multiple accounts for multiple partnership programs... remember ?

**Comment by cgladue** [comment]
and you SHOULD be worried about security no matter what.. more strict password requirements are not as difficult for the user to use as is 2FA

**Comment by ChrisASearles** [comment]
@cgladue Here's the multi-tenant Identity change I mentioned on the phone: https://www.scottbrady91.com/ASPNET-Identity/Quick-and-Easy-ASPNET-Identity-Multitenancy

**Comment by robgpeak** [comment]
I was not sure if this should go here or on #53, but here is is anyway.  Please follow the notes on https://app.moqups.com/robg/QSDVx2F07W/edit/page/a93e4a7ba as it clearly articulates my reasoning for just capturing email and password on Sign Up. (no first and last name).  It may spur other discussions, but we should have them in moqups or verbally.

**Comment by ChrisASearles** [comment]
Hey @robgpeak, this issue was specific to the username issue, please submit this as a new issue and we'll get it scheduled in.

**Comment by cgladue** [comment]
So when you go to send them an email or a SMS or something down the road, what do you use for the salutation, "Hey you" ?

**Comment by robgpeak** [comment]
At the outset, before someone enters their name, we would use the prefix of their email address.

**Comment by cgladue** [comment]
pretty impersonal if you ask me, but you got it,

**Comment by ChrisASearles** [comment]
I'm going to add these items as a new issue.
