### ISSUE TITLE
Assigning an account number to every user account, and making it visible to the end user.

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#181]
I know we spoke about it, but there was nothing created in Github to discuss it.

I would like to have unique account numbers for end users.  They will also be visible to the end user in their "Account Information" section, but of course not editable.

https://app.moqups.com/robg/QSDVx2F07W/edit/page/af53607d3

**Comment by cgladue** [comment]
All set:

![image](https://cloud.githubusercontent.com/assets/7914133/26808518/52bdfb40-4a2b-11e7-9687-36d8e716e7ad.png)

**Comment by robgpeak** [comment]
Cool
