### ISSUE TITLE
Time zone issues

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#184]
I looks like the time zone is off for the recording of registration times.  Pete Bradley from dover downs signed up for an account today, but it is not showing EST

As you can see the current time is 12:32PM and Pete's registration record shows 1:25PM

![uploads/a4167b59-ef4a-4b95-9f11-9c1361adcb1e/Screen Shot 2017-06-06 at 12.32.47 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa4167b59-ef4a-4b95-9f11-9c1361adcb1e%2FScreen+Shot+2017-06-06+at+12.32.47+PM.png)

I am not sure where else this might be happening on the server, but again we need to make sure we are displaying and recording transactions on the same time zone.

**Comment by ChrisASearles** [comment]
All times should be stored in the DB as UTC and converted on the front-end for the current user. Preferred time zone needs to be added to the my account/profile page (I forget which was which) and should be defaulted to EST.

All DateTime.Now references throughout the site should be changed to DateTime.UtcNow to ensure we're storing UTC times regardless of the server's timezone.

All time objects should be converted in the business layer to the correct time zone for the user.

**Comment by cgladue** [comment]
Not going to make it in the initial release, site will record all times in EST for now until there is more time later.

**Comment by robgpeak** [comment]
@cgladue but it is not currently recording in EST.  I just marked a Redemption request as completed, and you can see it is not in EST.

It was 1:45 EST when I did it, and it is showing 5:45pm  Maybe that's GMT?

<img width="777" alt="screen shot 2017-06-08 at 1 49 32 pm" src="https://user-images.githubusercontent.com/28393235/26942785-57f73806-4c51-11e7-9bdf-1b2d3be59820.png">

**Comment by cgladue** [comment]
Its UTC time, i had set both servers to UTC in preparation to add timezone offsets, but the process if going to take quite some time to go through all the logic and do the conversions (including DST adjustment).  So better off just going with EST for now and switch when there is more time.  i have just adjusted the DB server and web server back to EST, try your test again.

**Comment by ChrisASearles** [comment]
This is a pretty important issue. Changing the server's time zone and relying on that time stamp means we also now have some records in the database with UTC time stamps and others with EST. There are limited places on the front-end where we're displaying any times and they're pretty much all limited to the admin areas. A quick find and replace on DateTime.Now with DateTime.UtcNow should take care of the time stamps we're storing.

Making this switch after the site launches is definitely more expensive than getting it right now.

I think there's a significant argument to make that this should be completed prior to releasing anything.

@robgpeak  your call.

**Comment by cgladue** [comment]
All the data in the DB is going to be purged before go live so thats no
concern.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
No, still not showing EST.  Cleared cache, and in fact, I logged into my robg account from a private firefox window, which I've never done before, and just marked the second one as complete, and it is still showing 6:21 instead of 2:21...

I just now saw Chris' response, and I agree that this should be fixed now to reflect EST, but what happens if we sign up a casino partner in PST.  What would we be able to do then?  

I think it would be great if it always appeared in the user's local time zone.  

<img width="569" alt="screen shot 2017-06-08 at 2 21 36 pm" src="https://user-images.githubusercontent.com/28393235/26944258-24c2179e-4c56-11e7-913b-b200ad91f027.png">

**Comment by cgladue** [comment]
Is there a timezone setting in ebates ? if there is i dont see it

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/26944952-3d504914-4c58-11e7-9154-c354f04381f4.png)

can you try again rob i just did an iisreset and restart of mysql and the proper date shows up for me when i complete a redemption and also when i start a trip.

![image](https://user-images.githubusercontent.com/7914133/26945013-6af7b0a0-4c58-11e7-9878-5aa6959b0eb9.png)

**Comment by robgpeak** [comment]
For the shopping trips, it is showing the correct time in EST.

Now when I try to mark a redemption request as completed, I get an error message.  Again this is AFTER a cache clear and new log in to me robg account

<img width="649" alt="screen shot 2017-06-08 at 3 11 27 pm" src="https://user-images.githubusercontent.com/28393235/26946342-ea2593b6-4c5c-11e7-995a-2691009626c5.png">

**Comment by robgpeak** [comment]
ebates shows shopping trips in PST...
<img width="846" alt="screen shot 2017-06-08 at 3 04 05 pm" src="https://user-images.githubusercontent.com/28393235/26946411-257a9ace-4c5d-11e7-9bf0-b0f3e963093e.png">

**Comment by cgladue** [comment]
try it from the partner dashboard rob, i see on the admin side it did give an error, ill fix that.

https://shop.complinks.co/partnerdashboard/redemptions

**Comment by robgpeak** [comment]
It's working as expected now
