### ISSUE TITLE
Inconsistency in ad model objects

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#185]
Ads are being presented using the FeaturedLink class on the category detail page and the Link class on the store detail page. The category page is currently functional, the code for ads on the store page is commented out. If you decide to use the Link class, the MedSqAd display template needs to be updated to use that as the model object instead of the FeaturedLink class. Please also uncomment the code that's loading the ads on the store detail page once this is fixed.

**Comment by cgladue** [comment]
@ChrisASearles @robgpeak this isnt an inconsistency, one is featured ads and one is just plain ads... the featured ad is on the category page, and is only Ads that have specifically marked as featured.  On the store page the ads are all ads for that advertiser.

**Comment by cgladue** [comment]
closing as a non-issue.

**Comment by ChrisASearles** [comment]
@cgladue as far as the front-end is concerned, there's no distinction, an ad is an ad, we need the same model object for ads.

**Comment by cgladue** [comment]
you may have to just deal with it and create a second partial to display it, but ill look into  why i split it out.

**Comment by cgladue** [comment]
Removed all references to FeaturedLink.
