### ISSUE TITLE
Issue with Deals and Promotions not showing up

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#188]
@cgladue Just went to the site, and no deals and promotions are showing up on any of the store index pages, only a bunch of numbers

https://shop.complinks.co/stores/index/5309
https://shop.complinks.co/stores/index/6693

**Comment by cgladue** [comment]
@Dwells7583 @ChrisASearles i just comitted the latest changes and now rob see this, any idea ?

**Comment by ChrisASearles** [comment]
@cgladue no, I just pulled latest and it runs fine on my machine. It looks like a string of sequential numbers so I'm assuming they're all the deal IDs, but no idea why it's showing up like that in production based on what's committed to source.

**Comment by cgladue** [comment]
Problem was a new partial view "DealList" that was not included in the project so it didnt publish, i have included it and republished.
