### ISSUE TITLE
Type-o on MyRewards page when a reward is successfully processed

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#194]
@cgladue In the green check box notification at the top of the page...  It reads "Successfully Redeemped Points" instead of Redeemed.

![uploads/4f235703-3e5b-4001-b05c-77df934d96c3/Screen Shot 2017-06-08 at 4.58.39 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F4f235703-3e5b-4001-b05c-77df934d96c3%2FScreen+Shot+2017-06-08+at+4.58.39+PM.png)

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
Actually, this might be another issue all together, but even though I have enough points to make a transfer, it does not work... So I can't verify the type-o is fixed

<img width="1027" alt="screen shot 2017-07-08 at 11 53 50 am" src="https://user-images.githubusercontent.com/28393235/27986957-6c780392-63d4-11e7-9ae2-90aa550d96b5.png">
