### ISSUE TITLE
Front end on iPhone 7 looks messed up

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#196]
Here is a screenshot, and she made a screen cast from her computer of he iphone screen, and you can see side by side that the back end works fine, but the front end is whacked.  She has the latest version of iOS on her phone v.10.3.2

Here is the screencast:  https://drive.google.com/file/d/0B4WqJhdIXntNX3lHdXRSZnZTQzA/view?usp=sharing

![uploads/74c460d5-6425-4c37-95c9-64962ddf8291/morgans iphone screenshot.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F74c460d5-6425-4c37-95c9-64962ddf8291%2Fmorgans+iphone+screenshot.png)

**Comment by robgpeak** [comment]
I was just on the phone with Frank and asked him to pull up the site in his phone, and this is what he sent me.  IPhone 6.  So it is definitely not an isolated incident.

![img_2598](https://user-images.githubusercontent.com/28393235/26953612-647b666a-4c79-11e7-9eab-77f81d99d3d5.png)

**Comment by cgladue** [comment]
Same for me on iPhone 6s

**Comment by robgpeak** [comment]
Here is a site that you can test our site in multiple devices live in real time...  https://www.browserstack.com/responsive  just click Live in the top nav area.  I hope it helps.

**Comment by robgpeak** [comment]
@ChrisASearles This issue has to move up the priority list to get resolved ASAP.

**Comment by robgpeak** [comment]
@ChrisASearles I mentioned this to, and showed the site to a friend of mine who knows code, and for what it's worth he said, "...I think if they make sure they’re declaring the correct bootstrap responsive classes… and apply “clearfix” to some of the elements it should help… 

but yeah the site is throwing a few errors and a handful of warnings according to my debug console"

**Comment by ChrisASearles** [comment]
@robgpeak we're not using bootstrap, as I reported previously this is a bug in Safari's implementation of the flexbox spec so we were trying to find a solution that addressed the current problem but wouldn't cause problems of it's own when they fix their bug. I think we got it sorted out, this is a dup of #102.

**Comment by robgpeak** [comment]
I did not want to create a different issue for iPhone 6, but if you go to https://www.browserstack.com/responsive and click on "Live" at the top, you can get a free 30 day trial, and you can see what it looks like live on several devices...  And while it looks 95% better than it did, there are still some issue with how certain things are displaying, (or not).

For example, on the home page of shop.complinks.co there is no footer at the bottom of the page, it is actually hidden behind some other items below the hero image.  And this is true on internal pages as well, and all all browsers on the iphone 6.

Then if you look at the footer in the ipad air 8.3, you'll see it is whacked as well.  I was not able to scroll on the home page, but I clicked into the cigavette store, I was able to see it because there was only one promotion/deal...  Additionally, a lot of the formatting is whacked there as well.

**Comment by morganpeak** [comment]
I have an iPhone 7 and when I'm logged in to shop.complinks.co on Safari the user dashboard, account management, rewards, shopping trips, and redemptions pages are all jumbled up. Here is a screen shot of the Manage Account page 
![uploads/c2377c08-76e4-4543-95e7-e08d2944c46f/IMG_8911.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc2377c08-76e4-4543-95e7-e08d2944c46f%2FIMG_8911.jpg)

**Comment by ChrisASearles** [comment]
Commited.

**Comment by cgladue** [comment]
@robgpeak Published
