### ISSUE TITLE
All {Category_Name} Stores and Featured {Category_Name} Deals sections not displaying properly on my phone

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#199]
They are not stretching across the screen.

![uploads/51cdb7cb-acda-4af1-a224-d94c31b28ad1/Screenshot (June 8, 2017 7-50 PM).png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F51cdb7cb-acda-4af1-a224-d94c31b28ad1%2FScreenshot+%28June+8%2C+2017+7-50+PM%29.png)

**Comment by robgpeak** [comment]
I just realized why, it is holding a spot for the "Display Ads" on the right hand side of the screen.  It used to be, that when the site was responsive to a certain size, the Display Ads would NOT show up, but now they are.  We should put it back to the way it was that if the size of the window gets too small, don't show the display ads.

**Comment by robgpeak** [comment]
For further clarification this issue is only happening on the category index page.  The size of the deals and promotions on the store index pages is NOT being reduced, because the display ads are disappearing, which they should on the small screen.

**Comment by Dwells7583** [comment]
Issue resolved

**Comment by cgladue** [comment]
@robgpeak Published
