### ISSUE TITLE
Login dialog and page don't work

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#20]
I created a new account, logged out, can't log back in.

**Comment by cgladue** [comment]
works fine when you use the /account/login page .. perhaps you were using your login modal.

**Comment by ChrisASearles** [comment]
Hey @cgladue, both the page (/account/login) and the modal are not allowing me to login at the moment. I get an invalid login attempt on the page.

**Comment by cgladue** [comment]
i just logged in as cgladue perfectly fine from /account/login  the modal has never worked

**Comment by ChrisASearles** [comment]
Figured out what it is! I removed the bug tag b/c it's not a bug, but definitely something that will cause some customer service issues. Chrome auto-filled the username with my email after registering, overwriting the placeholder text that indicates it's a username, not email field.

@Dwells7583 This should resolve itself once we migrate this to a material form, I'm going to tie this to #14

**Comment by ChrisASearles** [comment]
@Dwells7583 I had to pull this out of the template because of the antiforgery token. Doing so broke the display a bit, need you to get back in and get it back to where it was. I don't like the orange bg on the create account section here, I think that needs to change. The visited link color needs to be overridden too.
