### ISSUE TITLE
Adding pagination to Deal and Promotions on Store Index pages

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#200]
In the Deals and Promotions section of a stores index (details) page there should be NO pagination IF there are less than 20 records in the Deals and Promotions section.

If there are MORE than 20 records, we SHOULD use the pagination feature just as it is being used in the All {Category_Name} Stores section of a category index page.

**Comment by ChrisASearles** [comment]
Committed

**Comment by cgladue** [comment]
@robgpeak published
