### ISSUE TITLE
Only a white screen if you click on shop now button when not logged in

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#201]
I went to doverdowns.complinks.co on my phone and click on several show now buttons, and it launches in a new tab, and it attempts to start a shopping trip, but it just remains a white screen.  After trying 6 or 7 buttons, I then realized I am not logged in.  There we no indication or prompt to log in.

But I recall setting up a different issue a bit ago about keeping someone logged in forever, until they actually manually log themselves out.  I think that is definitely the way to go with our app. (That's the way ebates does it too).  It just makes better sense.

As for someone who is not logged in though, we do need to display some sort of notification to login in order to start a shopping trip.

Here is an example of the URL in a new tab after clicking a shop now button and not being logged in...  It just stays white.

https://doverdowns.complinks.co/Account/Login?ReturnUrl=%2Ftrip%2Fstart%3Faid%3D6712%26lid%3D0%26url%3Dhttps%253a%252f%252fclick.linksynergy.com%252ffs-bin%252fclick%253fid%253djLQ8qrFPMSA%2526offerid%253d492045.16805%2526type%253d3

**Comment by cgladue** [comment]
This seems to have broken recently, used to work fine.  The /account/Login views were converted to angular and partial views, so assigning to Chris and Derek to resolve.

**Comment by ChrisASearles** [comment]
Fixed the error with the blank page.

@cgladue on an unrelated note, while looking to make sure the bounce was happening properly I noticed there's no Authorize attribute on the TripsController (TripController is good), not sure if you're using that anywhere but if so it looks like it should probably only be accessible to an authorized user.

**Comment by cgladue** [comment]
@robgpeak published
