### ISSUE TITLE
Can't drag store image from excluded featured section to included featured section if there are no stores already in the included featured list

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#203]
@cgladue the particular category is https://shop.complinks.co/admindashboard/advertisers/setAdvertiserDisplayOrder/152 but there may be others...

**Comment by cgladue** [comment]
need to set minimum height on this DIV

**Comment by cgladue** [comment]
check it now, i believe the div has a minimum size now and should let you drag and drop if nothing is in it.

**Comment by robgpeak** [comment]
I am out at the moment, and it does not work on my phone.

**Comment by robgpeak** [comment]
Works now.
