### ISSUE TITLE
Changing the the word Redeem to Transfer

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#205]
We need to change the terminology of Redeem to Transfer as it relates to points.  It is confusing the way it is written and understood from a casino rewards member standpoint.  They will be "transferring" from Rewards Everywhere to the casino's rewards program, and then "redeem" at the casino.

We are going to take a page from American Express on their Member Rewards system, and when someone wants to move them to a different loyalty program (i.e. Airline Miles), the customer "Transfers" the points, and then "Redeems" the points that have been transferred to the other loyalty program.

https://rewards.americanexpress.com/myca/loyalty/us/catalog/view/ptlanding/?tier=MR&viewfullsite=y

![uploads/228ddf70-6822-42c4-b806-afffe1969bc5/Screen Shot 2017-06-09 at 2.51.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F228ddf70-6822-42c4-b806-afffe1969bc5%2FScreen+Shot+2017-06-09+at+2.51.20+PM.png)

I will try to spot all the locations of the word Redeem and replace them with the proper phrasing as it relates to "Transferring" instead.  I don't think it is just a global search and replace.  Thankfully, it is not in too many places.

I am NOT going to make a new issue for every time it needs to be changed, I think that is excessive.  I will just make one more comment in this thread with a number list that whoever can make the changes, makes them, and thenI can review, and we can mark it as done.  

Stand by for the list...

**Comment by cgladue** [comment]
Only issue would be the redemption on the casino side will happen automatically which based on Amex wording isn't the case for them


I for one don't see the wording as confusing.  And having different terminology for different rewards might be complicated.  But who knows that's me.

**Comment by robgpeak** [comment]
Redemptions never happen automatically on the casino side, ever.  In any casino. Any time someone earns points in a casino rewards program for playing in the casino, those points would just sit in a users casino rewards balance until she does something to redeem them.  i.e. use them towards a hotel room, or food and beverage credit, etc.

So when we transfer points from Rewards Everywhere to the Casino's rewards program, they will be sitting on their casino rewards account balance until she decides to do something with them.

Just like my Delta miles.  If I transfer points from AmEx to Delta, they will sit there in my Delta Miles balance account until I redeem them for a flight or upgrade.

Please use this image as guidance to make the necessary changes to the words on the page https://shop.complinks.co/myrewards

<img width="966" alt="screen shot 2017-06-09 at 4 12 40 pm" src="https://user-images.githubusercontent.com/28393235/26992883-97ea6414-4d2e-11e7-9a3c-c0e447d81e7b.png">

**Comment by cgladue** [comment]
true, its semantics and depends on the perspective, but i get what your saying tho

**Comment by cgladue** [comment]
@robgpeak published
