### ISSUE TITLE
Change to term Redemptions to Points History 

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#206]
We need to change the word Redemptions to Points History on the /myredemptions page and corresponding menu items in both the drop down menu when someone is logged in (top right of the screen), and also the menu that appears on the left when someone is in their "my account" section.

Changes to the menus and icon on the menus: (only one of the menus is in this image below, but it needs to be in both menus)

![uploads/262c3694-fb11-498a-a99b-f4c290dc9076/Screen Shot 2017-06-09 at 4.34.40 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F262c3694-fb11-498a-a99b-f4c290dc9076%2FScreen+Shot+2017-06-09+at+4.34.40+PM.png)

**Comment by robgpeak** [comment]
Shit, just realized that the icon next to the "Redemptions" that will be changed to "Points Transferred" needs to be changed as well.  Please change it to https://material.io/icons/#ic_done_all  (two check marks)

**Comment by cgladue** [comment]
@robgpeak published
