### ISSUE TITLE
Adjustment to the /account/dashboard page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#207]
Slight verbiage change and icon swap:  Actually, maybe it should read "Most Recent Point Transfers".  Singular on "Point" instead of Points Transfers.  Yeah, let's do that.

![uploads/ca1b8ba6-3a23-4ab8-b42d-bb9945488052/Screen Shot 2017-06-09 at 4.47.27 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fca1b8ba6-3a23-4ab8-b42d-bb9945488052%2FScreen+Shot+2017-06-09+at+4.47.27+PM.png)

**Comment by cgladue** [comment]
@robgpeak published
