### ISSUE TITLE
All the "Featured Stores" as a category in the Order List moved to the "Exclude" side seemingly on their own, except 2 of them

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#208]
@cgladue before I go in and fix it, I wanted to see if you might know why this would have happened?  Look at the home page, and then https://shop.complinks.co/admindashboard/advertisers/setAdvertiserDisplayOrder/153

It seems to be the only category this happened with.

**Comment by cgladue** [comment]
im  not sure what im looking for, it looks ok ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
There are only two in the "Included" section, but there were 18 or so when Morgan finished on Friday.  I am not sure what happened...

<img width="1110" alt="screen shot 2017-06-11 at 11 49 49 am" src="https://user-images.githubusercontent.com/28393235/27012362-46dc4f46-4e9c-11e7-91c5-2fce8659bf41.png">

**Comment by cgladue** [comment]
oh, remember you said if the display order is 0 then dont show them, its
because all the other ones are in the excluded column (that means display
order = 0)



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Yeah, but they WERE dragged into the "Included" side, and ordered in the right order, and they were showing up fine on the front end at the end of the day on Friday when her and I looked at it, and then something seems to have happened, and now only those two are showing on the Included side, and now only those two are showing on the front end.

**Comment by robgpeak** [comment]
@cgladue Moran just told me that the other potential issue was that she added new header images to all of those that were in "included" and then they subsequently move to excluded on their own after she added a new header image.  Best Buy and Autozone header images were added a few days earlier, and that is the reason they were not moved over to excluded.

So that seems to be the issue some how...

**Comment by robgpeak** [comment]
@cgladue  So it is also happening site wide. Meaning, just now, @morganpeak added a new header image for a specific store "Zales" which prior to her adding the header image to that specific store page, WAS in the "Included" (left) side of the Order List, then after she added the header image, it moved itself over to the "Excluded" (right) side.

**Comment by cgladue** [comment]
ok, i am looking at it right now, i am probbally overwriting that field with a 0 when saving .. hold off the header images for a few till i look at this more...

**Comment by cgladue** [comment]
@robgpeak @morganpeak i believe i found the bug, i was removing all categories and re-adding them each time an advertiser was saved, therefore resetting to default of 0 when saving .. now i only remove if not in the category anymore.
