### ISSUE TITLE
Featured stores next to hero

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#21]
Need to be able to set a store as featured in the admin area, then pull a maximum of 4 to load on the homepage next to the hero. Need to define an image size for this and store a separate image in the DB. Stores shouldn't load in this section without that image uploaded.

Reference here: https://app.moqups.com/robg/QSDVx2F07W/edit/page/a9762b57c

**Comment by Dwells7583** [comment]
The image size for this section would be 25px in height, auto width.

**Comment by ChrisASearles** [comment]
@Dwells7583 we need a recommended default image size including width.

**Comment by cgladue** [comment]
This isn't an issue, this already exists in the advertiser maintenance screen, add them to the Featured Category.

**Comment by ChrisASearles** [comment]
Hey @cgladue are you formatting the commissionfrom and to strings on your end or do I need to parse that text out to determine if it's a percentage or a dollar value? If you're not already doing it in the controller, can you? I would think that would be a better place for it to live rather than trying to figure the data out in the view.

**Comment by cgladue** [comment]
Right now all commission values are already formatted in the DAL except the "up to x points/$" vs "x points/$" based on the values of those two fields.   Those you need to decide which way to display it

**Comment by ChrisASearles** [comment]
@Dwells7583 still an issue here that's causing the buttons to not align right.

**Comment by Dwells7583** [comment]
Fixed alignment issue
