### ISSUE TITLE
Putting the categories in the nav, in alphabetical order

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#211]
I would like to have the categories in alphabetical order

**Comment by cgladue** [comment]
@robgpeak i took care of this, please review now.

**Comment by robgpeak** [comment]
Thanks Chad

**Comment by robgpeak** [comment]
Not to be a douche, but ONLY if it is an easy fix, can you make it alphabetically going down in column 1, and then continuing in columns 2 and 3 that way.  This would be more in line with how it responds from within the hamburger menu.

**Comment by cgladue** [comment]
you are such a douche rob...

just kidding 😛 

that would have to chris's realm since that would require the layout of the list to change, but should be trivial i would assume.

**Comment by robgpeak** [comment]
LMFAO...  Don't I know it :)

OK.  Not super pressing, but again, for continuity sake, I think that's the way it should be.

**Comment by cgladue** [comment]
i agree, it makes more sense top to bottom left to right then left to right top to bottom anyways.

**Comment by ChrisASearles** [comment]
This never got reassigned to me but it was included in the update I pushed up today to fix the nav in Safari
