### ISSUE TITLE
An issue with points awarded from Yoshop (LS advertiser)

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#212]
@cgladue First the "Great News". I placed a couple of real orders...  One from Vitamin Shoppe at 4:46 PM yesterday (Shopping trip 683), and the commission came through about 30 minutes after the order was placed, and the commission and points were exactly as expected!!!  Awesome.

There was a slight issue with another order I placed with YoShop.

First, I actually placed the order from the Shopping Trip 686 but it is showing that I placed it from 687.  I DID actually start a second trip just to test a different link, but I closed the tab that had the newer shopping trip in it, and completed the transaction in the original trip window.  Not that big if a deal, but I figured I would mention it.  I just happen to see now in looking at the vitamin shoppe transaction that cj captures the SID, which I am assuming is the shopping ID parameter that we send them in the URL string when we start a shopping trip, and maybe LS does not do this.  I think this is always a good idea as it gives us more data points to look up specific transactions...

In fact, here is the actual link from the trip that I started, and DID make the purchase from.  Not sure if it helps, but I figured I would send it to you.  https://www.yoshop.com/promotion/mid-year-sale-314.html?utm_source=linkshare&utm_medium=linkshare&utm_campaign=linkshare&ranMID=42476&ranEAID=jLQ8qrFPMSA&ranSiteID=jLQ8qrFPMSA-0dS9LKucdOrluncmFsfoNw

The other issue of greater importance is, our system seems to have issued a double credit in points to my end user account.  But if you look in the https://shop.complinks.co/admindashboard/transactions/comission report, you can see one of them was actually a debit because I used a 10% promotion coupon code.  So the Commission Report on our side has the proper calculation, but the Shopping Trips data on my user account front end is showing two full credits for points, instead of one for a credit of 87 points and another one for the debit of 9 points.

 
![uploads/ee93cb83-a066-4de8-9e59-9de600dafbfb/Screen Shot 2017-06-13 at 8.34.58 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fee93cb83-a066-4de8-9e59-9de600dafbfb%2FScreen+Shot+2017-06-13+at+8.34.58+AM.png)

So the debiting of points from someone's account in this particular type of transaction should be categorized as a "Discount", (I am not sure how it is reported to you in the API), and I can also see something like this happening in the future with a return of an item, and in that case I would describe it as a "Product Return" and we would debit the appropriate amount of points.

Here is a screenshot of the ls report located at https://cli.linksynergy.com/cli/publisher/reports/reporting.php#report/559d7cb6184a41b532000182

![uploads/b50a7254-4230-4549-92e3-a3986558ff43/Screen Shot 2017-06-13 at 8.40.41 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb50a7254-4230-4549-92e3-a3986558ff43%2FScreen+Shot+2017-06-13+at+8.40.41+AM.png)

**Comment by cgladue** [comment]
I will def. look at the double credit.  I always knew I'd have to handle returns when I saw them the first time. Because there's no testing that Jc and Las provide and I'm not sure how the data will come across.  So I'll look at the data in the API and see if this can solve that issue.

**Comment by robgpeak** [comment]
Ok.  And I will make some additional purchases and return them so we can see what they look like in each network.

**Comment by robgpeak** [comment]
As a follow up, and possible remedy to the "Discount" credit issue from YoShop (which I really don't like the look of it), would be, IF the "Order ID" reported from the network is exactly the same, and processed at the same exact time, we do the calculation on our end and only show the one "Credit" of points to the end user.

**Comment by robgpeak** [comment]
@cgladue as even more follow up, The purchase I made on 6/1/17 from cvs pharmacy also had a 30% savings coupon, but cj or cvs itself combined the two transactions into one, and just reported the single total price that I paid.  Makes way more sense that way, but obviously either LS and/or YoShop does not do it that way.

**Comment by robgpeak** [comment]
Damn, here is another little wrinkle to consider...  Have a look at the first image, and you can see that the same shopping trip to Best Buy shows up twice.  It only shows up twice AFTER the report from ls (the second screenshot) showed the transaction, but notice it is NOT showing the commission yet, because the items I ordered are not going to ship until the 20th of June.

When I placed the order, their site told me the items WERE available at the store (I was going to go pick them up), but then I received an email after I submitted the order, and was told the items were not available.

As for the "Discount" line in that report, I am not sure what happened there because there was no discount coupon used...

It does not seem to be an all time thing from LS, because the other transaction from Hotel Power and others does not include a second "Discount" record.  Maybe it's something new in June going forward...  I will make a couple of other transactions and we'll see, and if need be I will ask their support.


![uploads/366c19f3-36c6-40e0-b9e9-6bdb3189b591/Screen Shot 2017-06-13 at 8.30.36 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F366c19f3-36c6-40e0-b9e9-6bdb3189b591%2FScreen+Shot+2017-06-13+at+8.30.36+PM.png)

Having a look at the second screenshot, you can see the report from LS on this particular transaction...


![uploads/790c6dd3-98c2-4bcf-b601-64a951b9c00f/Screen Shot 2017-06-13 at 8.41.50 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F790c6dd3-98c2-4bcf-b601-64a951b9c00f%2FScreen+Shot+2017-06-13+at+8.41.50+PM.png)

**Comment by cgladue** [comment]
ok, as for the trips it will always take the last trip that you started to use in the cookie to the advertiser, so if you click twice the last one should be the trip that gets reported to the advertiser in either the SID for CJ or th u1 parameter in LS... eventually the trips that never produce any commission will be "deleted" so they dissapear from the trip view.

as for the discounts and stuff, i will have to see the data thrugh the API and see if theres a pattern to it and deal with it that way, i am guessing i will be able to identify a discount vs a sale and deal with it accordingly...  i am hoping i dont have to add two records for the balance and the sale it would be confusing and better to just have 1 for the sale tha is combined.

**Comment by cgladue** [comment]
i basically changed it to sum the comission and sale amount by orderId, so since discount and sale transaction have the same orderid it basically subtracted discount from sale and just records the sale.
