### ISSUE TITLE
Not allowing duplicate emails with the same partner at the same subdomain, but allowing it at other subdomains

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#214]
I think we spoke about this in the past, and the idea is that an email address should be unique to each partner.  Meaning, chadgladue@gmail.com is signed up as a member of CompLinks through the subdomain "shop", and would NOT be able to register for another account using that email address at shop, but COULD at doverdowns, or any other subdomain.

If chadgladue@gmail.com attempts to register another account at a subdomain in which he is already registered, I suppose the best thing to do would be to ask him to login using that existing account information, and if he forgot his password, prompt him to reset it to gain access to the existing account.

**Comment by cgladue** [comment]
@robgpeak i believe this is already resolved

**Comment by robgpeak** [comment]
We need to change the verbiage that appears at the top of the https://shop.complinks.co/Account/Register page if our system detects someone is trying to register with an email address that is already in our db for that subdomain.

Currently it shows this:

<img width="759" alt="screen shot 2017-06-22 at 8 07 41 am" src="https://user-images.githubusercontent.com/28393235/27433322-36026988-5722-11e7-9521-343fbc2c0826.png">

A couple of issues:

1. It should show the "email" address instead of the "Name", Name in that format does not mean anything to the end user.

2. It should only appear once in red, not the second time in black below it.

3. The exact verbiage should read, "The email address {email_address} is already registered, please use the 'Sign In' page to access your account."

4. I am hoping that without this line appearing twice, it will move the "Sign In" button up and appear within the overall white area of the page to make it look better than it does now.

5. Looking at it on mobile, it looks like the "Sign In" button at the bottom shows up fine and in the right spot (not seen in the image below), but the top of the page you cannot see the text, "Sign Up", and part of the red text is jammed right up to the top of the page, and does not look good.  I am hoping with the removal of the second line it will look better on mobile as well, but I tend to think there may be something else at play here...

![sign in mobile](https://user-images.githubusercontent.com/28393235/27434036-2bd5b44e-5725-11e7-9a1f-4c98dfffe503.png)

**Comment by ChrisASearles** [comment]
@cgladue if you want to handle the error message verbiage and then reassign to myself or @Dwells7583 when you're done we'll take care of the front-end stuff (unless you want to just bang that out while you're working on it, your call).

**Comment by cgladue** [comment]
https://forums.asp.net/t/2026833.aspx?How+can+customize+Asp+net+Identity+2+username+already+taken+validation+message+

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
OK for the verbiage, please change dont to don't.

But it still shows up twice on the page, (meaning the whole line "This email already exists, if you dont remember your password please try the forgot password link to reset it."), and we only want to it appear once.

**Comment by robgpeak** [comment]
Actually, just looking at what I originally wrote, here is a better line of verbiage instead of "This email already exists, if you dont remember your password please try the forgot password link to reset it."  Replace it with "This email address is already registered, please use the 'Sign In' page to access your account, or reset your password if you forgot it."

**Comment by cgladue** [comment]
@robgpeak this should be fixed now, take a look
