### ISSUE TITLE
Slight change to the "Phone Number" section on My Account page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#217]
@cgladue I know you are probably still working on this, and maybe I am jumping the gun, but I would like to remove the words "Phone Number" from the actual field entry area, and have it appear above the field entry area, so it is consistent with all the other fields in that section of the site.  Please DO leave the brackets and formatting feature in the field, as I think it looks good in there.

![uploads/93ea7b1f-6208-4978-9290-9af86dcd580e/Screen Shot 2017-06-16 at 2.07.21 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F93ea7b1f-6208-4978-9290-9af86dcd580e%2FScreen+Shot+2017-06-16+at+2.07.21+PM.png)

**Comment by ChrisASearles** [comment]
This is a bug I fixed a while ago, not sure how it made it's way back here ...

**Comment by ChrisASearles** [comment]
Looks like this broke when that email opt-in checkbox was added. It broke a couple other things in the layout too. I pulled that out into it's own "Communication Preferences" section and changed it from a checkbox to a switch.

That functionality seems to still not be quite right though ... but this issue has been fixed.

**Comment by cgladue** [comment]
what functionality is not right ?

**Comment by ChrisASearles** [comment]
Looks like it's the same thing @robgpeak reported in #81 where it doesn't actually set the value, it asks me to check my email and confirm and comes back as not subscribed.

**Comment by cgladue** [comment]
yea thats how it works, when they opt in they have to confirm the opt in via the email they recieve, which then does a post back to our site to update the opt in value to true..

**Comment by ChrisASearles** [comment]
Submitting a comment over on that issue to keep this one clean.

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
I see the brackets are in there but the functionality is still not working correctly.  I just entered 6 digits into the field, clicked "Update Info" and saw the green check mark that the profile has been updated, but there was no phone number, and no error message saying a needed to enter 10 digits.

**Comment by ChrisASearles** [comment]
Committed.
