### ISSUE TITLE
Update Hero image callout text for both authenticated and unauthenticated users

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#218]
I would like to add the lines of text below them hero image callout text areas:

Unauthenticated: "When You Purchase Everyday Items From Our Merchant Partners"
ALSO, please make the "a" in the main copy a capital "A" ... "Earn Rewards Everywhere 365 Days A Year"

![uploads/7fef90f0-2833-4462-9c5a-10c88b1b9a59/Screen Shot 2017-06-19 at 11.27.55 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7fef90f0-2833-4462-9c5a-10c88b1b9a59%2FScreen+Shot+2017-06-19+at+11.27.55+AM.png)

Authenticated: "By Shopping For Everyday Items, 365 Days A Year"

![uploads/1ba4a27e-98a9-4f7b-8892-b62d32bc4d02/Screen Shot 2017-06-19 at 11.21.01 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1ba4a27e-98a9-4f7b-8892-b62d32bc4d02%2FScreen+Shot+2017-06-19+at+11.21.01+AM.png)

**Comment by cgladue** [comment]
@robgpeak published
