### ISSUE TITLE
Load featured stores on homepage

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#22]
Need to allow stores to be featured in the back-end and then load them on the homepage in the section that's already been designated.

The cards that load should be clickable to the advertiser detail page with a "Shop Now" button of the theme's accent color that links to the advertiser's website using the advertiser's default link.

**Comment by cgladue** [comment]
Added ViewModel with the Featured property.  Any advertiser put into the featured category will be returned in this list.  i have added a sample to the Home Index View.

**Comment by Dwells7583** [comment]
@cgladue also need the feature stores for the header section as well.

**Comment by ChrisASearles** [comment]
Data is loading, I changed to div's from the tilegrid to fix the overflow issue but it's causing another problem where heights aren't flexing properly. For some reason the buttons blew out larger when I made my changes too. @Dwells7583 can you take a shot at this?

**Comment by Dwells7583** [comment]
Buttons are fixed.
