### ISSUE TITLE
No links in multiple advertisers

### ISSUE THREAD

**Issue by morganpeak** [ChrisASearles/CompLinks#220]
@cgladue I have a list of advertisers that have no links appearing in the back end. Some were added a while ago and some where just added the other day. Here they are:

Kendra Scott- no links
Roku-no links
South Beach Swimsuits- no links
my mold detective- no links
joseph joseph- no links
Globehunters- no links
swiss diamond- no links
downpour.com- no links
izidress- no links
overstock sheet club- no links
kicks USA (CJ not LS)- no links
da vinci vaporizer- no links
nexgen biolabs-no links
walgreens- no links
pep boys- no links

**Comment by morganpeak** [comment]
Two more new advertisers have this same problem:
Oasap - CJ
Healthy Pets - Linkshare

**Comment by cgladue** [comment]
not sure whyt his started all of a sudden, but im sure its an easy fix

2017-06-26 00:12:47.4108 INFO Processing Links...
2017-06-26 00:12:47.4958 FATAL The remote server returned an error: (401)
Unauthorized.



Chad Gladue
*DevNull Technology, LLC*

**Comment by morganpeak** [comment]
Oh okay I just sent you another email about one that just happened about an
hour ago where other links were pulled from LS but not the ones for a
particular store that just approved us.

Thank you,

Morgan

--

*Morgan Gallo*
*VP Operations*
*Peak Marketing*
*morgan@peakmarketing.com <morgan@peakmarketing.com>*
*Phone: 631-903-1032*
*www.PeakMarketing.com <http://www.PeakMarketing.com>*

**Comment by cgladue** [comment]
@morganpeak @robgpeak i fixed and restarted the service, for some reason the password expired, so i set it to not expire and we will try again .. some of the advertisers you listed either have no links peroid or no text links .. the others that do have links should be updated now.
