### ISSUE TITLE
Login & Password Reset Issues

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#221]
I just went to login to the site and wasn't able to. Figured the database might have just been cleaned up so I re-registered successfully, but when I went to login with that account it error'd out. Tried registering again just to make sure I didn't type my email address wrong and I'm getting the correct error message that my account already exists. I tried to use the forgot password functionality but never received an email.

**Comment by cgladue** [comment]
i am not having any issues logging in... not sure what you are having issues with ... is this on shop.complinks.co or localhost ?

**Comment by cgladue** [comment]
Also i requested a password reset and was able to do it without any issue,

**Comment by ChrisASearles** [comment]
shop.

**Comment by ChrisASearles** [comment]
Just tried again, login still isn't working and I still haven't received a password reset email, not getting filtered into my spam folder. Does the AWS email service give you access to logs to see if it's being sent and if so, can you validate the email address it's sending to?

**Comment by ChrisASearles** [comment]
Login's not working on my localhost either.

**Comment by cgladue** [comment]
there must be some strange happening with your login, let me clear you out and have to re-register again, because i just registered, requested a password reset and logged in and no issues...

**Comment by cgladue** [comment]
i see what it was, i have committed a change and published it, try to login now

**Comment by ChrisASearles** [comment]
Working now, thanks. What was the issue?

**Comment by cgladue** [comment]
i never changed the login method to parse the new username format
correctly, i only changed the register method, so if you registered
recently and had the new format username it would fail to find you
correctly.



Chad Gladue
*DevNull Technology, LLC*
