### ISSUE TITLE
Change the name of the /myredemptions page to /pointshistory

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#223]
The page https://shop.complinks.co/myredemptions should be changed to https://shop.complinks.co/pointshistory

**Comment by cgladue** [comment]
should it be /pointshistory ?  because its not really the point point history thats shown on this page, unless you want point history AND transfer history to be shown together on this page ?

**Comment by robgpeak** [comment]
at the moment, the only thing showing on the page is "Points History", so I was just saying the name of the page should kind of match what is the main contents of the page.  Additionally, yes, it should have the transaction history on this page as well.  #224 and that is why I wanted to change the name of the actual page.

**Comment by cgladue** [comment]
@robgpeak Published
