### ISSUE TITLE
Adding "Transaction History" section to Points History page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#224]
On the Points History Page, I would like to add a Transaction History section below the Points Transferred section.

The functionality would be that this section would include all the transactions that involve points added to, or taken away from the user's account, whether manually added or automatic.  In the Description section, I have "Item" purchased, and "Item" is a place holder for the actual item that was purchased (or returned), WHEN we have the functionality to import that data from those back end reports from LS and CJ.  Until then, we can leave it with Item.

![uploads/9670d07b-b32c-4728-b1a7-ba308027a63c/Screen Shot 2017-06-26 at 12.29.54 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9670d07b-b32c-4728-b1a7-ba308027a63c%2FScreen+Shot+2017-06-26+at+12.29.54+PM.png)

**Comment by robgpeak** [comment]
Another feature should be the ability to sort by any column.

**Comment by ChrisASearles** [comment]
@cgladue Let @Dwells7583 know when the data is being pushed to the view and he can take it from there.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
We still need the new icon for the Transaction History section as I indicated in my original post to this thread in the image.

Also @cgladue a couple of questions:

1. Can we make the columns sortable?  What are they being sorted by now?

2. In the transaction on 6/14/2017 9:17:13 PM, there is no description...  Do you know what it was?

**Comment by cgladue** [comment]
@robgpeak 

#1 would be a job for Derek and Chris
#2 that comes from the API, in this case it appears they sent in a blank string as the description.
