### ISSUE TITLE
Changing the naming convention of the points

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#225]
@cgladue as we discussed on the phone the other day, I think we should change the naming convention of the points on the https://shop.complinks.co/account/dashboard page to "Lifetime Points Balance" being the overall amount of points I have ever been awarded for any reason, and "Current Points Balance" which shows my current point balance in my account regardless of how I've come to accumulate them.

In that context, I would like to have the "current" balance on the left, (first) and the "lifetime" balance on the right (second) on this page...

![uploads/32f90cd2-62a4-436c-8485-1d045ce5f214/Screen Shot 2017-06-26 at 4.54.58 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F32f90cd2-62a4-436c-8485-1d045ce5f214%2FScreen+Shot+2017-06-26+at+4.54.58+PM.png)

And based on the overall history on this account, the balances would be Lifetime 21,223 and Current would be 17223.  Meaning I have transferred 4k out...

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
cool.  One other thing, for consistency, I think we need to show the decimal points in the Current Points balance big blue box, as it shows up with the decimals in the top right of the screen...
<img width="1037" alt="screen shot 2017-07-12 at 12 32 21 pm" src="https://user-images.githubusercontent.com/28393235/28128706-9c89c188-66fe-11e7-9808-5231913b1016.png">

**Comment by cgladue** [comment]
@robgpeak Published 

![image](https://user-images.githubusercontent.com/7914133/28194276-34484d74-6811-11e7-8a09-1a3e5e4e56d4.png)
