### ISSUE TITLE
Please make a change in Partner Dashboard

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#226]
@cgladue Please change the word "Redemptions" in the left nav AND as the header of the page to "Points Transferred"

Also please change the icon in both the left nav menu from the diamond, and next to the header word (the gear), to something that fits in with the icon scheme of the back end, but more like https://material.io/icons/#ic_done_all

![uploads/9f04e57f-b157-4634-a660-0a0b3c1f6c65/Screen Shot 2017-06-27 at 4.52.27 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9f04e57f-b157-4634-a660-0a0b3c1f6c65%2FScreen+Shot+2017-06-27+at+4.52.27+PM.png)

**Comment by cgladue** [comment]
Sounds good I will make these changes.

**Comment by cgladue** [comment]
@robgpeak published
