### ISSUE TITLE
Should not be allowed to open two accounts with the same email address on the same subdomain

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#228]
Just saw this...

![uploads/3add512a-e944-4352-b9e7-3e6268ba8f0b/Screen Shot 2017-07-06 at 9.10.47 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3add512a-e944-4352-b9e7-3e6268ba8f0b%2FScreen+Shot+2017-07-06+at+9.10.47+AM.png)

**Comment by cgladue** [comment]
this is already all set, it was from testing that these are duplicate
