### ISSUE TITLE
Load featured deals on homepage

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#23]
Need the ability to feature a deal in the back end and then load those deals on the homepage under the featured stores section. The "Shop Now" button on these should use the link for that particular deal, but should also include the advertiser info and a link to the advertiser.

Design reference: https://app.moqups.com/robg/QSDVx2F07W/edit/page/a23bde215

**Comment by cgladue** [comment]
i have added "mainLinkURL" to advertiser object as well as loading all the featured deals in the viewModel.
