### ISSUE TITLE
Add "Linked Accounts" section to ../account/myprofile page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#232]
We need to have a section below the "Communication Preferences" on the myprofile page called "Linked Accounts", and it should follow the guidelines of https://app.moqups.com/robg/QSDVx2F07W/edit/page/af53607d3 for an unlinked account, and https://app.moqups.com/robg/QSDVx2F07W/edit/page/ab902c755 once an account has been successfully linked to the user's casino rewards program.

**Comment by ChrisASearles** [comment]
@robgpeak I didn't think we had any account linking set up yet and were waiting for the first partner to sign on so we could iron out that process with them. @cgladue do we have any content to show here?

@robgpeak if not, are you just looking for something dummy'd in there for your vegas trip to show to the casino?

**Comment by cgladue** [comment]
the only thing we had was a test page that would process a login to doverdowns.com and return user details to display on the screen... i was waiting for confirmation of who and how we would be validating player accounts to make anything permanent

**Comment by robgpeak** [comment]
For now the best thing to do would be to mock something up and we can fill in the functionality behind the scenes when we get our first customer. But basically it will do what the Foxwoods play for fun casino currently does to validate someone's rewards account with the casino

**Comment by ChrisASearles** [comment]
So you just want us to mock in the functionality on those mock-ups so you can drop in anything into those boxes and end up with a linked account?

**Comment by ChrisASearles** [comment]
Or do you just want every account to show as linked already?

**Comment by robgpeak** [comment]
No, just build the unlinked account section that would have the fields someone would be able to enter their casino rewards member ID, PIN and birthdate.  We don't need to show every account as linked, or even the functionality, but when we do get the functionality from a casino partner, then of course after we validate that the person is who they say they are, we show the account as linked.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by cgladue** [comment]
@robgpeak i just saw how the linked accounts page was designed and it is a bit lacking i believe.. i think this should be re-opened ..

Chris's guys seem to have removed my button to "unlink" an account and also i dont know how they are going to handle more then 1 account possibly being linked .. i think these are necessary functions for future functionality that should be done now.

**Comment by cgladue** [comment]
This is what happens if there are multiple accounts linked:  not correct behavior IMO

![image](https://user-images.githubusercontent.com/7914133/28248551-53f569a4-6a14-11e7-8e7e-24f9ceb65287.png)

**Comment by robgpeak** [comment]
Are casino customers allowed to have multiple player rewards club memberships?  I don't think so so it really doesn't make a difference because someone can only link to One account. I mean we could reput the unlink Account button back in there it doesn't really make much of a difference

**Comment by cgladue** [comment]
Not loyalty memberships but it does make a difference because in the future they may be linking credit cards, fuel rewards cards etc not just loyalty cards, need to think big picture it dosnt make sense to think short term now and have to revisit it again later

**Comment by cgladue** [comment]
Plus there is no way to Unlink an account which you said would be something you needed in case they merge accounts or the acct# changes for some reason...

**Comment by robgpeak** [comment]
Agreed, so let's put the unlikely functionality in there

**Comment by Dwells7583** [comment]
Sorry, I will add the unlink button back in there, I just went off the moqup which had the transfer points button only.

**Comment by cgladue** [comment]
@robgpeak Published
