### ISSUE TITLE
Error marking redemption as complete

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#233]
@cgladue I was in the Partner Dashboard, and I attempted to mark a redemption request as complete, and it gave me a red error message at the top of the page.  Same thing happened in the admin dashboard

**Comment by cgladue** [comment]
@robgpeak  this was due to some transactions i deleted in the DB, this is a byproduct of testing, you can try again for a fresh redemption and there should be no issues.
