### ISSUE TITLE
The action column and action buttons are way off to the right, if at all

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#234]
@cgladue  in the tables of the back end on just about every page that has an action column and buttons, is way off to the right, and we need to figure out why and fix it.  And on the ipad, they (the action column and buttons) don't even show up on chrome.

![uploads/e2f0741d-7f47-4d6d-a9a5-99532506d9ae/Screen Shot 2017-07-06 at 4.11.22 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe2f0741d-7f47-4d6d-a9a5-99532506d9ae%2FScreen+Shot+2017-07-06+at+4.11.22+PM.png)

**Comment by robgpeak** [comment]
You have both been added as admins on all the accounts registered with your email addresses.

**Comment by Dwells7583** [comment]
@robgpeak thanks.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
sweet!
