### ISSUE TITLE
Server Error in"/" Application logging in on mobile

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#235]
When I am on my phone, but I have not been active for a while (a couple of hours I guess), when I come back to the page and click the head and shoulders icon it takes me to this page https://shop.complinks.co/Account/Login?ReturnUrl=%2Fstores%2Findex%2F6712 and I get a Server Error in"/" Application

You can see it here in action, and the error message...  https://screencast.com/t/zUNcsngfJRM

**Comment by ChrisASearles** [comment]
I'm not able to reproduce this, are you still seeing this error? I'm thinking it may have been fixed with another update ...

You can force the issue by logging in, clearing your browser cookies (which clears your authentication token) and then trying that button again.

**Comment by robgpeak** [comment]
must have gotten corrected with some other fix
