### ISSUE TITLE
Adding first and last name to sign up form

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#236]
As per our conversation a few weeks ago, we want to add the capture if the first and last name of the new customers...  We were supposed to put a task in here but I don't see it.

Here is a document I mocked up for reference.

New User Sign Up 

https://docs.google.com/document/d/1NBe2k6vih0llA-KQ8CgmYSAgCKcjXVBOCxg6UGzjkCI/edit?usp=sharing

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
OK, I see the sign up page now includes the fields for first and last name, but the functionality is lacking.  I will start another separate issue.
