### ISSUE TITLE
Linking Rewards Everywhere to existing casino rewards Member ID

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#237]
I put a document together for more reference

https://docs.google.com/document/d/1OqL56glpVLRNJEMlU0SO9kLrqbWVpCNN2BQM6bGmnX4/edit?usp=sharing

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
OK.  Two things:

1. Can you make it NOT default to include the email address and password on the fields.  Just leave them blank when you get to the page.  When I got there I saw this:

<img width="821" alt="screen shot 2017-07-12 at 10 26 13 am" src="https://user-images.githubusercontent.com/28393235/28122570-92bcb29e-66ec-11e7-8612-c5a7e37e155b.png">


2. Can you make the Linked account section look the same as all the other "sections" of the page.

Meaning, I put in some BS info, and this is what I saw...  I like that it came back with something (for demo purposes), but would like it to look better.

<img width="658" alt="screen shot 2017-07-12 at 10 23 32 am" src="https://user-images.githubusercontent.com/28393235/28122514-669900b4-66ec-11e7-899a-991eab7603da.png">

**Comment by cgladue** [comment]
its your browser inserting that data in the field, the site dosnt have a default value for those fields. 

and #2 @ChrisASearles and @Dwells7583 will have to pretty up

**Comment by robgpeak** [comment]
OK.  So I will leave the issue open for now until he pretties it up.

**Comment by robgpeak** [comment]
Hey @Dwells7583 basically we want to make the linked section look pretty like the unlinked section.  In its own box and more uniformed than what it looks like in the image above in this thread.

**Comment by ChrisASearles** [comment]
I saw the auto-fill problem before I saw this issue and took care of that and published it last week so you shouldn't be seeing that problem anymore, @Dwells7583 can take care of what it looks like when it comes back as linked.

**Comment by cgladue** [comment]
@robgpeak Published
