### ISSUE TITLE
Commission transactions are missing

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#239]
@cgladue https://shop.complinks.co/admindashboard/transactions/comission is now empty, when there used to be data in there?

**Comment by cgladue** [comment]
Take a look again, it was due to more invalid test data (we will be clearing all users and data prior to actual release to keep this clean

**Comment by robgpeak** [comment]
cool.  One thing we will have to do is have the ability to break down all those fields into sub sections for the subdomains.  Meaning, we would need to see ALL as it is now, but then just Doverdowns, foxwoods, etc. separately.  Should I start a separate issue for that?

**Comment by cgladue** [comment]
yea if you dont mind it would help keep it from getting lost



Chad Gladue
*DevNull Technology, LLC*
