### ISSUE TITLE
Category Images

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#24]
Need to be able to upload a default category image for each category and display that at the top of each category page.

@Dwells7583 Please be sure to clearly define dimensions and specs for this image.

**Comment by cgladue** [comment]
i have added a headerImage field to the category model returned to the page, you can now display the url in that field.

**Comment by cgladue** [comment]
also, i have updated the category Index view to show an example of the header image, as shown here:  http://shop.complinks.co/category/index/153

**Comment by robgpeak** [comment]
@cgladue I am getting an error message when I try to save a header image to a category.  https://screencast.com/t/AWRqmMqXe8o

**Comment by cgladue** [comment]
it may be because i am monkeying around with things fixing soemthing else,
stand by

**Comment by cgladue** [comment]
problem was i had to store the AWS credentials whiel the code was running on the server, so i corrected that, please try again...

**Comment by ChrisASearles** [comment]
Pushing this back to Ready for Derek to get in and specify image specs / layout.

**Comment by ChrisASearles** [comment]
As this ticket was just related to the upload and ability to display a category image, not the layout of the page, I'm going to close, all discussion about the page layout should occur on that issue (#25).
