### ISSUE TITLE
a better interface for "forgot password"

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#240]
On the "Sign In" screen (which is a nice overlay to the site), when you click on forgot password, this page (https://shop.complinks.co/account/forgotpassword) appears full screen, and I think it would look way better if it was in the same 'overlay' style and format of the Sign In and Sign Up overlays...

The same would hold true for the https://shop.complinks.co/Account/ForgotPassword page.  It too should appear in the same overlay style and format.

**Comment by Dwells7583** [comment]
@ChrisASearles Can you take a look at this and make sure I converted everything over correctly. It does not seem to send me an email to reset password.

**Comment by ChrisASearles** [comment]
@Dwells7583 everything is functioning properly on the front-end, it's a bug on the back end.

@cgladue user is coming back as null on the FindByNameAsync method in the ForgotPassword action.

**Comment by cgladue** [comment]
ok ill take a look, probbally a leftover from when we changed the username format

**Comment by cgladue** [comment]
@robgpeak Should be fixed now.

**Comment by cgladue** [comment]
@robgpeak actually i think this should go to Chris's guys first now that its working.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
@ChrisASearles and @Dwells7583 So I guess it cannot appear in the same overlay window as the sign in screen?

**Comment by ChrisASearles** [comment]
@robgpeak Just need to track it under a separate work item. I'll open that as a new ticket and you can consider this one closed if the forgot password page is good as-is.

**Comment by robgpeak** [comment]
It's good as it is, as long as it fits in with the look and feel of the overlay.
