### ISSUE TITLE
image ads not showing up

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#243]
@cgladue @ChrisASearles The images for the ads are not showing up on the store's individual index pages.  I have two demos lined up for 3:00pm and another at 4:00pm.  Please see if you can get this sorted out ASAP.  Thanks.

**Comment by cgladue** [comment]
can you give me a store page that should show an add ?

**Comment by robgpeak** [comment]
Should have been more specific.  It is only happening (not showing up) on doverdowns...  https://doverdowns.complinks.co/stores/index/6789

**Comment by cgladue** [comment]
This is what i see when i visit the store page:

is this what its supposed to look like ?

![image](https://user-images.githubusercontent.com/7914133/28134471-0c3152c8-6711-11e7-9b33-497a3c78fc09.png)

**Comment by robgpeak** [comment]
huh.  Strange.  It is only happening (not showing up) in a private window in firefox...

**Comment by cgladue** [comment]
maybe go to developer console or debug console or whatever its called on firefox and see if you see any error messages being thrown ... ?

**Comment by robgpeak** [comment]
I don't see any error messages...  Oh well, bigger fish to fry.
