### ISSUE TITLE
Transaction History section on /pointshistory not showing the 100 points for signing up

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#246]
@cgladue I just signed up with a new account to test some email mail chimp stuff, but when I look in myaccount, I see I received the 100 points, but I don't see the transaction in the Transaction History section

**Comment by cgladue** [comment]
i think this may be a sorting issue, i have changed the sorting to descending, take a look now, it shows up for me when i tested.

**Comment by robgpeak** [comment]
I signed up for an Account, cl2@peakmarketing.cim received my 100 points, but it's not showing up in my points history
![screenshot_2017-07-16-13-19-13](https://user-images.githubusercontent.com/28393235/28249736-8e5f69b8-6a29-11e7-89e2-4069922679e0.png)

**Comment by cgladue** [comment]
whats the login for this test account ?

**Comment by robgpeak** [comment]
Password: 09876poiuy

**Comment by robgpeak** [comment]
@cgladue same thing for this new account dd7_test@peakmarketing.com. Same password

**Comment by robgpeak** [comment]
Shit, sorry @cgladue  it was dd8_test@peakmarketibg.com same pw

**Comment by cgladue** [comment]
Found the bug, it was in the view, Chris/Derek was only showing the history if there were redemptions on the account, when no redemptions had occured then it didnt show the history...

**Comment by cgladue** [comment]
@robgpeak can you try again ?

**Comment by robgpeak** [comment]
Seema to be working

**Comment by robgpeak** [comment]
Lol. That was my Italian accent
