### ISSUE TITLE
Adjust the slider on the myrewards page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#247]
"We want to have the slide bar default the little round circle to the left." 

Meaning, the Rewards Everywhere points should be at 1000 and the Capital Club points should be at 40 by default.

**Comment by ChrisASearles** [comment]
This change was made when I indicated so on the ticket it was originally included on. If you're not seeing it you may need to clear your cache or possibly the compiled javascript file never got published. Looping @cgladue in on this to verify it's not the latter.

**Comment by robgpeak** [comment]
@ChrisASearles I just registered a brand new account, and while I see the slide defaulting to the left, it dow not say 1000 it is still showing the number of point I would have after the transfer.
![screenshot_2017-07-17-06-40-18](https://user-images.githubusercontent.com/28393235/28264905-1ff28f18-6abb-11e7-8d08-ae61d3686900.png)

**Comment by ChrisASearles** [comment]
@robgpeak I'm able to verify this is displaying and working correctly, I'm sure it's just a caching issue on your end. Make sure you clear your cache and refresh the page and you should be seeing it function as you described.


![uploads/afcfe210-e01f-4318-aab6-e0687d7da205/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fafcfe210-e01f-4318-aab6-e0687d7da205%2Fimage.png)

**Comment by robgpeak** [comment]
It is working correctly now

**Comment by robgpeak** [comment]
@ChrisASearles I just cleared my cache on my phone, and I am still seeing it show the number of points that will be left after the transfer, instead of the number of points I want to transfer...
![screenshot_2017-07-18-18-12-56](https://user-images.githubusercontent.com/28393235/28346347-4db25bb0-6be5-11e7-97d0-5e08e2b7b2d6.png)

**Comment by robgpeak** [comment]
@ChrisASearles It has something to do with mobile.  Please check it on mobile on your end.  I just tried in my default browser on my phone and the same thing happened
