### ISSUE TITLE
Category page updates

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#25]
Category page should load similarly to the home page with a featured stores section and a featured deals section underneath. Let's define a standard for how many rows we'll show at full screen size. 3-4 seems like the right number, will need to make a decision on how these will load at mobile or small sizes.

Need to get the back-end work on this done; on the front end cards should look and function as defined for the homepage in issues #23 and #22.

**Comment by cgladue** [comment]
by category page what URL do you mean ?  can you give me an example URL for one of the pages you are referring to ?

**Comment by ChrisASearles** [comment]
@cgladue default category detail page: http://shop.complinks.co/category/index/10

**Comment by cgladue** [comment]
Rob has asked for a featured "category" that will be seperate from other categories and stand on its own, this is the featured advertiser data i am passing currently.

**Comment by ChrisASearles** [comment]
@cgladue not sure what that's for but I don't think it's related to this issue. @robgpeak can you clarify?

**Comment by cgladue** [comment]
because you are asking to display featured stores within the category view, to me that dosnt make sense since the featured stores are a mixed category of stores across multiple categories.

**Comment by robgpeak** [comment]
Guys, unfortunately we are going to need to have a verbal conversation.  I could write a simple answer to this issue, but without a verbal conversation, other similar issue will continue.  The simple answer is, you are one two different pages on this one, literally.  Chad is talking about "featured" being a category in the back end, so we can assign a display order, independent of the order of stores within their respective categories.  Then how they are displayed in a "Features Stores" container on the front end would be up to Chris, and where he thinks they make the most sense. 

Again, we MUST have a conversation regarding this and a host of other things.  Please let me know when we can all speak.

**Comment by ChrisASearles** [comment]
Hey @cgladue I think this issue was clarified with the change you made in #32 to be able to pull featured advertisers by category. Can you confirm when that gets added to the view model?

**Comment by cgladue** [comment]
Featured advertisers are only in 1 category right now, the "Featured" category depending on which ViewModel you are referring to shoudl already be there...

**Comment by robgpeak** [comment]
The Featured category should behave like any other category, and an advertiser CAN be in multiple categories.  So for example, Macy's can be in "Women's Clothing" as number 2, "Men's Clothing" as number 7, and also in "Featured" as number 4...

**Comment by cgladue** [comment]
@robgpeak and that is how it functions exactly as of right now.

**Comment by robgpeak** [comment]
Gotcha.  I just was not sure, as when I go to edit the order of the "Featured" category I get an error message.

**Comment by cgladue** [comment]
That was because there was no advertisers in the category, i have added one and its ok now.

**Comment by ChrisASearles** [comment]
Updates committed. @robgpeak the "Featured Deals" section needs a little work at various sizes and will be tracked under a separate issue because it affects multiple pages.

**Comment by cgladue** [comment]
published

**Comment by robgpeak** [comment]
This is why I suggested we have a verbal conversation on this issue...

I still think we have confusion on the "Feature <Category_Name> Stores" section in any particular category.

The original idea was to have "Shop <Category_Name> Stores" and have 8 or 12 Store Boxes for each category, and then a list of ALL the stores in that category.  We would then be able to, (in the back end), control the order of Store Boxes.  So for example, if there are 50 stores in that category, and we only have 1 through 10 numbered in the https://shop.complinks.co/admindashboard/advertisers/setAdvertiserDisplayOrder/10 for example, then only those 10 Store Boxes would be in the "Shop <Category_Name> Stores", and ALL 50 would be in alphabetical order in the "All <Category_Name> Stores".

I think the confusion comes from using the term "Featured" within category, so now instead of "Shop <Category_Name> Stores" it became "Featured <Category_Name> Stores".  We can still leave the section heading "Featured <Category_Name> Stores", but those Store Boxes would be derived from the setAdvertiserDisplayOrder for that particular category.

The Featured category itself, would be just like it's own category, with it's own setAdvertiserDisplayOrder, and the ONLY place they would show up on the front end is where they are called up to be displayed as a separate category.  So for example on the home screen, we might have a section that says, "Featured Stores", and those would be pulled and displayed in the order that we chose in the back end.

IMPORTANT NOTE, we will only display the Store Boxes if there is a number in the setAdvertiserDisplayOrder.  So there might be 50 advertisers in the list, but unless there is a number greater than 0, we will not show it in the "Featured <Category_Name> Stores".

Any questions, please ask.

**Comment by ChrisASearles** [comment]
@cgladue can you update the controller to pull data as @robgpeak describes above? that should close this ticket out.

**Comment by robgpeak** [comment]
@cgladue This was assigned to me, but I am not sure why.  The "Featured <Category_Name> Stores" section on the pages are not working as I described, and I think there still might be some confusion.  If you are able to talk on the phone for a minute, please give me a call to discuss.

**Comment by ChrisASearles** [comment]
@robgpeak I'm pretty sure the changes you're talking about are being tracked under #129

**Comment by robgpeak** [comment]
Actually they are two separate issues.  They may overlap slightly, but again, both separate issues.

**Comment by ChrisASearles** [comment]
Yeah, sorry, I thought this was assigned to you because the data changes had been made but I'm not seeing them on my end either.

**Comment by ChrisASearles** [comment]
@cgladue I did something I thought would work here but it resulted in some errors popping up in the DAL so I'm going to leave this to you to pull the right data.

**Comment by cgladue** [comment]
i still dont even know what needs to be done here, the store page shows featured stores that are also in the current category as is being displayed under Featured Stores, Under Featured Deals i am displaying all links for the stores in the category that are marked as featured, and all automotive stores is just a list of all stores in that category so what needs to change exactly ?

**Comment by robgpeak** [comment]
Guys, while I know getting on the phone is your least favorite thing to do, let me make a short screen cast of what I think the issues still are...  Give me a few.

**Comment by robgpeak** [comment]
I can't get to a category page to make a screencast

**Comment by cgladue** [comment]
im looking at that now something happened in the last two hours when i left to the casino for a meeting, ill get back with you

**Comment by ChrisASearles** [comment]
@cgladue I thought that's how this should function as well so I understand the confusion!

Within a category page, @robgpeak wants advertisers that have a display order set for that category to load as "Featured Stores" within that category sorted by that display order.

All stores that are in that category that don't have a display order set for that category would load in the "All Stores" section ordered by name.

**Comment by cgladue** [comment]
:frowning_face:

**Comment by ChrisASearles** [comment]
Unfortunately I deleted what I think was working code that solved the problem because I thought it was what was causing the error on the category page but it looks like it's something else.

**Comment by cgladue** [comment]
i am publishing all your latest updates as well as the correction to the problem now, the issue was advertisers who were active but have no links loaded for them, since rob wants the start trip link to be the oldest link if none set it was erroring out when there was no main link and no links to default to.

**Comment by cgladue** [comment]
shit maybe not... hang on

**Comment by cgladue** [comment]
getting a different error now, think its your code:

![image](https://cloud.githubusercontent.com/assets/7914133/26651184/db0270be-4619-11e7-950a-f64dffc38ca4.png)

**Comment by ChrisASearles** [comment]
Yeah, that's what I couldn't test (but I crossed my fingers really hard ...). Comment out that line for now and commit your fix and I'll fix that.

**Comment by ChrisASearles** [comment]
Give me a second actually, I can fix it now for you.

**Comment by cgladue** [comment]
i already committed my stuff

**Comment by ChrisASearles** [comment]
Ok, no worries, I'll get that fixed and in now too.

**Comment by robgpeak** [comment]
Just for a brief explanation as to the reasoning behind doing it the way I described in this thread 6 days ago is... If we only used the Featured category, (I know it's not really a category like the others, i.e. Automotive, Women's Clothing, etc. but for the purposes of this discussion, it's a category), and the order of the advertisers in that category to determine whether or not a Featured store shows up in a particular category, the numbering system would get crazy.

Let's say we had 6 "Featured Stores" in each of the 18 "Real" categories, that would be 108 different advertisers in the Featured category list in the back end.  So if I wanted the order of the list in the Automotive category "Featured Automotive Shops" section to be AutoZone, Euroauto, VinAudit, etc... I would have to look through a list of 108 numbers, and know which one is where in the list to then make sure they are in the right order.  Just not the right solution.

Let's just use the individual advertiser in setAdvertiserDisplayOrder to be the order within each category, and the Featured category itself, will be just what appears on the home page.

**Comment by robgpeak** [comment]
@ChrisASearles This issue as well should be at the top of the priority list.  It is a very simple fix in my mind, but I think it might be a tough thread to follow, and perhaps a voice discussion may be beneficial with us and @cgladue

**Comment by ChrisASearles** [comment]
@cgladue what's the status on this?

**Comment by cgladue** [comment]
@ChrisASearles @robgpeak we will have to discuss on our call today because at this point i have no friggin clue what this should be doing compared to what it is currently doing

**Comment by robgpeak** [comment]
@cgladue @ChrisASearles had to move the call back to 3:00.

**Comment by robgpeak** [comment]
@cgladue @ChrisASearles Lucky for you guys, I just found a screencast that explains where the confusion comes from, and then the remedy to fix it.  Happy viewing  https://screencast.com/t/LQ6niIz1

**Comment by cgladue** [comment]
@robgpeak i THINK this is now how you want it can you take a gander ?

**Comment by robgpeak** [comment]
Yes, but the "All <Category_Name> Store section should have ALL the stores alphabetically, even if their number is 0 in the display order.  

So if you look at https://shop.complinks.co/admindashboard/advertisers/setAdvertiserDisplayOrder/11 and https://shop.complinks.co/category/index/11 you'll see that the ones with "0" at not in the ALL section, and they should be.

**Comment by cgladue** [comment]
@robgpeak take a look now !!

**Comment by robgpeak** [comment]
Yes.  Works great now.
