### ISSUE TITLE
Crediting 50 points for users who open and click on a link in our promotional emails

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#256]
@cgladue @ChrisASearles I just sent both of you a test email that I am working on from MailChimp, and I wanted to start a thread to discuss the idea of crediting each user 50 points (one time) when they open and click on a link within our promotional emails.

Actually, now that I am thinking about it, we should make it a separate link (meaning, not even a store, just a link to our site that works one time per person...)  [Get your 50 points now] I think that would be much easier to manage.

Then of course we would need to update the points history for the users account...

**Comment by robgpeak** [comment]
@cgladue I wanted to get your thoughts on this?

**Comment by cgladue** [comment]
mailchimp does not send me any notifications when someone opens an email...

but i could design a system where you specify the # of points and some
settings and it generates a unique link which you can then put into your
email blast, and when someone clicks that link and goes to the site, it
will credit their account the points ...

how does that sound ?



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
That sound like a plan.  I guess we can try it that way and see how it goes.  I suppose it's better than pigeon holing someone into visiting a particular merchant if they don't want to use that merchant.   But now just thinking out loud, getting them to visit the website from the email and paying the xx points is good, but getting them to make a shopping trip and ultimately a purchase in the main objective.  Again, we can start this way and see how it goes and then adjust as needed.

So yeah, a system that I can put in the parameters in the back end (how many points to credit, the name of the promotion, description), and it would generate a unique link that I could copy and paste into and email, or even on the site (thinking of other possibilities later on).

Then in the users Transaction History, they would see something like:

Date	Type	Points	Description
8/24/2017 8:37:47 PM	Opt-In Bonus	100	Email Opt-In Bonus
8/25/2017 9:37:04 AM     Email Link       50     Visit From Clicking Link
