### ISSUE TITLE
not receiving 100 points for opting in at xclub.complinks.co

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#265]
@cgladue I just signed up for a second test account and did not receive the 100 points

**Comment by cgladue** [comment]
I need to create the web hook.  Give me a bit and I’ll add it in Mailchimp.

**Comment by robgpeak** [comment]
Ah, ok.  I did not know that.

Thanks,

Rob

**Sent from my phone

On Jan 9, 2018 2:59 PM, "cgladue" <notifications@github.com> wrote:

I need to create the web hook. Give me a bit and I’ll add it in Mailchimp.

> On Jan 9, 2018, at 2:48 PM, robgpeak <notifications@github.com> wrote:
>
> @cgladue I just signed up for a second test account and did not receive
the 100 points
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisASearles/CompLinks/issues/265#issuecomment-356396905>,
or mute the thread

**Comment by cgladue** [comment]
yea, its in a prior issue in here, any new subdomain that gets created
needs to have the webhook added in mailchimp, go to the list then go to
settings->Web Hooks and enter this url:


   -

   https://<subdomain>.complinks.co/mailchimp

   Edit
   <https://us14.admin.mailchimp.com/lists/tools/webhooks-edit?id=103441&hookId=701>
   - so in this case it would be:
   -

      https://xclub.complinks.co/mailchimp

      Edit
      <https://us14.admin.mailchimp.com/lists/tools/webhooks-edit?id=103441&hookId=701>
      -




Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
try it now, i added the web hook.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
Just registered again but I did not get the 100 points

Thanks,

Rob

---

Rob Gallo
President
Peak Marketing
robg@peakmarketing.com
mobile: +1 631 682 5107
skype: robg888
bio: https://www.linkedin.com/in/peakmarketing

http://www.PeakMarketing.com <http://www.peakmarketing.com>

**Comment by cgladue** [comment]
i just registered cgladue@foxwoods.com and i got the 100 points after
clicking the email link .... there was a delay from mailchip tho ... they
do not guarentee it happens immediatly.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
I see it in my account now.  I will make a note to the end user that it may
take a couple of minutes to show up.  Thanks.

Thanks,

Rob

---

Rob Gallo
President
Peak Marketing
robg@peakmarketing.com
mobile: +1 631 682 5107
skype: robg888
bio: https://www.linkedin.com/in/peakmarketing

http://www.PeakMarketing.com <http://www.peakmarketing.com>
