### ISSUE TITLE
Expand search on large screens

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#3]

**Comment by ChrisASearles** [comment]
Needs to be limited in size on larger screens, black placeholder text doesn't work with the blue background. Should we change this to a more traditional text box at this size or leave it as a material box and work on the style? If it stays as a material box, the label should respond accordingly.

**Comment by ChrisASearles** [comment]
@Dwells7583 I think I broke the mobile version of the search bar in a more recent commit.

**Comment by Dwells7583** [comment]
Fixed search on mobile
