### ISSUE TITLE
Set navigation icon from category record in DB

### ISSUE THREAD

**Issue by cgladue** [ChrisASearles/CompLinks#30]
need to be able to specify the icon for the Store Category in the DB.

**Comment by ChrisASearles** [comment]
Reopened this as I don't believe we're displaying these yet, are we @Dwells7583

**Comment by cgladue** [comment]
i have updated the layout to display this and comitted it

**Comment by robgpeak** [comment]
@cgladue what are the size limitations on the header images for the categories?  file size and dimensions? I am going to keep the files sizes as small as possible anyway, but I just wanted to know.

**Comment by cgladue** [comment]
it would be up to chris, on my end i am not limiting the size



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=chadgladue@gmail.com&idSignature=22>



Chad Gladue
*DevNull Technology, LLC*
