### ISSUE TITLE
Move display order to the advertisercategory join table instead of on the advertiser record.

### ISSUE THREAD

**Issue by cgladue** [ChrisASearles/CompLinks#32]
This will allow each category that the advertiser is in to have a seperate display order.

**Comment by cgladue** [comment]
Moved the displayOrder field to AdvertiserCategory Join Table.  When the category page pulls list of advertisers, the display order is built dynamically based on the category that is being displayed.

**Comment by cgladue** [comment]
Rob, display order is no longer on the advertiser record on backend page.  It is now under the category page, action choice "Set Advertiser Display Order"  this will show all active == true advertisers only since inactive advertisers would confuse the numbering.

**Comment by robgpeak** [comment]
For the purposes of Phase 1, I am going to mark this as complete, but later on down the road, we are going to enhance the functionality of this system.  Meaning, it would be nice to be able to reorder them by just dragging and dropping them.  Or at the very least, to be able to sort by the order they are list in.

**Comment by ChrisASearles** [comment]
@robgpeak Please feel free to add these as new issues/feature requests and we'll get them scheduled with an appropriate milestone sometime in the future.
