### ISSUE TITLE
Add Disclaimer Field to advertiser record.

### ISSUE THREAD

**Issue by cgladue** [ChrisASearles/CompLinks#33]
Add Disclaimer field for disclaimer info to be displayed on the store page.

**Comment by cgladue** [comment]
http://shop.complinks.co/stores/index/11

field added to advertiser maintenance page, will display on advertiser page.

**Comment by robgpeak** [comment]
@cgladue please do me a favor and put "No points earned on the purchase of gift cards." in all of the "Disclaimer" fields in the db, and even put it in the new advertisers be default.  It is sort of universal.  Morgan can tweak and adjust as necessary where need be.

**Comment by cgladue** [comment]
Done, the disclaimer field has been updated globally to read "No points earned on the purchase of gift cards." and all new advertisers will have that text by default.
