### ISSUE TITLE
create Activity Feed on the backend

### ISSUE THREAD

**Issue by cgladue** [ChrisASearles/CompLinks#34]
create Activity Feed on the backend that displays changes to advertisers and links.

**Comment by robgpeak** [comment]
Please put a link to the Activity Feed on the left nav menu

**Comment by cgladue** [comment]
the activity feed is on the "Home" page for the admin backend .. and there is already a link to "Home" would you prefer it not be on the home page and put somewhere else.

**Comment by robgpeak** [comment]
We've got bigger fish to fry.  Leave it as it is for now.

**Comment by ChrisASearles** [comment]
@cgladue please add all items to the backlog without milestones and work on the priority list as outlined from top to bottom in Huboard. This is how we're trying to ensure we're collaborating in a way that prioritizes the stuff that needs to be done to get a working version out the door and that we all can continue to work without waiting on the other to complete something. I'll move issues from the backlog into ready and prioritize accordingly.

**Comment by cgladue** [comment]
@ChrisASearles i had completed all my assigned tasks when i worked on this.  I can choose what i think is an easy fix and what will take more time.  Easy fixes i can do during the week ( i do have a real 9a-9p job) the more involved ones i do on weekends when i have more time to devote uninterrupted.  What exactly are you waiting on me to do that you cant move forward on, if you have issue #'s that would be helpful.  i dont see any blocked' tags ?

**Comment by ChrisASearles** [comment]
@cgladue mainly trying to keep on top of the items that are prioritized for this release and generally what the status of the project is. when these get moved through without me even seeing them I'm having a hard time keeping up with items that need to be done vs ones that are waiting to be pushed to the production site. Really just a bookkeeping request on my end.

**Comment by cgladue** [comment]
Would you prefer i left them in a particular status or added a particular flag on them so you know which ones to review ?

**Comment by ChrisASearles** [comment]
Yeah, if you add them to the backlog with no milestone that's where I try to process my queue from. Thanks Chad.
