### ISSUE TITLE
Display Order for Categories

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#35]
Add a Display Order field for categories that should be used as the OrderBy on the front end.

**Comment by cgladue** [comment]
you are talking the categories themselves not just the advertisers in the categories ?

**Comment by ChrisASearles** [comment]
@cgladue Looks like I misread the list you sent me last week. The item you sent was written as "Display order by category by advertiser" so I broke that into two individual items but I see now you mean by advertiser within each category so I'm going to close this.
