### ISSUE TITLE
Add icon to category record

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#38]
Store a string in the category record related to the material icon to be used for each category. These should be inserted in the sidenav on the site.

**Comment by cgladue** [comment]
This was already done.

**Comment by ChrisASearles** [comment]
I see that @cgladue can you please be sure to move your items through the board in huboard, I'm seeing a lot of stuff that was done or worked on but hasn't been moved to the right columns.

**Comment by cgladue** [comment]
i thought it was tied to github, it dosnt change status in hubord when i
change it in github, honestly hubord is pretty shitty.

**Comment by ChrisASearles** [comment]
If you have a better option I'm all ears but this is the best way we've got so far for everyone to be able to get a good overview of the current status of the entire project. I've not had any issues with it so far so please let me know if there's something specific that's tripping you up or that you're not liking about it that you have a better alternative for.

**Comment by cgladue** [comment]
i prefer to just use github, huboard dosnt offer me anything that the labels in github dosnt

**Comment by cgladue** [comment]
or get it so when i change labels in github it updates on huboard without having to do it twice
