### ISSUE TITLE
Add first name, last name, and mobile number to registration model

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#39]

**Comment by cgladue** [comment]
First and Last Name added already, ill add mobile also

**Comment by ChrisASearles** [comment]
Hey @cgladue hold off on this a minute, this was in the list you sent me but Rob mentioned something this morning about wanting something different. @robgpeak do you want to comment on this?

**Comment by robgpeak** [comment]
This has been revised to #63

**Comment by cgladue** [comment]
Sounds like only email and password is required during signup, in which case this issue is closed as its no longer relevant.
