### ISSUE TITLE
Hero feature: Should display image of the casino (tenant) loaded from DB and the current text if !Authorized, else change text to link to "How it Works" page

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#4]
Text when logged in: https://app.moqups.com/robg/QSDVx2F07W/edit/page/a7f4ce830

**Comment by cgladue** [comment]
will add a field for style info to partner maintenance screen

**Comment by Dwells7583** [comment]
Added the correct text when logged in, image is the same currently. @cgladue I used the same image hard coded in with the passing of the gift, not sure how that will be passed through? A default hero image should be added from the back end I would assume.

**Comment by cgladue** [comment]
@Dwells7583 its already part of the ViewBag.partner object, heroUrl and logoUrl properties.

**Comment by Dwells7583** [comment]
Yes the partner image is, but what about the default non logged in image? That would need to also be swapped from time to time? @robgpeak  @cgladue

**Comment by cgladue** [comment]
The hero Image is controlled by the subdomain name .. and is displayed regardlesss of being loged in or not, am i mistaken ? @robgpeak

**Comment by Dwells7583** [comment]
Oh ok, I may be mistaken then.

**Comment by cgladue** [comment]
One of us is, lol im not sure who tho @robgpeak  will have to step in

**Comment by robgpeak** [comment]
The original idea and thought behind the swapping of the hero image was to show a different image to people who are logged in or not.  The first image is meant to convey, "Here is why you need to sign up..."  The second one (when someone is logged in), is meant to convey, "Now that you're a member, here are all the cool things you can get by using the app..."

**Comment by cgladue** [comment]
@robgpeak so you want me to add a second hero image upload option on the partner maintenance record ?

**Comment by robgpeak** [comment]
yes please.  Call them "Hero Image Standard" and "Hero Image Authenticated"

**Comment by Dwells7583** [comment]
Can I update this. Currently it is @partner.heroUrl, but i do not see the updates versions. Let me know when that is updated.  @cgladue

**Comment by Dwells7583** [comment]
The recommended image size for the Hero is now 850x400.

**Comment by Dwells7583** [comment]
I did not see the Hero image standard or authenticated yet. @cgladue  let me know when that is complete.

**Comment by cgladue** [comment]
standard hero image is called Partner.heroImageUrl property, the authenticated one will be added tonight, will be Partner.authenticatedHeroImageUrl

**Comment by cgladue** [comment]
the standard hero image is already implemented and being used on the Home/Index.cshtml view

**Comment by Dwells7583** [comment]
Yes the Standard is currently partner.heroUrl, I am going to leave them as that for now just so we do not have a missing image. Let me know when the others are updated. @cgladue

**Comment by Dwells7583** [comment]
@robgpeak I reworked the Hero Image section from the ground up to be more optimal  The recommended image size would be 850x400. so it will look best across all sizes.

**Comment by robgpeak** [comment]
Cool Derek.  Looks nice.  One thing that does look a little strange is when you reduce the size of your browser screen, part of the image (the right side), is covered up by the white area to the right with the text in it, instead of the image actually scaling down.

**Comment by Dwells7583** [comment]
That is done with a wrapper to ensure the image works well across all size. So a small portion of the right side will be cropped between 600-980px in order to preserve the aesthetics above and below as well as keep in in line with the rest of the content to the right.

**Comment by Dwells7583** [comment]
@cgladue Did you add the two options yet?

**Comment by ChrisASearles** [comment]
@Dwells7583 something we changed today broke this functionality, please take a look and fix.

**Comment by Dwells7583** [comment]
@ChrisASearles This has been fixed. a few styles were missing.

**Comment by Dwells7583** [comment]
@robgpeak I adjusted it to not cut off the right side. It will now center at that small size. The reason for this is that the image is wrapped in a containing div that masks the image to help scale it up and down to difference sizes. If you scaled the image proportionally it will not take up the area needed for the text and the featured deals to the right.

**Comment by robgpeak** [comment]
OK.  I noticed the hero image and the div are behaving differently on doverdowns.complinks.co at various screen sizes.  Maybe it is because of the size of the image.  What is the optimal size of the image to completely fill up that div?

**Comment by Dwells7583** [comment]
Yes,  I updated that image on the backend, but it looks like my changes are actually not published yet. I just checked.

**Comment by cgladue** [comment]
i just published whatever was committed up till 30 minutes ago

**Comment by Dwells7583** [comment]
I just committed another change to cat page that should have been included on your last publish. maybe was a merge issue. Can you publish what I just committed?

**Comment by Dwells7583** [comment]
sorry the last commit that should be included was the "missing hero style"

**Comment by cgladue** [comment]
ok, published again

**Comment by Dwells7583** [comment]
@robgpeak It was a cached on the server. all my updates styles are now visible. The hero image should respond the same on both now.

**Comment by Dwells7583** [comment]
@cgladue Let me know when I can add in the correct data for the two images.

**Comment by cgladue** [comment]
@Dwells7583 as far as i know you only need the authenticatedHeroImage added, the heroUrl is already there ... confirm what the second image you are waiting on me is for

**Comment by Dwells7583** [comment]
Yes the authenticatedHeroImage.

**Comment by cgladue** [comment]
@Dwells7583 It has been added

heroUrlAuthenticated is the property

**Comment by Dwells7583** [comment]
This is updated. But I tried to upload a new photo. and it did not work on the back end.

**Comment by cgladue** [comment]
@Dwells7583 all set there was a bug saving the URL when the partner existed already.
