### ISSUE TITLE
Navigation changes

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#41]
Remove sidenav on screens > SM, update nav to include the following elements:

- Categories (dropdown with category list, probably needs to be separated into columns)
- Featured Stores (dropdown, display based on number of elements returned)
- Featured Deals (dropdown, display based on number of elements returned)

Need to somehow mark the "Featured" elements in the DB so they can be loaded on the front end. I know we have featured stores within the categories already, I would think this either needs to be separate or we can just pull the first 1 or 2 based on DisplayOrder from each category?

These nav elements need to be echoed in the sidenav for SM and XS devices.

**Comment by cgladue** [comment]
We do not have featured per category we have a category called Featured that contains all the featured advertisers.

**Comment by cgladue** [comment]
i will return PartialView("Name)  in the controller action 
and in the view call html.partial("name", controller") and return categories as well as featured stores.

**Comment by ChrisASearles** [comment]
This should be completely functional as soon as the issue with the featured deals is sorted out that's being tracked under #84. There are still some minor display issues I'd like to address but I want to track those under separate issue tickets (some like not capturing a user's first and last name have been introduced with recent changes and need some discussion).

**Comment by cgladue** [comment]
this should be cleard up with my recent committ..
