### ISSUE TITLE
Header nav changes

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#42]
- Remove "Account" icon on the toolbar.
- Move "Terms & Cond.", "Privacy Policy", and "FAQ" to footer.
- Change this section to display just "Sign Up" and "Login" for unauthenticated users
- Authenticated users should see their name, point total, and a dropdown list with the following items:
    - Manage Account
    - My Rewards
    - Shopping Trips
    - Favorite Stores
    - Support
    - Log Out

**Comment by ChrisASearles** [comment]
Check #45 for Footer task

**Comment by robgpeak** [comment]
If a user is logged in, we should display the just the user's First name, not first and last.  If the "First Name" field in that users record is blank/empty, we should display the prefix of their email address.  For example robg@peakmarekting.com would display "ROBG - 2,000 POINTS"
