### ISSUE TITLE
Add header image to category page

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#44]
Category pages need to have a header image defined for the page.

@Dwells7583 we need to define the format for this image for display, @cgladue we need to include this in the admin section and add it to the model for the category detail page.

**Comment by cgladue** [comment]
this is complete as well

**Comment by ChrisASearles** [comment]
I'm going to close this as a duplicate, that was supposed to get reassigned to Derek to specify image specs within the design. Going to update that ticket now @cgladue
