### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#45]
Some of the content for the footer is detailed in #42

**Comment by robgpeak** [comment]
@ChrisASearles , I don't see any of the content for the footer in #42.  You can see it at the bottom of https://app.moqups.com/robg/QSDVx2F07W/edit/page/a9762b57c

Additionally, based on my understanding of Huboards, this task being in the "Review" would mean that something has been completed, and I would be approving it and dragging it to Done, or  making a comment such as this, and then someone else (You, Derek or Chad) would be dragging it back to another column to work on something, and then putting it back here in Review when it is ready for me to look at.

**Comment by ChrisASearles** [comment]
@robgpeak Just included a description of the process in another issue, Review contains items that have been committed to the source repository but not all will be available for you to review until @cgladue publishes a new version and reassigns those issues to you or @morganpeak. Sometimes these versions are held off purposely because the code that's committed may be buggy and just intended for us to share code back and forth.

**Comment by ChrisASearles** [comment]
@Dwells7583 footer shouldn't be docked to the bottom, should be included inside an md-content. Hold off on this until you rework the nav menus (#41) as they'll likely go together.

**Comment by robgpeak** [comment]
Based on the footer that is in place currently, I made two notes regarding functionality (sticky note 3 & 4) at the bottom of https://app.moqups.com/robg/QSDVx2F07W/edit/page/a1819d6ea

**Comment by robgpeak** [comment]
Is it possible to have a thin gray line separate the different sections in the footer when it show up in mobile.  As per the attached mock up as an example.


![uploads/899544f1-00f3-4531-aa7d-99fd4fd6d00e/Screen Shot 2017-06-02 at 12.55.08 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F899544f1-00f3-4531-aa7d-99fd4fd6d00e%2FScreen+Shot+2017-06-02+at+12.55.08+PM.png)

**Comment by robgpeak** [comment]
@ChrisASearles Shit, I did it again.  I posted a comment to an issue that was in review, and it was not assigned to anyone, so I suppose it is not showing up on anyone's radar.
