### ISSUE TITLE
User Dashboard Page

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#46]
@Dwells7583 we need to mock up a version of this displaying the most critical information for a user's account (total points earned, current points, most recent trips and status, new favorites (future feature), last reward redemption, etc.).

**Comment by Dwells7583** [comment]
@cgladue Can you add all the user info from the User Model to the UserDashboardIndex Model so I can use it on the userdashboardIndex page. I am going to mock it up for now with dummy text.

**Comment by Dwells7583** [comment]
Also need to be able to load the Trips and points redeemed all on the main dashboard page

**Comment by cgladue** [comment]
@Dwells7583 @robgpeak Derek,  we arent going to use /userdashboard/Index anymore for the user dashboard/Profile  Rob and i agree that the user pages should be part of the front end so i will add User Info, Trips and Redemptions to a new Viewmodel on a new action for the user frontend.

**Comment by Dwells7583** [comment]
I believe @ChrisASearles had a discussion with @robgpeak and @morganpeakl about the way this was going to function and display at meeting here. @robgpeak Looking to clear this up. Thanks.

**Comment by robgpeak** [comment]
We did have the conversation when I was at the office, and the decision was made to have the user dashboard Pages look like the front end.

**Comment by ChrisASearles** [comment]
Most of this is just terminology. @Dwells7583 is working on what's there currently and we're fine leaving it in the Area. @cgladue if you have a reason for wanting to pull it out of it's own area that's fine, let's just coordinate so we don't have to duplicate any work.

**Comment by cgladue** [comment]
tonight ill add the actions to the controller and create the views for you to mess with, the reason for not leaving it where it is currently is that area shares its CSS with the rest of the admin and partner styleing and dont want to change all that with whatever styleing you do for this.

**Comment by ChrisASearles** [comment]
@cgladue we already changed the layout page for those views so that's not a big deal for us, it actually makes some sense to leave it as-is because we ended up nesting two layout pages together so at least there's a logical connection between all those views. hate to make more work for everybody if what we already have is working ...

**Comment by cgladue** [comment]
@ChrisASearles as long as your OK with me removing the UserDashboard Area i dont want to mix the Front end and the backend Controllers/Views/Areas

**Comment by ChrisASearles** [comment]
@cgladue that's fine, just make sure all of the work we did on the front-end get's copied over to the new views. @Dwells7583 make sure you commit those changes before you leave so Chad has the latest version.

**Comment by Dwells7583** [comment]
@cgladue I was getting an error on the rewards and shopping trip pages. But I committed up what i was working on. You will see the dashboard page is filled with dummy content, if you want to go in and update that while you are in there as well. The dashboard recent trips and recent points redeemed needs to display a certain number of entries.

**Comment by cgladue** [comment]
@Dwells7583 Error : Copying file Views\Shared\_DashboardLayout_old.cshtml to obj\Release\Package\PackageTmp\Views\Shared\_DashboardLayout_old.cshtml failed. Could not find file 'Views\Shared\_DashboardLayout_old.cshtml'.

can you please include that file and committ it

**Comment by cgladue** [comment]
Also _DashboardNav.cshtml too please

**Comment by cgladue** [comment]
@ChrisASearles @Dwells7583 This has been completed and nav updated, Controllers are MyRewards, Trips, and MyRedemptions

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
Looks nice full screen, but only seeing two columns in the tables when reduced to mobile resolution.

Also, there is a type-o in the code of the "Most Recent Points Redeemed" section.  You will only see it if you've had a redemption...  The reward description reads "40 CompLinks Rewards Points/td>"  That "/td>" should not be in there.

Shit, while we're at it... never mind, I will start a different issue.

**Comment by Dwells7583** [comment]
Updated look of this page as well on small sizes
