### ISSUE TITLE
Update buttons and links to use accent palette

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#5]

**Comment by robgpeak** [comment]
Derek, I see the buttons on the store index page using the color palette, but the main link to the store next to the description should also be a button.  Additionally, I think the accent color palette should be the orange in this case, something that makes the shop now button stand out more on the page.  https://screencast.com/t/PilhDB76Wv (I love my screencasts:)

@ChrisASearles would I leave this task in review and let Derek move it to his queue?

**Comment by ChrisASearles** [comment]
@robgpeak this change has been made, looks like it hasn't been published yet. This was just a change to the current buttons, new design changes like the one you're describing are covered in other issues already and are scheduled to be made. The process for these is that @cgladue will reassign issues in the review column to you and @morganpeak once he pushes them up to the production site. You can ignore issues until they've been assigned to you for review.

**Comment by robgpeak** [comment]
@cgladue how often are changes push up to the production site?

**Comment by cgladue** [comment]
my changes i push up several times a day... but Chris and Derek do not merge their branch with my branch very often.  so their changes havent been included for a while now.

**Comment by Dwells7583** [comment]
@cgladue @robgpeak I should have some changes to push by end of day today. Just trying to finalize a few things.

**Comment by robgpeak** [comment]
Oh boy, it's like Christmas Eve!!!

**Comment by cgladue** [comment]
Why was this assigned to me, what do you need ?

ViewBag.Partner.Style contains the style object for the partner .. only thing missing is the logo.  but colors are in there.

**Comment by ChrisASearles** [comment]
Hey @cgladue I assigned everything that we pushed to 'Review' that's waiting to be deployed so you had a better idea of what changes need to be reassigned to Rob when you push a new version up. Just thought it might be easier for you to keep track of but let me know if not!

**Comment by cgladue** [comment]
oh ok, i thought you were expecting me to do something ...
