### ISSUE TITLE
Password requirements should be clearly displayed on the login page

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#53]
Requirement is just an 8 character password

**Comment by cgladue** [comment]
displaying password requirements is a security flaw.

**Comment by ChrisASearles** [comment]
*Note - I edited the title of this issue, it previously said Login page but it's for the Register page

@cgladue I'm not aware of that being an issue, is that in the new NIST guidance? If so, we're currently returning that specific text as a error message, would that represent the same problem?

**Comment by cgladue** [comment]
Its common knowledge that telling an attacker the length of password saves them time from wasting time focusing on passwords that do not meet complexity requirements.  The fact that we are leaking password requirements in the error message should be corrected as well.

**Comment by ChrisASearles** [comment]
We need a solution to this that provides a usable experience while meeting security requirements. In the future maybe we can look at a solution to do something like a password strength meter, for now, how about a simple error message that says something like "Your password is too short, please try again."

**Comment by cgladue** [comment]
Fair Enough, that will do

**Comment by robgpeak** [comment]
While you're in there, is it possible to retain the information someone has already entered into the other fields.  That is good UX.

**Comment by cgladue** [comment]
what do you mean by "retain the information someone has already entered" ? you mean if they submit and the form is not complete ?

**Comment by robgpeak** [comment]
Exactly.

**Comment by ChrisASearles** [comment]
@robgpeak Please add anything that's not related to the password requirements and error messages as a new issue.
