### ISSUE TITLE
Shopping Trips page needs to be re-themed

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#54]

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
Brilliant!  Looks great full screen, just needs some help for mobile.  Only two columns are visible.

**Comment by Dwells7583** [comment]
@robgpeak  Ok removed the table from Small and Mobile view. Now will load in a scrollable card layout
