### ISSUE TITLE
Rewards page needs to be re-themed and renamed

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#55]
As per meeting with @morganpeak and @robgpeak last week, change title to "My Rewards."

This page should display how a user earned the rewards points they have.

**Comment by ChrisASearles** [comment]
@morganpeak I seem to remember discussing adding a "Redeem" page where the user would redeem their points but it's not in my notes. Do you remember where we landed on this?

**Comment by cgladue** [comment]
there is a page for the user to redeem their points already 

https://shop.complinks.co/userdashboard/rewards

**Comment by Dwells7583** [comment]
@cgladue Need to add user info such as points, and also the redemption model info onto this page.

**Comment by cgladue** [comment]
which page are you looking for ?

**Comment by Dwells7583** [comment]
rewards page yes

**Comment by cgladue** [comment]
i will remove the "pointBalance" property and replace with "currentUser" which will contain point balance info, you need to display redemption info as well on this page ?

**Comment by Dwells7583** [comment]
Yeah I thought it would be nice to see your redemption history under the redeeming of the points section.

**Comment by cgladue** [comment]
ok i have it done ill committ it in a sec

**Comment by Dwells7583** [comment]
@cgladue Can you check out this page, some of the functionality is not working correctly since I updated the style.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/26883310-c95c0e3c-4b6a-11e7-879a-3202d890736d.png)

**Comment by cgladue** [comment]
there are a ton of these errors, also the dropdown isnt really a dropdown ?  how can i get the value of the dropdown using jQuery ?

**Comment by ChrisASearles** [comment]
@cgladue Front end is built in Angular, jQuery shouldn't even be included. Do you want me to take a look at it?

**Comment by cgladue** [comment]
@ChrisASearles yep if that's the case then thats the only option.

It should work as follows, 

1. the dropdown will default to the minimum # of points they can redeem.  below that will be some wording saying "40 Capital Club Rewards Points will be credited to your account.


1000 Everywhere Points will be deducted from your balance."

when they change the dropdown it will update the verbiage accordingly,

if they have < 1000 points it will show in red that "You must redeem a minimum of 1,000 Everywhere points."

@robgpeak may have some other nuances to add to this...

**Comment by ChrisASearles** [comment]
@Dwells7583 I checked in a rough version of this page that needs your help to finalize. Once you're done let @cgladue know so he can add what he needs to submit the appropriate values in the form post.

**Comment by Dwells7583** [comment]
Updated small version and updated styles. @cgladue you can work on this.

**Comment by cgladue** [comment]
im not sure now to specify the post data that angular sends, but the pieces of info i need returned is:  

- rewardId = ID of the reward being redeemed (there is only one for right now, but may be more later on)  Model.Rewards.First().id should work for now.

- redeemedCost = # of Everywhere Points being redeemed

**Comment by ChrisASearles** [comment]
Yeah I saw that loop and wasn't sure what that was all about. What are the other potential types of rewards?

**Comment by cgladue** [comment]
In the future there may be rewards that have a fixed value, such as 15$ food coupon for 20,000 points or $10 Free Slot Play for 50,000 points etc, where the customer will just choose the reward and click redeem.  But for now rob only wants the freeform point redemption reward used only, so what you have there will work untill someone wants to give away fixed value rewards,

**Comment by ChrisASearles** [comment]
Gotcha.

**Comment by ChrisASearles** [comment]
Ok, should be all set. I just added two hidden inputs to bind the variables to. @cgladue I verified the data is posting properly but I don't have any points in my account to test the actual redemption process so if you could run through a quick one just to be sure that'd be great.

**Comment by robgpeak** [comment]
I really like the sliding scale better than the drop down for the redemption of the rewards,  Great job!

But there are a couple of small issues that I showed here... https://screencast.com/t/6oa9eiWOI

Basically, the number of the points shown on the left "Rewards Everywhere points" should show the actual number of points someone is looking to redeem, and the remaining balance that would be left after the redemption, (which is currently the way it is working).

In the line below that, lets have it read (1000 Rewards Everywhere = 40 CompLinks points).  Notice Rewards Everywhere does NOT include the word points, and the 40 <Partner_Name> points does NOT have a capital "p" in points, so it is consistent with the way the word points appears in the section immediately above this. (Meaning the redemption slide bar)

And so you know the actual redemption is not working yet...
<img width="914" alt="screen shot 2017-06-08 at 4 22 29 pm" src="https://user-images.githubusercontent.com/28393235/26949126-bfc10dd0-4c66-11e7-816a-8bfc02ed6faa.png">

**Comment by robgpeak** [comment]
I just saw the addition of (after transfer) to the rewards slider section, and that is still not the right UI/UX. It definitely needs to be the way I described it in my previous comment on this thread.  It should show the number of points I want to redeem, and the number of points I will be credited on the casino's end...

**Comment by ChrisASearles** [comment]
@robgpeak that was added before your comment, this hasn't been assigned to you yet

**Comment by robgpeak** [comment]
oops.  OK.  Sorry about that.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
I don't think this one is ready for me yet according to @ChrisASearles

**Comment by cgladue** [comment]
i didnt either but it was assigned to me with review label so not sure why

**Comment by robgpeak** [comment]
@ChrisASearles this one is now two months old, and really should have been resolved by now.

To recap:
1. We want to have the slide bar default the little round circle to the left.
2. The number on the left would start with the smallest amount of Rewards Everywhere points that cold be transferred, (in this case 1000), and show the number of {Casino_Name} points it would be converted to upon transferring on the right.  
3. Remove the (After Transfer) under the amounts.

The end result should look like this:

<img width="864" alt="screen shot 2017-07-11 at 5 12 58 pm" src="https://user-images.githubusercontent.com/28393235/28091076-ac38603c-665c-11e7-8bce-5c433ba73a21.png">

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
Close.  Number 1 in my comment two days ago is not done.  "We want to have the slide bar default the little round circle to the left."  Meaning, the Rewards Everywhere points should be at 1000 and the Capital Club points should be at 40 by default.

**Comment by cgladue** [comment]
@robgpeak Published
