### ISSUE TITLE
Support Page / Support Plan

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#56]
Need to add a Support page for authenticated users that allows them to contact customer service.

**Comment by ChrisASearles** [comment]
@morganpeak / @robgpeak have you guys figured out how you want to handle support requests yet? Did you decide on Zendesk or another alternative?

**Comment by morganpeak** [comment]
@ChrisASearles We are going to use Groove (groovehq.com)

**Comment by robgpeak** [comment]
As a follow up on this, we will have our online form in the support section of the site capture the fields; *'First_name', 'Last_name', *'Email_address', *'Comment_box' where * is "Required" field.  Question, if someone is already logged in, can/should we have the email field pre-populated with their email address?  If yes, we should allow them to edit it.

Not sure if this would be a separate discussion, but I noticed Chris mentioned "...Support page for authenticated users...", but what if a user is not logged in...?  She should still be able to send a message through the same form.

In either case, the comment box will have the sort of gray words that will disappear when someone clicks in the box to type, "Please enter your comments here..."

![uploads/d5a7726a-c1cc-4e03-92ce-04b08a6a7603/Not_logged_in_support_form.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd5a7726a-c1cc-4e03-92ce-04b08a6a7603%2FNot_logged_in_support_form.png)

![uploads/627a841c-24d2-4c1a-942c-f154769834a3/Logged_in_support_form.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F627a841c-24d2-4c1a-942c-f154769834a3%2FLogged_in_support_form.png)

The will send the message to support@complinks.co

**Comment by ChrisASearles** [comment]
@morganpeak @robgpeak can one of you guys get us the code for the widget? https://www.groovehq.com/apps/widget

**Comment by robgpeak** [comment]
@ChrisASearles I just added you as an admin to Groove.  When you get in, you can go to https://complinks.groovehq.com/groove_client/settings/api and get what you need.  I really don't understand it.

Also, keep in mind that at the moment, we only have the free plan with just info@complinks.co going through groove, which is the account for the advertisers to contact us.  Once we are ready to start testing support@complinks.co (for end users), I will replace info@ with support@.  

So perhaps we can have a conversation about some other platforms out there.  You mentioned Zendesk, do you have any experience with the platform?

**Comment by robgpeak** [comment]
@ChrisASearles have you done anything with this in the last two days?  Because all of a sudden since the 24th, none of our emails have been going through Groove.  I just emailed their support, but I figured I would check with you.

**Comment by ChrisASearles** [comment]
@robgpeak no, I haven't had a chance to get into it yet.

**Comment by ChrisASearles** [comment]
Committed.

**Comment by cgladue** [comment]
@robgpeak published

**Comment by robgpeak** [comment]
I like the little ? at the bottom of the page.

Two things @ChrisASearles 

1. I see that it is powered by Groove (which is fine), but were does the actual form get sent to?  Meaning, I did a test, and it DOES show up in Groove, but it does NOT show up in either support@complinks.co or info@complinks.co, which I think it should, only because then there is a backup failsafe version of the original email.

2. Can we replicate this same ? functionality (where it pops open the groove widget), from the "support" link in the user menu (authenticated) under the icon of the user, instead of just launching an email to support@complinks.co as it does now.

**Comment by ChrisASearles** [comment]
@robgpeak Number 1 above I don't have any control over, that's all their code and integration point and I customized it as much as they allowed. You'd have to contact Groove to see what options you have for email notifications.

Number 2 I might be able to hack together, let me give it a shot.

**Comment by ChrisASearles** [comment]
@robgpeak ended up just doing a direct integration via the Groove API for the support link in the nav. Change is committed.

**Comment by robgpeak** [comment]
Yeah, that's fine for now.  we'll see how it goes
