### ISSUE TITLE
Add My Account page

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#57]
This page is will allow users to change their email address, password, and manage any other personal / account information we collect.

**Comment by cgladue** [comment]
@ChrisASearles Page has been created and change password / first, last, mobile number fields added and functional, time for you to make it look pretty.

**Comment by cgladue** [comment]
oh, page is /account/profile

**Comment by robgpeak** [comment]
I have a crude mock up of some functionality for this page https://app.moqups.com/robg/QSDVx2F07W/edit/page/af53607d3

**Comment by Dwells7583** [comment]
@ChrisASearles I need some help with this page now. The update links should open in a dialog box to update the info. Also, I was having a few alignment issues as well.

**Comment by ChrisASearles** [comment]
@Dwells7583 we don't have time for that for this version, these should be editable with a save.

**Comment by Dwells7583** [comment]
Hey @cgladue I got it, only issue is the phone number not displaying as placeholder

**Comment by cgladue** [comment]
@Dwells7583 oh good, ok you need me to do anything ?  you can add the placeholder in there right ?

can you add jQuery.maskedInput so it forces 555.555.5555 format ?

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by robgpeak** [comment]
I put my phone number in the field, clicked update info, and received a notice at the top of the page that said, "Profile Has Been Updated", but it is not saving my number.  Meaning, the field is still empty.

**Comment by Dwells7583** [comment]
@robgpeak phone number will display as 555-555-5555 unless you have an entered phone number.

**Comment by robgpeak** [comment]
What I mean was I put my phone number in but it did not save

**Comment by cgladue** [comment]
ill take a look, it may not be in the code to save the phone#, but it will be soon if not.

**Comment by Dwells7583** [comment]
It is there now, It is in the code @cgladue. It should function properly when published.
