### ISSUE TITLE
Default links need to start shopping trips

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#58]
Right now the default links have the correct affiliate tracking info, but they are not logging in our shopping trip db.

**Comment by cgladue** [comment]
rob i just registered a account and visited a link under "Rewards" panel on the advertiser and it did show correctly in the user dashboard ... which advertiser did you try  that wasnt the case with ?

**Comment by robgpeak** [comment]
You know I love these screencasts...  https://screencast.com/t/ks7cUBTLn

**Comment by cgladue** [comment]
ok i got what your saying ... ill edit the destination for the main link ...

**Comment by cgladue** [comment]
main link is now pointing to the start trip redirect as well as opens in a new tab.
