### ISSUE TITLE
Load palette's from DB

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#6]
@cgladue We need a primary and an accent palette for each casino (just strings, e.g. "blue").

@Dwells7583 You're defining custom hue's, correct? Please let @cgladue know what you need for this (e.g. PrimaryTheme, PrimaryHue1, PrimaryHue2, etc.)

**Comment by cgladue** [comment]
ok so you will just need two strings passed to you for style info and one for logo ?

**Comment by Dwells7583** [comment]
@cgladue 

-  Primary palette: (ie. light-blue)
 - default: 
 - hue-1:
 - hue 2:
 - hue-3:

Accent palette: (ie. orange)
 - default:
- hue-1:
- hue-2:
- hue-3:

If you want to present the user with a default option these would be a good palette setting to use.
              'default': '700',
                'hue-1': '500',
                'hue-2': '900',
                'hue-3': 'A700',

  Accent:
                'default': 'A200',
                'hue-1': 'A100',
                'hue-2': 'A400',
                'hue-3': 'A700',

**Comment by cgladue** [comment]
can this just be stored as a comma seperated list of values instead of
storing 4 seperate values ?



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=chadgladue@gmail.com&idSignature=22>



Chad Gladue
*DevNull Technology, LLC*

**Comment by Dwells7583** [comment]
You can store it however you would like on the back end, as long as thats what we are presented with on the front end.

**Comment by cgladue** [comment]
i have completed this, i am serializing this object into the partner property of the viewbag, update your project and take a look at HomeController, as well as _Layout to see what i did.  This object is stored on each partner record in the DB 

 {
	"primary": 
	{
		"main" : "700",
		"hue1" : "500",
		"hue2" : "900",
		"hue3" : "A700",
	},
	"accent": 
	{
		"main" : "A200",
		"hue1" : "A100",
		"hue2" : "A400",
		"hue3" : "A700",
	}
}

**Comment by ChrisASearles** [comment]
This is working but the implementation is being touched up in #133. For now, you should be able to navigate to different partners and have the proper theme loaded.

**Comment by cgladue** [comment]
published

**Comment by robgpeak** [comment]
While I like it, I would still like the Shop Now to be our orange.

Like they do on the Book a Room link...
<img width="696" alt="screen shot 2017-05-25 at 11 57 37 am" src="https://cloud.githubusercontent.com/assets/28393235/26458512/76a35bc4-4141-11e7-91d8-61ff5a42d822.png">

**Comment by ChrisASearles** [comment]
@robgpeak I selected a palette for DD based on their website but you're free to change the accent color of that palette to anything you'd like (you can also change the default theme, and this is also how any future partners will be configured).

To change the color scheme, visit the partners page https://shop.complinks.co/admindashboard/partners click 'Actions -> Edit', scroll to the bottom box that says "Style Info" and change the name of the Accent from "blue-grey" to any color palette of your choice from this list: https://material.io/color/#!/?view.left=0&view.right=0

The palette we use for the CL default accent color is 'deep-orange'. Note that all letters are lowercase and the two word color palette's should be separated with a hyphen, not a space when used on the site.
