### ISSUE TITLE
Edit Advertiser successful but remain on the same edit page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#61]
@ChrisASearles If it is an easy fix for Chad...  After the record for the advertiser is "saved" the page it reads "Success! Advertiser Saved Successfully", but it refreshes back to the list view of all the advertisers, and I would rather that tab remains where it was, but the "save" button would be grayed out, as long as nothing has changed on the page.  [When in the list view of all the advertisers, and you click on "Action>Edit Advertiser" it purposefully opens in a new tab.]

**Comment by cgladue** [comment]
i can reload back to the same record, but greying out the save button is extra work, but wouldnt hurt if you press it 10 times.... i can change this behavior.

**Comment by robgpeak** [comment]
Ok reload back to the same record with the message it was successfully updated, and leave it at that, no heating out needed for now, but it should be a back, back burner thing.

**Comment by ChrisASearles** [comment]
This is a low priority item, removing from the current milestone.
