### ISSUE TITLE
Some commission percentages are including decimals

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#62]
There are many examples and you can see them when you look at http://shop.complinks.co/admindashboard/advertisers in list view

**Comment by cgladue** [comment]
this is due to the new way of pulling default comission %, the new field has decimals .. ill remove them going forward...

**Comment by cgladue** [comment]
If you take a look at the Activity Feed, you will see the Engine is currently reprocessing all the advertisers now and correcting the commission rates...
