### ISSUE TITLE
Engineer the points exchange system

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#64]
I know we've spoken about how we might build an API for those casino partners who don't have a way to tap into their points system for the purposes of making the exchange of points seamless, but I would like to see either a mock up of how it would work, or a written description so we can start building and testing the system internally.  We would obviously do the same (create a mock up or document), for those casino partners with an API already in place...

**Comment by cgladue** [comment]
Take a look at this document...
[Everywhere Points Redemption Process.pdf](https://github.com/ChrisASearles/CompLinks/files/987277/Everywhere.Points.Redemption.Process.pdf)

**Comment by robgpeak** [comment]
OK looks good.  And I suppose if there is an API on their side, it's even easier.

**Comment by cgladue** [comment]
depends how good their API is, but as well as the API is straightforward then yes.

**Comment by ChrisASearles** [comment]
Hey @cgladue I took a look at the process outlined in the doc and looks great, has the whole thing been implemented on both the user and casino side?

**Comment by cgladue** [comment]
yes, the links referenced are live and the process does work, except i have not added the email notifications yet

**Comment by ChrisASearles** [comment]
Awesome. I'm going to add those as a separate ticket under the new Stretch Goals milestone.
