### ISSUE TITLE
Adding a checkbox to Advertisers/Links page

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#65]
I wanted to see what it would take programmatically to have a checkbox in the list view of the Advertisers/Links page to be checked or unchecked, and that would determine whether or not the link was active (visible on the site), or not.  Hey look, I found another one of those videos:) https://screencast.com/t/YZYt7HR8

**Comment by ChrisASearles** [comment]
Would definitely improve the page's usability, moving this into the Stretch Goal milestone to change add a 'Save' button to the page and change the True/False string to a checkbox that is checked/unchecked, Save button would update that field for all entries in the list.

**Comment by ChrisASearles** [comment]
As referenced by @robgpeak in #67 

"What would it take to be able to edit the Link directly in the http://shop.complinks.co/admindashboard/advertisers/links/6785 list view instead of having to drill into the edit window? It would make life a shitload easier."

**Comment by robgpeak** [comment]
This would also improve the functionality of the http://shop.complinks.co/admindashboard/rewards/redemptions page, where we might have hundreds of redemption requests in there that a casino operator would need to go in and manually mark as a completed transaction.

**Comment by cgladue** [comment]
@robgpeak Now there is a bulk actions dropdown on the links page to activate/deactivate multiple links at once.

**Comment by robgpeak** [comment]
That's great.  Just thinking out loud, is there a way we can remove them completely from view?  Would that cause a problem in the way your system pulls this info from cj/ls?  Would make it a lot cleaner and easier to navigate.

**Comment by cgladue** [comment]
@robgpeak i could remove them completely from view if they are expired, but if i remove the deactivated links then if you wanted to activate them at some future point they wouldnt be there to activate...

**Comment by robgpeak** [comment]
I just saw the check boxes, (image below), and I gotta admit, I felt blood flow to my nether region.

Maybe I jumped the gun as to its working functionality, particularly because it was not assigned to me to review yet, but I was a bit excited...  Anyway, as you can see by the image it did not work yet. 

Also, will there be a "check box" in cell A:1 (meaning the column header for all the check boxes), whereby if checked, it would select all the visible check boxes in that column?
<img width="885" alt="screen shot 2017-05-31 at 1 57 09 pm" src="https://cloud.githubusercontent.com/assets/28393235/26646527/fda345cc-4609-11e7-810d-3dcb658b8a27.png">

**Comment by cgladue** [comment]
get your juices flowing again, i believe its fixed now.  i believe i can add a "all" checkbox yes.

**Comment by robgpeak** [comment]
Cool.  It does work, but I don;t know if it is by design, but the selection of check boxes does not work the way normal check boxes work...  Meaning, in the way you have it set up, it is still necessary to hold down the shift or command key, wherein normally, that is not the case in most other check box scenarios.

**Comment by cgladue** [comment]
i think thats just the way the table works, you can CTRL click and CTRL+SHIFT click too

**Comment by robgpeak** [comment]
Yeah, I get ya.  I suppose it's just how this particular table works, but it is not standard UX.  Like for example the table at the bottom right hand side of this page http://keenthemes.com/preview/metronic/theme/admin_1/table_bootstrap.html which is where I though we got ours from?  Meaning we are using this exact theme, you can select multiple check boxes without holding any keys.

**Comment by cgladue** [comment]
ok i didnt see that example, ill take a look to see if i can adapt it to fit in ...

**Comment by robgpeak** [comment]
Cool.  And if it does work, let's replicate that functionality on the Activity Stream pages as well.

**Comment by robgpeak** [comment]
@cgladue before I close this, I know we spoke about adding the "all" check box feature, and the ability to select multiple records (rows), without having to hold Shift and/or Control...  Yeah or Nay?

**Comment by cgladue** [comment]
yea what was the link to the template page that showed that functionality again ?

**Comment by robgpeak** [comment]
It's in this same thread from a post I made two days ago...

Like for example the table at the bottom right hand side of this page http://keenthemes.com/preview/metronic/theme/admin_1/table_bootstrap.html

**Comment by cgladue** [comment]
Look at it now rob, ... the example you gave me tho does not have the shift-Click functionality but it does have the select all deselect all and you can then click individually.

**Comment by robgpeak** [comment]
Cool.  Much better this way.  Instead of starting a whole new issue, can you please change the number of entries in the dropdown on the page https://shop.complinks.co/admindashboard/advertisers/links to "20, 50, 100, all"

**Comment by cgladue** [comment]
All set, changed

**Comment by robgpeak** [comment]
👍

Thanks,

Rob

**Sent from my phone
