### ISSUE TITLE
Grabbing "Example of link" text instead of link name from LinkShare

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#67]
@cgladue we need to grab the "Example of Link" text field instead of "Link Name" https://screencast.com/t/cwxntbhm8uk

**Comment by robgpeak** [comment]
As a follow up, can we make this retroactive?  Meaning, we would need to change all the current ones that are using "Link Name" as the description to show the "Example of link".

**Comment by cgladue** [comment]
yes i will expire all the links for linkshare now and force the engine to re-update the descriptions.

**Comment by cgladue** [comment]
the engine is running right now, as an example you should see the new link descriptions here and slowly trickle in over the next several hours.

http://shop.complinks.co/admindashboard/advertisers/links/6785

**Comment by robgpeak** [comment]
Great.  Thanks.  One quick thing.  Can you make the description box on this page http://shop.complinks.co/admindashboard/advertisers/editLink/13738 bigger.  Does not have to be as big as the description box on the main edit advertiser page, but at lease big enough to see 250 characters or so...

**Comment by cgladue** [comment]
All set, added Start Date and Expires After dates as well just in case you had another screencast queued up ...

**Comment by robgpeak** [comment]
LOL on the preemptive screencast.  A couple things (no screencast needed:).  

1. What would it take to be able to edit the Link directly in the http://shop.complinks.co/admindashboard/advertisers/links/6785 list view instead of having to drill into the edit window?  It would make life a shitload easier.

2. If that was possible, it would also make sense to have a simple check box in the "Active' column to be on or off.  Again, making it a ton easier to manage 20 to 50 deals and promos times 900+ advertisers.

So I would think it might work more like the edit advertiser page, where we could make the edit changes I described above, and then click save to save the records.

**Comment by ChrisASearles** [comment]
@robgpeak you had already added the second item on that list as #65 which is assigned into the stretch goals milestone for this release. I'll add your item 1 in that same issue as they would go hand-in-hand.
