### ISSUE TITLE
Registration form changes

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#69]
Update registration form to remove first and last name and add reCAPTCHA verification (as per @robgpeak comments on #18).

**Comment by cgladue** [comment]
Done

**Comment by robgpeak** [comment]
Hey Chad, do you know why it's not behaving the same as the one on https://complinks.co/contact-us/?  Meaning, when I go to the one on the page above on chrome on my phone, I don't have to pick any portions of pictures it asks you to like when I go to the one on the registration screen, when I just use the default internet browser on my Android phone...?

**Comment by robgpeak** [comment]
Nevermind, I just went to the registration page in a chrome incognito window on my phone, and the image puzzle popped up...  No worries.  Maybe it's random.

**Comment by cgladue** [comment]
yea thats part of how it figures out if your a robot or not, sometimes it will prompt you for input sometimes it wont.
