### ISSUE TITLE
Expanded "How it works" section on homepage

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#7]

**Comment by Dwells7583** [comment]
@robgpeak Is this the only content you want on the How it Works page? Please send email me any copy or images you want on this page. 

 https://app.moqups.com/robg/QSDVx2F07W/edit/page/adfd762e6

**Comment by robgpeak** [comment]
Derek, first I was hoping to have the functionality that I described in comment number 3 on the page https://app.moqups.com/robg/QSDVx2F07W/edit/page/a9762b57c whereby the page expands to show the "How it works" container section, while still remaining on the same page.

Then as far as the content, I was hoping my web design and digital marketing company Searles Media could use some of its creative marketing kung-fu to dress up the imagery and put some captivating punchlines to engage end users :) 👍

**Comment by Dwells7583** [comment]
@robgpeak Ok. You got it. Thanks.

**Comment by ChrisASearles** [comment]
@robgpeak when we discussed this in our meeting with @morganpeak we talked about doing it on a separate page that we could link to from other areas if/when necessary. I saw that moqup but thought it was old as you had broken it out into it's own page after our discussion, no?

**Comment by robgpeak** [comment]
I recall the conversation being the About the Program page being separate, not the How it Works

**Comment by robgpeak** [comment]
And someone would get to that About the Program page from the Learn More button on the hero image when someone is logged in.  And I would even like to see a link in the main nav to About the Program.  https://app.moqups.com/robg/QSDVx2F07W/edit/page/acd4932ab

**Comment by ChrisASearles** [comment]
@robgpeak This solution doesn't consider a mobile device. We were going to link to a new page because, while the mock up you did would work fine on a desktop monitor, I'm having a hard time envisioning the way you see this working on a small screen.

**Comment by ChrisASearles** [comment]
@robgpeak I'm also not seeing a logical difference between "About the Program" and "How it Works." As an end user, I wouldn't understand a distinction (I would expect the same content on both), and looking at the content, there doesn't seem to be much of a distinction. What's the reason for creating two pages when one seems to be sufficient?

**Comment by robgpeak** [comment]
Point taken on the solution not working. But the idea behind two different pages on about the program and how it works, the first is an overview of the technical of how it works, and the second is explaining the benefits of why some would continue to use it.  I know I wrote it somewhere in an issue (the reasoning), but I can't find it...

**Comment by ChrisASearles** [comment]
So  for now you're good with a new page for this @robgpeak ?

**Comment by robgpeak** [comment]
Yes, but remember there are 2 different reasons and thoughts for sending people to two different pages.  One is "How It Works" kind of a light non technical this is what happens... And how it works.  And the other is when you are logged in, "About the Program", shows the user why he should use it, and the benefits of doing so... Value Propositions...

**Comment by Dwells7583** [comment]
How it Works Page added.

**Comment by Dwells7583** [comment]
/how-it-works 
@robgpeak Adding learn more links under the 3 main how it work features on the homage, correct?

**Comment by robgpeak** [comment]
Not three separate links, just one in the call out box underneath that with
the image background that's there already

Thanks,

Rob

**Sent from my phone

On May 26, 2017 11:24 AM, "Derek Wells" <notifications@github.com> wrote:

/how-it-works
@robgpeak <https://github.com/robgpeak> Adding learn more links under the 3
main how it work features on the homage, correct?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisASearles/CompLinks/issues/7#issuecomment-304311797>,
or mute the thread

**Comment by robgpeak** [comment]
So to clarify, I meant just changing this link, which becomes Learn More when someone is logged in.
![screenshot_2017-05-26-11-31-50](https://cloud.githubusercontent.com/assets/28393235/26501362/6ba6b5f6-4207-11e7-9c10-a826a7924ace.png)

**Comment by Dwells7583** [comment]
My only question is, why wouldn't you want people who are not members to learn how it works? I would think this information that non members should see.

**Comment by cgladue** [comment]
@robgpeak @Dwells7583  i just published the changes

**Comment by Dwells7583** [comment]
@robgpeak @cgladue styles are not updated. so the content is there, but missing updated styles.

**Comment by cgladue** [comment]
it looked ok to me, probbally since i havent visited the site today let me clear the cloudflare cache again

**Comment by cgladue** [comment]
@Dwells7583 how about now ?

**Comment by robgpeak** [comment]
I can see it now. I have not gone over it with a fine-tooth comb. But I am sure it's fine for now. Let's move on to more important issues like the user information pages. Meaning their shopping trips and my account section to make it look more like the front end I am dictating this into my phone standing at Home Depot fun

**Comment by Dwells7583** [comment]
@cgladue looks good, I just added the link to the homepage you can publish that too.

**Comment by cgladue** [comment]
i would recommend that we move the userdashboard into the front end and leave the partner and admin dashboards in the backend, then everything the user can see and do looks almost identical, as for the partners and admins they wont need to have 100% congruity and their "dashboards" can stay the way they are...

**Comment by robgpeak** [comment]
I agree 100% with Chad's last statement

**Comment by cgladue** [comment]
@robgpeak pending your review

**Comment by robgpeak** [comment]
Sorry, reopened by accident.  This issue should be closed.
