### ISSUE TITLE
Changing the names of some advertisers

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#75]
@cgladue I wanted to bring to your attention that @morganpeak and I have been going through an changing some of the names of some of the advertisers, from what they may have been in that the original loading of them from those json files.  Some of them had additional BS in the Advertiser Name field.  (i.e. ECMD-Save on Early Childhood Furniture & Equipment!, Encore Software - Broderbund, Punch, Hoyle &amp; more, eReleases Press Release Distribution, etc.)

We would change them to ECMD, Encore Software and eReleases respectively...

The reason I bring it up is that we had made some changes yesterday, that were seemingly rolled back this morning.  One in particular was "7 For All Mankind, a division of VF Contemporary Brands" which was the original name in the json file, but yesterday I changed it to "7 For All Mankind" but today it was back to the full name.  Morgan has since changed it back.

But it got me thinking that maybe something on your end when you regrab some data, it overwrites the name back to the original.  If that is the case, please don't let that happen.  Thanks.

**Comment by cgladue** [comment]
yes on linkshare for some reason i was always setting the advertiser name to whatever linkshare gave me, i have removed that and it will no longer overwrite the name sorry!
