### ISSUE TITLE
MailChimp Integration

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#81]
Users should be presented with an option upon registration to sign up for special offers and updates (@robgpeak do you want to work out the specific text?). Checking that box will add the user to the CL MailChimp account.

**Comment by robgpeak** [comment]
I just looked at the T&Cs for ebates, and they have this paragraph in theirs:

Receiving Communications from Ebates

By signing up for membership at Ebates, you agree to receive communications that are account and membership related (e.g., that we've added money to your account, that we are mailing you a check on a certain date, etc.) as well as periodic shopping-related emails that highlight coupons & special deals that are available to Ebates Members. You can opt-out of receiving emails that are not account-related by either (i) visiting your account page and clicking on the Subscriptions link, or (ii) following the unsubscribe link on any of the emails. Since we need to communicate account information with you in order to operate our service, you cannot unsubscribe from account information emails. But rest assured that we don't send account emails unnecessarily. If you do not wish ever to hear from Ebates, even if just to hear that we awarded you Cash Back, you can close your account by contacting Ebates' customer service department.

Then at the bottom of every email correspondence, of course we will have the mandatory unsubscribe link, and additionally, a user can opt out on their My Account page in the communication preferences section. https://app.moqups.com/robg/QSDVx2F07W/edit/page/af53607d3

So the short answer is, I will add a communications section to our T&Cs to cover this.

**Comment by robgpeak** [comment]
The T&Cs have been revised and can be found here.  https://docs.google.com/document/d/14rLnCIh0Yj_TzFABhFDSDWMdE0M7RGY_swouazW9_pc/edit?usp=sharing

Please note there are a couple of URL references on this document (you will see the comments next to them, and they are highlighted for easy reference), that must dynamically replace the "www" with the name of the subdomain that is serving this document.  So if someone reading this document from doverdowns.complinks.co, that's what they would see.  If they came from foxwoods.complinks.co, that would be the URL they see in those T&Cs

**Comment by robgpeak** [comment]
@cgladue I know @ChrisASearles is busy with making the front end site look good on iphone/safari, and I wanted to start (or continue) this thread with how we are going to import/sync the user data into MailChip from our db.

I was just in https://shop.complinks.co/admindashboard/users and downloaded the csv file just to see all the fields, and I think they look great, and are exactly what we need.  Having said that, we need to figure out the "opt-out" feature, so our db and the Mailchimp db are in sync.

I just set you up as an admin in MailChimp...

Please let me know if you need to talk or discuss this.

**Comment by robgpeak** [comment]
As a follow up to this, It is important that for the purposes of building the email lists for each casino partner, we have the lists segmented by the “Partner” on our side first, before we even sync it with Mail Chimp, so there is no confusion of list segmentation within MailChimp.

I have set up two separate lists in MailChimp to get us started, and created to mock templates.  One for Shop - CompLinks and the other for Dover Downs - CompLinks.  Obviously as we bring on new partners, we would create separate lists and templates.

**Comment by cgladue** [comment]
@robgpeak @morganpeak, i have completed the integration of mailchimp, when a new user signs up if the list for that subdomain does not exist on mailchimp the site will create it for you automatically, and add all the fields you created to the list.  It will then add the user and populate those fields with the users data.  If the user then goes into their profile and adds/updates or removes information in their profile it will update their mailchimp record accordingly.  you can fully test it now, just be aware that mailchimp sometimes takes 5-10 mins for the changes to show up.

**Comment by robgpeak** [comment]
works great @cgladue thanks.  Now we just need a way to allow the end user to change their email preferences in our back end (the user's My Account section) and have it sync with MailChimp, and vice versa.  When someone unsubscribes from a link at the bottom of the email, it should show up as "opted-out" in our back end.

**Comment by robgpeak** [comment]
Hey @cgladue Please look at these to images and see if I am putting the correct mailchip data in the correct place in cloudflare


![uploads/7592f9a6-6220-4f12-a4ab-ca54dd47987c/Screen Shot 2017-06-16 at 2.31.30 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7592f9a6-6220-4f12-a4ab-ca54dd47987c%2FScreen+Shot+2017-06-16+at+2.31.30+PM.png)


![uploads/ad58f222-8b6c-428b-8c60-26d9c74ded2d/Screen Shot 2017-06-16 at 2.31.39 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fad58f222-8b6c-428b-8c60-26d9c74ded2d%2FScreen+Shot+2017-06-16+at+2.31.39+PM.png)

**Comment by robgpeak** [comment]
Hi @cgladue I wanted to start messing around with Mailchimp to streamline and automate the process, but I wanted to see if you can look at my last post and see if the settings are correct?

**Comment by cgladue** [comment]
@robgpeak yes it appears you did exactly as they have asked...

**Comment by cgladue** [comment]
@robgpeak i have also disabled the email that gets sent from complinks site when someone registers, so they should only get the mailchimp email now.

**Comment by robgpeak** [comment]
Ah, OK, cool on both fronts.  Seems as if I forgot to go back to mailchimp and click the Authenticate button.  All good on that end now.  I will run some tests.  Thanks.

**Comment by robgpeak** [comment]
@cgladue I think we might need some adjustment to this process for better UX.  As it stands now, if I go into the My Account section and check the box to "Receive Email" I see the message at the top of the screen saying "Please check your email..." I would like to add the line, "...This may take a few minutes."  (actually, I checked the checkbox on my account ~20 minutes ago, and have NOT received an email from mailchimp...  Am I doing something wrong?  Maybe it's not set up yet?)


![uploads/86f17a03-ba09-47df-8322-03e17d8c7ee6/Screen Shot 2017-06-19 at 12.19.56 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F86f17a03-ba09-47df-8322-03e17d8c7ee6%2FScreen+Shot+2017-06-19+at+12.19.56+PM.png)

**Comment by robgpeak** [comment]
Also, from a UX perspective, if it is possible (and easy) to have the My Account section in the image shown above say something like "Pending" next to "Receive Email" which would mean, the user would see that they requested a change, but it has not been completed yet until the email has been received and the link was clicked...

**Comment by cgladue** [comment]
i had to remove all the lists that were imported because of the permissions on the record it only worked when the site created the list itself... so you dont have a record on the mailchimp list probbally, i will add something in there that will add you to the list if you dont exist already if you opt in ... which is special in this case because when you unsubscribe from the list, you still stay on the list in mailchimp, only the status is unsubscribed, so its a product of me deleting the list entirely ... give me a few minutes and ill change that

**Comment by robgpeak** [comment]
understood

**Comment by cgladue** [comment]
ok i have made the change, next time you "update" your profile it should add you to mailchimp because it detected you arent on the list.

**Comment by robgpeak** [comment]
OK.  Just updated My Account to "Receive Email", let's see how long it takes for me to receive the email to click the link...

**Comment by cgladue** [comment]
i see you in the mailchimp API now, so the email should of gone out...

`"members": [
        {
            "id": "333c8eb1a55660d8c0d8aeef4bf09c79",
            "email_address": "robg@peakmarketing.com",
            "unique_email_id": "adf5321275",
            "email_type": "html",
            "status": "pending",
            "merge_fields": {
                "FNAME": "Rob",
                "LNAME": "Gallo",
                "MMERGE3": 1,
                "MMERGE8": "",
                "MMERGE9": {
                    "addr1": "123 Main st. apt #2",
                    "addr2": "",
                    "city": "anytown",
                    "state": "ny",
                    "zip": "11223",
                    "country": "US"
                }
            },
            "stats": {
                "avg_open_rate": 0,
                "avg_click_rate": 0
            },
            "ip_signup": "52.14.115.37",
            "timestamp_signup": "2017-06-19T16:58:53+00:00",
            "ip_opt": "",
            "timestamp_opt": "",
            "member_rating": 2,
            "last_changed": "2017-06-19T16:58:53+00:00",
            "language": "",
            "vip": false,
            "email_client": "",
            "location": {
                "latitude": 0,
                "longitude": 0,
                "gmtoff": 0,
                "dstoff": 0,
                "country_code": "",
                "timezone": ""
            },
            "list_id": "82b2052129",

**Comment by cgladue** [comment]
Looks like you just subscribed.

"members": [
        {
            "id": "333c8eb1a55660d8c0d8aeef4bf09c79",
            "email_address": "robg@peakmarketing.com",
            "unique_email_id": "adf5321275",
            "email_type": "html",
            **"status": "subscribed",**
            "merge_fields": {
                "FNAME": "Rob",
                "LNAME": "Gallo",
                "MMERGE3": 1,
                "MMERGE8": "",
                "MMERGE9": {
                    "addr1": "123 Main st. apt #2",
                    "addr2": "",
                    "city": "anytown",
                    "state": "ny",
                    "zip": "11223",
                    "country": "US"

**Comment by cgladue** [comment]
@robgpeak did you change the list name from shop.complinks.co ?  that is kind of needed to match the subdomain name so that the system can locate the proper list to use for each subdomain automatically, therefore not requireing any manual work from CL staff to function.

**Comment by robgpeak** [comment]
I did.  Trying to figure out how to eliminate the "manage your preferences" button on the page 

<img width="925" alt="screen shot 2017-06-19 at 1 11 56 pm" src="https://user-images.githubusercontent.com/28393235/27296973-0c16591e-54f1-11e7-8bca-445fbad0bfa7.png">

I went to the "Signup Forms" section and in the dropdown, clicked on "Confirmation thank you page" and I can edit the content of the body of the page, but I can't seem to be able to remove the manage your preferences link/button.  I would rather the only link be to, "Continue to our website"

<img width="952" alt="screen shot 2017-06-19 at 1 23 27 pm" src="https://user-images.githubusercontent.com/28393235/27297499-0f15c4ae-54f3-11e7-82ef-81320654c260.png">

**Comment by robgpeak** [comment]
Yes I did just change the name because it shows up on the confirmation page, and it does not look right.  We might have to think of a work around...

**Comment by cgladue** [comment]
hmm wonder if its part of the spam legislation to have to provide a user the ability to manage their preferences ?

do you think you can change the list name back to shop.complinks.co otherwise the integration will be broken since it wont know what list to use

**Comment by robgpeak** [comment]
This is how the email message shows up to confirm when the name of the list is the subdomain, and it looks pretty lame to an end user...

<img width="560" alt="screen shot 2017-06-19 at 1 33 03 pm" src="https://user-images.githubusercontent.com/28393235/27297729-119891b0-54f4-11e7-8222-da5c5c92def8.png">

What is we use the List ID? (shown over on the right hand side of this image)

<img width="1098" alt="screen shot 2017-06-19 at 1 33 42 pm" src="https://user-images.githubusercontent.com/28393235/27297745-239db52a-54f4-11e7-8f0d-c1d336ce6364.png">

**Comment by robgpeak** [comment]
Meaning, would it be possible to use that exclusively instead of the list name?

**Comment by robgpeak** [comment]
Another thing, does eliminating the SES email mean that we are NOT able to check our db to see if that email address already exists?  Meaning, we still don't want to allow people to have multiple accounts on the same subdomain.

**Comment by cgladue** [comment]
no, because if the program even gets that far where it would of sent the email then the user registration was already successful, if the email already existed then it would of failed before that point.

**Comment by cgladue** [comment]
@robgpeak what if instead of the subdomain name i looked for a list named "<Partner Name> Rewards Everywhere"  so for dover downs i would expect to see a list (and create it if it didnt exist) 'Capital Club® Rewards Everywhere'

**Comment by robgpeak** [comment]
I suppose that would work.  The idea is that the naming convention of the lists would be {Casino_Partner_Name} Rewards Everywhere.  So "CompLinks™ Rewards Everywhere" would be the subdomain shop.complinks.co, 'Capital Club® Rewards Everywhere' would be doverdowns.complinks.co, 'Foxwoods® Rewards Everywhere' would be foxwoods.complinks.co, etc.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/27298425-8ecf5e14-54f6-11e7-9db6-aec922227f53.png)

it would be based on this column .. so it would be the NAME colum plus "Rewards Everywhere" .. is that ok ?

**Comment by robgpeak** [comment]
yes

**Comment by cgladue** [comment]
ok, the list names now will follow the above naming convention and shouldn't be manually changed.

**Comment by robgpeak** [comment]
ok

**Comment by robgpeak** [comment]
So I just signed up for another account at shop.complinks.co using the same email address I had used before (robg@peakmarketing.com) and it let me sign up.

Then the mailchimp opt-in confirmation email I received was NOT the one that was in the back end of mailchimp.  Confusing...  https://screencast.com/t/th3uM6QqO

**Comment by cgladue** [comment]
the signup is expected because originally i was validating only the user part of the email address (the part before the @ sign) to be unique and recently i am now validating the entire address, so it would be different then the first account you registered, now if you tried a third time you should get a blank white page (due to an error that chris and derek caused when they modified the register screen) there exists an issue for that currently assigned to them.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/27299837-a038334c-54fb-11e7-852c-7cc900e55519.png)

you can see the old format usernames created by the site up till last week,  the two accounts you just registered you can see the new format where the username takes into account th eentire email address, not just the user portion.

**Comment by robgpeak** [comment]
Gotcha.  Just tried it, and it works as expected.  Meaning it comes back with a white page, that Chris and Derek would just put something there that says, "It looks like you already have an account registered with that email address, please log in...  If you forgot your password, click here..."

**Comment by robgpeak** [comment]
@cgladue as a follow up to an earlier post on this thread, we need to figure out a way to eliminate the  "manage your preferences" button on the confirmation thank you page.

First off, it does not work as expected.  Meaning, on my account 100051 I updated my first and last name using the mail chimp button on the confirmation page, and it DID update my name in mail chimp, but it did NOT pass through to our db, and that was yesterday.

Second, I would rather have all the updates happen on our end, and we pass it to mail chimp.  This way, if we ever moved to another email service provider, the change would be seamless to the end user.

Additionally, it gives us more flexibility if the user is on our site.

**Comment by cgladue** [comment]
it should update our DB if they update it in mailchimp, if the list is new i have to configure one thing that there is no way to configure problematically, what acct# did you to the update on ?

**Comment by robgpeak** [comment]
#100051 dd4_test@peakmarketing.com  But before we go through all of this anyway, I think we might want to have a discussion about the total amount of data we are going to collect.  We heard back from Dover Downs, and they had concerns about us collecting any more user information.  This might have to start in another thread, but again, I would like to have a verbal discussion with you.  Maybe you can call me when you are on your way home?

**Comment by ChrisASearles** [comment]
@robgpeak is this still in review or are we good on this?

**Comment by ChrisASearles** [comment]
Picking up the conversation where we left off on #217 ... I'll let you and @robgpeak make the call. From a CANSPAM compliance standpoint if you have the ability to update that field in via the MailChimp API you'd definitely be ok doing so based on that sequence of events of someone actually ticking that box on and saving. Not sure if that's how you're planning on confirming email addresses now though and that's why you're hesitant to do so, so whatever you guys end up deciding should be alright,

I might just make that message we spit back to the user a little more descriptive that their preference has been noted but they won't see the field updated in their account page until they click the confirm link? I also didn't get another email sent to me when I did that which could be a little confusing if they didn't get or didn't see the email that was sent the first time around.

**Comment by robgpeak** [comment]
I will polish up the process and make sure another email comes back to the user to confirm their preference and such.

**Comment by cgladue** [comment]
Did you happen to change the list name or merge fields ?  That would cause issues on my end.

**Comment by robgpeak** [comment]
@ChrisASearles MailChimp now sends a confirmation email.  The last message from @cgladue in this thread makes me think this issue should be opened again, but that's up to you.

**Comment by cgladue** [comment]
@robgpeak the errors could of been caused because you removed some of the merge fields from the lists, which means the site sending extra fields and mailchimp may not accept the transaction.  After our discussion i will update my code to reflect the decisions made.
