### ISSUE TITLE
Starts On and Expires After Dates for Deal and Promotions Links not correct

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#82]
@cgladue This screen cast (https://screencast.com/t/XsA3L2k0o) highlights two separate issues, but for now I will put it in as one, and we will break off another task for the second one.  The issue is that the expiration dates for the new links for advertisers that you are getting from the API and showing up in the Activity Stream, and then ultimately on the site, are NOT picking up the proper Starts On and Expires After dates and times.  

For example, our link http://shop.complinks.co/admindashboard/advertisers/editLink/24385 shows 1/1/2017 start and 12/31/2020 end, but in CJ's back end, (you can see it here
https://members.cj.com/member/4337795/publisher/links/search/#!advertiserIds=4421352 and it's easier to find by searching for "J3"), it shows "Schedule: 13-May-2017 9:00 PM to 20-May-2017 8:59 PM"

**Comment by cgladue** [comment]
there was an error in the code that pulled this field in the API..  good job finding it and shame on me for creating it :\
