### ISSUE TITLE
Advertiser Link not going to the intended page on the advertiser's site

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#83]
@cgladue seemingly you are using the proper offer ID in the link, but I just noticed this link was not going to the correct landing page on the advertiser's site. (https://screencast.com/t/rMm5Z3DwgYT) I will look for other examples on both cj and ls and let you know if I find anything else.

**Comment by cgladue** [comment]
Damnit rob, you always find the bugs!

there was a but on the trip start redirect, i have corrected it and the page loads correctly now.
