### ISSUE TITLE
Forgot password email

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#85]
Submitted a forgot password request and never received an email.

**Comment by cgladue** [comment]
Did you do this while running locally or from shop.complinks.co?  And which user ?

**Comment by ChrisASearles** [comment]
Local. Assuming that's my issue, security settings within Amazon?

**Comment by cgladue** [comment]
no, you only registered for an account on shop.complinks.co, when you run it locally it is technically a different tenant so you cannot login on the localhost:58149 site with your chris.searles@searlesgraphics.com account you registered on shop.complinks.co.  And the same goes for forgot password, it will silently return the same response whether or not an account exists for security reasons.  so if you want to test it then use the shop.complinks.co/account/forgotpassword page or register a second account while running locally and then do it from there.
