### ISSUE TITLE
Adjustments to "Store Box"

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#86]
We need to make a couple of adjustments to the "Store Box" container content, and it's functionality.

1. The store box should look like this:

![uploads/9673eba4-5ae4-4e84-9796-b435f180f6cf/Screen Shot 2017-05-12 at 11.15.19 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9673eba4-5ae4-4e84-9796-b435f180f6cf%2FScreen+Shot+2017-05-12+at+11.15.19+AM.png)

a. The logo spacing at the top that you have now needs to be increased to create more padding from the top of the container.

b. The logo itself should include the style tag: style="max-height:40px; width:150px;"

c. There should be no spaces between the words "Points and the /, and between the / and $"  It should look like this "...Points/$"

d. We need to include the copy "See All <Advertiser_Name> Deals" as it is shown in the mock up.

f. The functionality of the Store Box is, Anywhere on the box that is clicked takes the user to the store index page EXCEPT the "Shop Now" button will initiate a shopping trip to that advertisers store through our default link/URL.

e. The overall size of the store container should have a minimum height restriction.  Meaning it should NOT be allowed to reduce beyond the height that stops the Logo, Points/$, the See All <Advertiser_Name> Deals, and the button from appearing legible on a mobile device.  As it is now, it is all scrunched up and illegible.  There still need to be ample buffering between all the internal elements mentioned above, and the interior borders of the container.  This hold true for ALL the containers and their content throughout the site.

g. The line of text "See All <Advertiser_Name> Deals" SHOULD be allowed to wrap, so this need to be take into consideration when assigning spacing limits between the elements and the minimum height restriction on the containers.  They should all be uniformed.

I think that just about covers it.

**Comment by ChrisASearles** [comment]
Rob, these are all still in development under a number of different issue numbers (#22 #23 #25 to name a few). We're working on this actively and will let you know when the version you're seeing is something we need feedback on.
