### ISSUE TITLE
Activity Stream updates

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#88]
@cgladue as you suggested, I put together a mock of the Activity Stream.  Please have a look at https://app.moqups.com/robg/QSDVx2F07W/edit/page/af439bb18 and read the yellow sticky notes on the page first, and then the corresponding comments.  This is a low priority, but I know you like to "code to relax", so maybe this one can put you to sleep when you have nothing else to do:)

**Comment by cgladue** [comment]
lol, i dont think ive ever heard that before, but i suppose it has some
basis in reality.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=chadgladue@gmail.com&idSignature=22>



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
That was almost verbatim of what you said when we first spoke.  LOL

**Comment by robgpeak** [comment]
As a follow up to this Chad, I know it's going to take some work to think about the check boxes and batch processing, but in the mock up, Sticky note (2) about adding the Network ID column, that seems like it should not be to difficult, yes?

**Comment by cgladue** [comment]
network ID isnt in the table currently, but if you need it then it could be added, but in the future depending on the type of activity it may not always be filled in (redemption, etc)

**Comment by robgpeak** [comment]
Chad wrote "on a side note, you can archive the activity stream now, just select the row by clicking on it, you can shift click to select multiple or ctrl click like usual to select 1 row at a time."

I was able to get one record at a time to archive, but it did not work when I selected multiple records.

**Comment by cgladue** [comment]
hmm, ok let me look into it again

**Comment by robgpeak** [comment]
I think it would make a lot of sense to include the network ID in the table, especially since we change names of advertisers.  Additionally, I would leave the record ID column visible all the time.  It is useful to see.

**Comment by cgladue** [comment]
how about now @robgpeak

**Comment by robgpeak** [comment]
That seems to have worked.  Is it possible to have the same functionality on all the "views"?  Meaning, even if I am in one of the other "tabs", I should still be able to archive records.  As it is now, I can't even archive one by itself.

**Comment by robgpeak** [comment]
@cgladue please remove the "shopping trip chart" from the top of the Activity Stream page.  While I like it, I would rather have that and other charts and data like it on a separate page "Analytics" https://app.moqups.com/robg/QSDVx2F07W/edit/page/a2ad077fb
