### ISSUE TITLE
End User Analytics

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#89]
@ChrisASearles @cgladue This should be thought about from the perspective of, "What are people searching for, (i.e. store names, products, terms, etc.) from the search bar on our site?"  "What links are they click on within our site to navigate within it?" What links are they clicking on to start a shopping trip?  (i.e. The "Shop Now" button from Store Box on category page, the "Shop Now" button from a particular Deal, if so which ones).  Then I would like to tie those metrics to shopping trips, and see which are converting into sales.  The value of the sales, etc.  

This page is a work in progress, but it's a start...  https://app.moqups.com/robg/QSDVx2F07W/edit/page/a2ad077fb

I am not sure where to prioritize this on the list of things to do, but we should be thinking about it because it is important.  Actually, it would seem to me, that if we are already tracking shopping trips and gathering that type of data anyway, this is very similar, yes?

**Comment by ChrisASearles** [comment]
@robgpeak Do you have a Google Analytics account?

**Comment by robgpeak** [comment]
I just set you up with access, you should have just gotten an email.

**Comment by ChrisASearles** [comment]
For the initial release I've included Google Analytics on the page. That should give a good starting point of data that we can add to one-by-one in the future to extend the default functionality and tie analytics data to individual user actions.

@robgpeak I excluded our IP address from analytics but you should do the same with yours and @cgladue's

**Comment by cgladue** [comment]
just an FYI i am currently doing the following:

1. Every link clicked increments a counter for that link
2. Every shopping trip that gets started the link ID is recorded on that trip as well as the user and date
3. If the user clicks the main store shop now button that is recorded as link ID 0
4. every time a user clicks a link i record and increment a counter grouped by advertiser, by partner, by day
![image](https://cloud.githubusercontent.com/assets/7914133/26651960/56fabdf0-461c-11e7-9220-52b7fdbcef0c.png)
5. Every time an advertiser is viewed a counter on the advertiser increments.

**Comment by ChrisASearles** [comment]
@cgladue are you filtering that traffic at all?

**Comment by cgladue** [comment]
filtering what traffic ?

**Comment by ChrisASearles** [comment]
The page load that triggers the counter to increment. That data becomes wildly inaccurate after a short period of time once crawlers come into play. I've had that problem in the past and found it's better not to even bother and run it through an analytics engine instead where we have better control over filters.

**Comment by cgladue** [comment]
its only for authenticated users.  So i dont think crawlers will cause it to happen

**Comment by ChrisASearles** [comment]
The start trip click should be fine b/c it requires an authenticated user, really just the advertiser page view stuff.

**Comment by ChrisASearles** [comment]
ha, beat me to it.

**Comment by cgladue** [comment]
so not just starting a a trip but just an authenenticated user viewing an advertiser page will increment the counter as well,.

**Comment by cgladue** [comment]
oh, and also recording the last login date and time, but since wants a perpetual login cookie that may not be accurate any longer.

**Comment by robgpeak** [comment]
@cgladue as per @ChrisASearles suggestion of removing our IPs from the Google Analytics tracking, please let me have your IP address at work and the same when you get home...

**Comment by cgladue** [comment]
@robgpeak Published

**Comment by cgladue** [comment]
Work IP: 65.114.186.10
Home (Not Static): 68.114.60.150

**Comment by robgpeak** [comment]
Not static, but I am sure it remains the same for a good bit of time, while you are still logged into the same session with your ISP.
