### ISSUE TITLE
Login dialog 'x' doesn't close dialog

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#9]

**Comment by Dwells7583** [comment]
@ChrisASearles  Can you add the close function for me please.

**Comment by ChrisASearles** [comment]
Done with changes, details in #20.

**Comment by ChrisASearles** [comment]
This issue is technically fixed but I had to move the dialog out of a template and into the layout page because of the anti-forgery token in the login and it created a new issue where the dialog seems to think it's parent is only the left half of the page. Still trying to track down the cause of this but I will add that as a new issue.
