### ISSUE TITLE
Login dialog display issues

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#90]
I broke the look of this when I had to migrate it into the Layout page as documented in #9. At the same time, I hate the accent color background at the bottom, and some of my changes also caused some of the text decoration and color changes to revert back to browser defaults on the Create Account link. All of these items need to be fixed.

**Comment by Dwells7583** [comment]
@ChrisASearles  Can you go in and take a look at the register section. Specifically the Input fields.

**Comment by ChrisASearles** [comment]
@Dwells7583 I'm going to commit my version. I broke the T&C and privacy overlays after splitting the forms, I also can't figure out why the login dialog is getting cut off on the bottom, and I still need to test the functionality. Can you take a look at the display issue on the login dialog and try to fix that then let me know when I can get back in to finish it up.

**Comment by Dwells7583** [comment]
@ChrisASearles I committed my fix for the above. I tested the register and login with no issues for me.

**Comment by ChrisASearles** [comment]
@robgpeak I'm pushing this to you for review. I'd like to work on the terms and privacy overlays a little more but in the interest of focusing on higher priority items for now I want to put it on the backburner.

**Comment by robgpeak** [comment]
Again, please check it on mobile...
