### ISSUE TITLE
Category Model

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#92]
@cgladue based on conversations with the CL team and the design we're working up, we need to update the model for this view with the following elements:

1. Featured Stores - all stores within the category that have been featured
2. Featured Deals - all links for stores within the category that have been flagged as featured
3. All Stores - all stores for the category

This one we need to talk about with @robgpeak :
4. Ads - @Dwells7583 current design includes a couple of ads we pulled from the web but our thought was to use the ads that are uploaded to the networks and just insert those on the page. I know these were previously loaded into the admin section with the links but I believe has since been removed.

**Comment by robgpeak** [comment]
Regarding number 4, let's put this (other ads), on the backlog for after the initial release.  Have a look at comment 3 on the page https://app.moqups.com/robg/QSDVx2F07W/edit/page/ab309be6f to get an idea of what I was thinking for the **Extra Container**

**Comment by ChrisASearles** [comment]
@robgpeak yeah, we discussed that when you guys came in last but it seems a little odd and out of place on that page. Plus, at the moment, the only way we have to really identify a user is by their email address.

I know you're looking for ways to gamify but I'm not sure that's it. In the future we might be able to work in some of the gaming options you want to build out but we thought this might be a good way to fill the space for the time-being. Alternatively, might not be a bad idea to slap in some good-old-fashioned AdWords ads!

Happy to put it on the backburner but we'll have to figure out something else to fill the space for now. We'll work on something.

**Comment by robgpeak** [comment]
No Adwords.  That does not fit into the business model.  As for the leaderboard Idea, we will be capturing the users first name, just not at the initial registration.  We will backburner that for sure.

In the mean time, we can go with 8, or 10, or 12 "Similar Stores" to fill up some of that space.  Additionally, we can have Display Ads (say 300x250) in the **Extra Container** that rotate in from the back end.  @cgladue could make a separate page in the back end that would handle **Extra Container** content, as I would want this to be independent of the Advertisers Links section.

When I say rotate, I mean it would pull one ad at a time randomly from the list of 5 or 10 that we might have in the list at any given time.  We are NOT going to pull every banner link from the networks automatically, that would be WAY too many.  But we can figure out a way to populate this list in our db...

Here is a sample.  Of course the link would have to start a shopping trip as well...  

<a href="https://click.linksynergy.com/fs-bin/click?id=jLQ8qrFPMSA&offerid=486109.10020637&subid=0&type=4"><IMG border="0"   alt="Macys.com" src="https://ad.linksynergy.com/fs-bin/show?id=jLQ8qrFPMSA&bids=486109.10020637&subid=0&type=4&gridnum=13"></a>

**Comment by cgladue** [comment]
So you want me to start pulling banner ads and store separately and make them available similarly to links but in a different container ?  And these will be referred to as ads ?

**Comment by robgpeak** [comment]
Yeah, that's fine.  We can call them ads, and they should use the same starts on and expires on logic as the text links.  Let's keep the sizes consistent throughout. Only grab 300x250 ones, and maybe only grab ones that are listing in our Featured list.  Meaning, we only want to use big brand name stores...

**Comment by cgladue** [comment]
Ok so only banner ads for listing that are featured and only if they are 300x250px ?

**Comment by robgpeak** [comment]
Yeah I think that will be a good start.  And of course we can manually turn the off from appearing manually if need be

**Comment by robgpeak** [comment]
Meaning being able to turn them off  from appearing on the front end, on and individual ad basis.

**Comment by ChrisASearles** [comment]
You can drop them right in on the view Chad, spot should be there already
(pretty sure there are two right now).

On May 12, 2017 7:19 PM, "robgpeak" <notifications@github.com> wrote:

Meaning being able to turn them off from appearing on the front end, on and
individual ad basis.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChrisASearles/CompLinks/issues/92#issuecomment-301206569>,
or mute the thread

**Comment by cgladue** [comment]
#1,2,3 is done, the viewmodel look slike this:
`CategoryIndex vm = new CategoryIndex();

            vm.currentCategory = categories.Where(w => id == w.id).FirstOrDefault();
            vm.Advertisers = AdvertiserDAL.getAllAdvertisers(id, User.Identity.Name);
            vm.FeaturedAdvertisers = AdvertiserDAL.getFeaturedAdvertisersInCategory(User.Identity.Name, id);
            vm.FeaturedDeals = LinkDAL.getFeaturedDealsInCategory(User.Identity.Name, id);

            return View(vm);`

**Comment by cgladue** [comment]
@robgpeak @ChrisASearles @Dwells7583 ads are now added to Category ViewModel as well as the Store ViewModel...
