### ISSUE TITLE
Pull Banner Ads into AdvertiserAds Table

### ISSUE THREAD

**Issue by cgladue** [ChrisASearles/CompLinks#94]
@robgpeak wants to have Banner Ads for featured advertisers that are 300x250px to be loaded in the DB and made available to the front end.

**Comment by cgladue** [comment]
Ads are now being stored in AdvertiserAds table for featured advertiers and only 300x250px banner ads.  You can view advertiser Ads just like you view links from the advertiser maintenance screen.

**Comment by robgpeak** [comment]
When I click on Advertisers Ads from the actions menu I get a page error.  http://shop.complinks.co/admindashboard/advertisers/ads/6789

**Comment by cgladue** [comment]
this is because there are no ads for this advertiser, ill fix it so it
handles it nicer...



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=chadgladue@gmail.com&idSignature=22>



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
@robgpeak all set it will not throw an error if there are no ads, and the ads option wont even be available if its not in the featured category.

**Comment by robgpeak** [comment]
So http://shop.complinks.co/admindashboard/advertisers/ads/6789 is Macy's, and they are in the feature list, but I don't see any ads on this page I referenced?

**Comment by cgladue** [comment]
Press refresh again, it is corrected
