### ISSUE TITLE
Rounding Decimal Places of points/$

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#95]
Truthfully I would really only like to display AND calculate points in full or half points...  But I think for now we can at least limit it to Full, .25, .5 and .75...  I saw a few in there as ..375, and that should round DOWN to .25, and if something is .875, it should round down to .5.

**Comment by ChrisASearles** [comment]
@cgladue what will this take on your end?

**Comment by cgladue** [comment]
@ChrisASearles its not mathmatically difficult, but when if we start manipulating the percentages and rates this way it might not produce the intended result.

@robgpeak tell me again why you are wanting to only have these 4 values ?  all the math is done by the system and the user wont be seeing those calculations, and if you start rounding then people might start complaining that they spend $100 and only got 75 points and should of been 77, etc etc...  what do you accomplish by this?  i think it just makes the process more complicated.

i would say let them earn their points using as many decimal placesas the comission Rate * the Share Rate produces (7.75% comission * 50% share = 3.875% earnings, i can round on the display of the points so they wont know their "true" balance but i think the earning should be as accurate as possible especially when we are talking dollars and cents to fractions of points, things can get messy quickly with the rounding and stuff...

**Comment by robgpeak** [comment]
Sorry guys, give me a few to get back to you on this and some of the other issues, just dealing with something unrelated to business at the moment.  But keep cc'ing me and asking other questions of me on other topics.

**Comment by robgpeak** [comment]
OK, so how about we use just two decimal points as a max on the front end for visible aesthetics and consistency on the site, but pay the actual points earn to a customer.  So "3.875 Points/$" becomes "3.87 Points/$"  The other option would be to use just one decimal place and make it "3.8 Points/$" but of course still pay the full 3.875 points to the users account.

Thoughts?

**Comment by cgladue** [comment]
i think the 1 decimal place is the best idea, do you still want to only show point balance in whole points ?

**Comment by robgpeak** [comment]
Glad"ue" to hear you say that.  I think that is the optimal solution to use one decimal place on the front end site, but if we only show whole point balances to the user, how would that work?

I just bought something the other day for $318.14, and the front end told me I was getting 2.25 points/$.  I should be expecting 715.815 points.  In the new idea of showing only one decimal place on the front end, I would have seen 2.2 points/$, so as a user I would calculate the expected points to be 699.908.

So if we ARE going to issue points based on the REAL number that we get in terms of the commissions we received from the advertiser, there is going to be a disparity in the actual points issued.  It will ALWAYS be in the end users favor, so that's a good thing, but still not an exact calculation based on the customer's expectation.

This was why my though was to based on what we show.  So in my example about, if we paid 700 points for that transaction, that would be showing the whole points balance, but at a number that is closer to what was displayed to the end user.

So if we round down on the points we display, (.375 becomes .3, etc), and round up to a full point for balances, that seems like it might be the best solution to always work in the customers favor, and still keep things neat, clean and simple...  Thoughts?

**Comment by cgladue** [comment]
@robgpeak i think i am rounding to 1 decimal place as you outlined...
