### ISSUE TITLE
Changing .icon and page titles

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#98]
There are several pages that I noticed the CL .icon image not showing up, mainly in the back end.  And the titles should be change to read "CompLinks - Casino Rewards Everywhere"

Notice the "L" in CompLinks.

If it possible or warranted, maybe we can have the name of the page dynamically appear in the title as well.  i.e. "CompLinks - Casino Rewards Everywhere - Advertisers", "CompLinks - Casino Rewards Everywhere - Macy's", "CompLinks - Casino Rewards Everywhere - Bloomingdale's", etc.

Also, I notice "CompLinks - Casino Rewards Everywhere - Advertisers" shows up as the title on shop.complinks.co/, but does not show up without the "/".

Lastly, and this might be a back burner thing, but something to think about is the page title naming convention for the subdomains...  Just thinking out loud, maybe "Capital Club - Rewards Everywhere - Advertisers" or "Foxwoods - Rewards Everywhere - Home Depot".

Even though right now we are calling the subdomain Dover Downs, the name of their rewards program is Capital Club, and I think it makes more sense to use that brand name.
![uploads/cc8932c1-272f-45d5-abc1-284b9d5de595/Screenshot_2017-05-14-08-04-41.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fcc8932c1-272f-45d5-abc1-284b9d5de595%2FScreenshot_2017-05-14-08-04-41.png)

**Comment by cgladue** [comment]
i went through the backend and changed the pages i could locate that had incorrect titles...

**Comment by ChrisASearles** [comment]
I'm working on this on the front-end with the rest of the theming stuff.

**Comment by ChrisASearles** [comment]
All front-end pages have titles and those titles will change based on the partner being viewed.

**Comment by cgladue** [comment]
Published
