### ISSUE TITLE
Add a filter to the Advertisers in list view

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#99]
@cgladue Please put a filter on the Advertiser list view as per attached mock up
![uploads/b377889b-dc88-4d68-a3ce-7fee9a078cc8/Screen Shot 2017-05-14 at 10.01.38 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fb377889b-dc88-4d68-a3ce-7fee9a078cc8%2FScreen+Shot+2017-05-14+at+10.01.38+AM.png)

**Comment by cgladue** [comment]
![image](https://cloud.githubusercontent.com/assets/7914133/26035196/7f8309dc-3896-11e7-92f6-91acd284505a.png)

**Comment by robgpeak** [comment]
sweet!
